In [1]:

!git clone https://github.com/causalNLP/logical-fallacy.git

Cloning into 'logical-fallacy'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 254 (delta 44), reused 29 (delta 28), pack-reused 181 (from 1)
Receiving objects: 100% (254/254), 10.55 MiB | 7.19 MiB/s, done.
Resolving deltas: 100% (94/94), done.

In [2]:

import os

project_path = "/content/logical-fallacy"

print("Project downloaded:", os.path.exists(project_path))
print("\nDataset files:")

for file in os.listdir(project_path + "/data"):
    print(file)

Project downloaded: True

Dataset files:
climate_all.csv
edu_test.csv
climate_train.csv
mappings.csv
climate_test_mh.csv
climate_train_mh.csv
edu_train.csv
climate_dev_mh.csv
climate_test.csv
edu_dev.csv
climate_dev.csv
edu_all.csv

In [9]:
#Checking Dataset

In [3]:

import os

data_path = "/content/logical-fallacy/data"

print("Dataset files available:\n")

for file in os.listdir(data_path):
    if file.endswith(".csv"):
        print(file)

Dataset files available:

climate_all.csv
edu_test.csv
climate_train.csv
mappings.csv
climate_test_mh.csv
climate_train_mh.csv
edu_train.csv
climate_dev_mh.csv
climate_test.csv
edu_dev.csv
climate_dev.csv
edu_all.csv

In [4]:

import pandas as pd

train_df = pd.read_csv("/content/logical-fallacy/data/edu_train.csv")
dev_df = pd.read_csv("/content/logical-fallacy/data/edu_dev.csv")
test_df = pd.read_csv("/content/logical-fallacy/data/edu_test.csv")

print("Training dataset:", train_df.shape)
print("Validation dataset:", dev_df.shape)
print("Testing dataset:", test_df.shape)

print("\nColumn names:")
print(train_df.columns.tolist())

print("\nFirst 5 rows:")
display(train_df.head())

Training dataset: (1849, 12)
Validation dataset: (300, 13)
Testing dataset: (300, 13)

Column names:
['Unnamed: 0.2', 'Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1', 'Unnamed: 0.1.1.1.1', 'Unnamed: 0.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1.1', 'source_article', 'updated_label', 'masked_articles']

First 5 rows:

,Unnamed: 0.2,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,Unnamed: 0.1.1.1.1.1.1,Unnamed: 0.1.1.1.1.1.1.1,source_article,updated_label,masked_articles
0,0,0,0,0,0,0,0,0,1436,"company's slogan ""Expect More. Pay Less.""",appeal to emotion,"company 's slogan "" Expect More . Pay Less . """
1,1,1,1,1,1,1,1,1,557,"The bigger a child's shoe size, the better the...",false causality,"The bigger MSK<0> shoe size , the better MSK<0..."
2,2,2,2,2,2,2,2,2,772,"Since many people believe this, then it must b...",ad populum,"Since many people believe this , then it must ..."
3,3,3,3,3,3,3,3,3,625,Senator Randall isn't lying when she says she ...,circular reasoning,MSK<0> is n't MSK<1> when MSK<0> says MSK<0> M...
4,4,4,4,4,4,4,4,4,1843,A mother is telling her daughter that she went...,fallacy of relevance,MSK<0> is MSK<1> MSK<2> that MSK<0> went over ...

In [5]:

print("Fallacy categories:")
print(train_df["updated_label"].value_counts())

print("\nNumber of unique categories:",
      train_df["updated_label"].nunique())

Fallacy categories:
updated_label
faulty generalization     319
ad hominem                225
false causality           174
ad populum                158
circular reasoning        134
appeal to emotion         130
fallacy of logic          121
fallacy of relevance      114
intentional               112
false dilemma             110
fallacy of credibility    107
fallacy of extension      106
equivocation               39
Name: count, dtype: int64

Number of unique categories: 13

In [6]:

print("Missing values:")
print(train_df[["source_article", "updated_label"]].isnull().sum())

print("\nDuplicate rows:", train_df.duplicated().sum())

Missing values:
source_article    0
updated_label     0
dtype: int64

Duplicate rows: 0

In [7]:
#Cleaning Data Set

In [8]:

import pandas as pd

# Keep only the useful columns
required_columns = [
    "source_article",
    "updated_label",
    "masked_articles"
]

train_df = train_df[required_columns].copy()
dev_df = dev_df[required_columns].copy()
test_df = test_df[required_columns].copy()

# Remove rows with missing text or labels, if any
for df in [train_df, dev_df, test_df]:
    df.dropna(subset=["source_article", "updated_label"], inplace=True)
    df["source_article"] = df["source_article"].astype(str).str.strip()
    df["updated_label"] = df["updated_label"].astype(str).str.strip()
    df.drop(
        df[(df["source_article"] == "") |
           (df["updated_label"] == "")].index,
        inplace=True
    )

# Display the cleaned data
print("Cleaned dataset sizes:")
print("Training:", train_df.shape)
print("Validation:", dev_df.shape)
print("Testing:", test_df.shape)

print("\nCleaned columns:")
print(train_df.columns.tolist())

display(train_df.head())

Cleaned dataset sizes:
Training: (1849, 3)
Validation: (300, 3)
Testing: (300, 3)

Cleaned columns:
['source_article', 'updated_label', 'masked_articles']

,source_article,updated_label,masked_articles
0,"company's slogan ""Expect More. Pay Less.""",appeal to emotion,"company 's slogan "" Expect More . Pay Less . """
1,"The bigger a child's shoe size, the better the...",false causality,"The bigger MSK<0> shoe size , the better MSK<0..."
2,"Since many people believe this, then it must b...",ad populum,"Since many people believe this , then it must ..."
3,Senator Randall isn't lying when she says she ...,circular reasoning,MSK<0> is n't MSK<1> when MSK<0> says MSK<0> M...
4,A mother is telling her daughter that she went...,fallacy of relevance,MSK<0> is MSK<1> MSK<2> that MSK<0> went over ...

In [10]:

print("Training labels:", train_df["updated_label"].nunique())
print("\nLabel distribution:")
print(train_df["updated_label"].value_counts())

print("\nLabels missing from validation:")
print(set(train_df["updated_label"]) - set(dev_df["updated_label"]))

print("\nLabels missing from testing:")
print(set(train_df["updated_label"]) - set(test_df["updated_label"]))

Training labels: 13

Label distribution:
updated_label
faulty generalization     319
ad hominem                225
false causality           174
ad populum                158
circular reasoning        134
appeal to emotion         130
fallacy of logic          121
fallacy of relevance      114
intentional               112
false dilemma             110
fallacy of credibility    107
fallacy of extension      106
equivocation               39
Name: count, dtype: int64

Labels missing from validation:
set()

Labels missing from testing:
set()

In [ ]:
#Training Model

In [11]:

import os

repo = "/content/logical-fallacy"

print("Repository instructions:")
for file in ["README.md", "codes_for_models/README.md",
             "codes_for_models/finetune/README.md",
             "saved_models/README.md"]:
    path = os.path.join(repo, file)
    print(f"\n--- {file} ---")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            print(f.read()[:5000])
    else:
        print("File not found")

Repository instructions:

--- README.md ---
# Logical Fallacy Detection
Repo for the paper "[Logical Fallacy Detection
](https://arxiv.org/abs/2202.13758)" (Findings of EMNLP 2022) by _Abhinav Lalwani*, Zhijing Jin*, Tejas Vaidhya, Xiaoyu Shen, Yiwen Ding, Zhiheng Lyu, Mrinmaya Sachan, Rada Mihalcea, Bernhard Schoelkopf_.

#### Dataset
Feel free to access our data in the `data/` folder.

Currently, all the data are annotated in the sentence format. In addition, if you need detailed source of our climate data, especially in the form of original articles, we have them collected in [this spreadsheet](https://docs.google.com/spreadsheets/d/1AHyjRkXk4xEmRWGc-k07LA1lflZQK9UIOw921zXZLqA/edit#gid=0).

#### To cite the paper:
```bibtex
@inproceedings{jin-etal-2022-logical,
    title = "Logical Fallacy Detection",
    author = "Jin, Zhijing  and
      Lalwani, Abhinav  and
      Vaidhya, Tejas  and
      Shen, Xiaoyu  and
      Ding, Yiwen  and
      Lyu, Zhiheng  and
      Sachan, Mrinmaya  and
      Mihalcea, Rada  and
      Schoelkopf, Bernhard",
    editor = "Goldberg, Yoav  and
      Kozareva, Zornitsa  and
      Zhang, Yue",
    booktitle = "Findings of the Association for Computational Linguistics: EMNLP 2022",
    month = dec,
    year = "2022",
    address = "Abu Dhabi, United Arab Emirates",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2022.findings-emnlp.532",
    doi = "10.18653/v1/2022.findings-emnlp.532",
    pages = "7180--7198",
    abstract = "Reasoning is central to human intelligence. However, fallacious arguments are common, and some exacerbate problems such as spreading misinformation about climate change. In this paper, we propose the task of logical fallacy detection, and provide a new dataset (Logic) of logical fallacies generally found in text, together with an additional challenge set for detecting logical fallacies in climate change claims (LogicClimate). Detecting logical fallacies is a hard problem as the model must understand the underlying logical structure of the argument. We find that existing pretrained large language models perform poorly on this task. In contrast, we show that a simple structure-aware classifier outperforms the best language model by 5.46{\%} F1 scores on Logic and 4.51{\%} on LogicClimate. We encourage future work to explore this task since (a) it can serve as a new reasoning challenge for language models, and (b) it can have potential applications in tackling the spread of misinformation. Our dataset and code are available at \url{https://github.com/causalNLP/logical-fallacy}",
}
```

#### Contact:
- For future collaboration requests, feel free to email Zhijing Jin and Mrinmaya Sachan.
- For coding questions, feel free to email Abhinav Lalwani.
- For dataset collection-related questions,feel free to email Abhinav Lalwani, Zhijing Jin, and Yiwen Ding.


--- codes_for_models/README.md ---
File not found

--- codes_for_models/finetune/README.md ---
Code changed from https://github.com/huggingface/transformers/tree/master/examples/legacy/seq2seq

## Requirements

pytorch 1.7.1
transformers 4.10

## How to Run
train the model:
```bash
python main.py train.json
```

output the probability:
```bash
python main.py test.json
```

## Parameters
train.json
```
{
"tokenizer_name": "../../results/fallacy/deberta/best-epoch",
"model_name": "../../results/fallacy/deberta/best-epoch",
"freeze_encoder": false, # optional, we set to false
"freeze_embeds": false, # optional, we set to false
"data_dir": "../../datasets/fallacy/sentence/",
"max_source_length": 128,
"task_type": "sequence_matching",
"mode": "train", # file name
"test_type": "dev",

"num_labels":3, # NLI's 0,1,2
"output_dir": "../../results/fallacy/propa/deberta", # save checkpoints to this
"do_train": true,
"evaluation_strategy": "steps", # evaluate by every X steps
"overwrite_output_dir": true,
"per_device_train_batch_size": 8,
"per_device_eval_batch_size": 128,
"eval_steps": 300,
"save_total_limit": 1, # how many checkpoints to save
"load_best_model_at_end": true,
"logging_steps": 300,
"fp16": false,
"gradient_accumulation_steps": 2,
"save_steps": 30000000000,  # we don't need to save intermediate steps, so we set it to a super large number
"logging_dir": "../../results/fallacy/propa/logs",
"num_train_epochs": 5, # we didn't tune this, just set 5 for all models
"seed": 42, # we set a random seed
"warmup_steps": 1931,
"learning_rate": 1e-05
}
```

test.json
```
{
"tokenizer_name": "../../results/fallacy/finetuned/roberta/best-epoch",
"model_name": "../../results/fallacy/finetuned/roberta/best-epoch",
"data_dir": "../../datasets/fallacy/article/",
"max_source_length": 512, # bigbird 4096
"task_type": "sequence_matching", # always set to this
"mode": "output_prob",

"num_labels":3,
"test_type": "test", # file name
"output_dir": "../../results/fallacy/finetuned/roberta", # save probs to a txt file of probs
"per_device_eval_batch_size": 64,
"fp16": false # mobilebert does not support this
}
```

--- saved_models/README.md ---
## How to use the pretrained models

Pretrained Models can be downloaded from this [link](https://drive.google.com/drive/folders/13icpZY_HNemv9Da14fYEyw8EfoxEvKQZ?usp=sharing)


The model follows Huggingface standard format, for how to use models， you can refer the code in the file `codes_for_models/experiments_round2/logicedu.py` , and use the appropriate flags

Here is an example on how to load the models:

```python
import transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model =  AutoModelForSequenceClassification.from_pretrained('path_to_saved_model', num_labels=3)
tokenizer = AutoTokenizer.from_pretrained('path_to_tokenizer', do_lower_case=True)

In [12]:

import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.11.0+cpu
GPU available: False

In [1]:

import torch

print("PyTorch:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

PyTorch: 2.11.0+cu130
GPU available: True
GPU name: Tesla T4

In [2]:

import os

repo = "/content/logical-fallacy"

print("Training script exists:",
      os.path.exists(
          repo + "/codes_for_models/experiments_round2/logicedu.py"
      ))

print("\nAvailable model folders:")
for folder in ["saved_models", "results", "datasets"]:
    path = os.path.join(repo, folder)
    print(f"\n{folder}:",
          os.listdir(path)[:15] if os.path.isdir(path)
          else "Not present")

Training script exists: False

Available model folders:

saved_models: Not present

results: Not present

datasets: Not present

In [3]:

import os

repo = "/content/logical-fallacy"

print("Repository exists:", os.path.exists(repo))

print("\nTraining-related Python files:")
for root, dirs, files in os.walk(repo):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "__pycache__"]
    ]

    for file in files:
        if file.endswith(".py") and any(
            word in file.lower()
            for word in ["train", "logic", "experiment", "main"]
        ):
            print(os.path.relpath(
                os.path.join(root, file), repo
            ))

print("\nSaved-model or checkpoint directories:")
for root, dirs, files in os.walk(repo):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "__pycache__"]
    ]

    if any(word in root.lower()
           for word in ["saved_models", "checkpoint", "results"]):
        print(os.path.relpath(root, repo))

Repository exists: False

Training-related Python files:

Saved-model or checkpoint directories:

In [4]:

!git clone https://github.com/causalNLP/logical-fallacy.git

Cloning into 'logical-fallacy'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 254 (delta 44), reused 29 (delta 28), pack-reused 181 (from 1)
Receiving objects: 100% (254/254), 10.55 MiB | 12.71 MiB/s, done.
Resolving deltas: 100% (94/94), done.

In [5]:

import os

repo = "/content/logical-fallacy"

print("Repository exists:", os.path.exists(repo))
print("\nTop-level files:")
print(os.listdir(repo)[:20] if os.path.exists(repo)
      else "Repository not found")

Repository exists: True

Top-level files:
['README.md', '.gitignore', 'codes_to_get_data', 'codes_for_analysis', 'saved_models', 'data', '.git', 'codes_for_models']

In [6]:

import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

GPU available: True
Tesla T4

In [7]:

import os

repo = "/content/logical-fallacy"

print("Training-related Python files:\n")

for root, dirs, files in os.walk(repo):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "__pycache__"]
    ]

    for file in files:
        if file.endswith(".py") and any(
            word in file.lower()
            for word in ["train", "logic", "experiment", "main"]
        ):
            print(os.path.relpath(
                os.path.join(root, file), repo
            ))

Training-related Python files:

codes_for_models/finetune/main.py
codes_for_models/experiments_round2/logicclimate_split.py
codes_for_models/experiments_round2/logicclimate.py
codes_for_models/experiments_round2/logicedu.py
codes_for_models/experiments_round2/experiment.py

In [8]:

readme = "/content/logical-fallacy/saved_models/README.md"

with open(readme, "r", encoding="utf-8") as f:
    print(f.read())

print("\nSaved-model folder contents:")
print(os.listdir("/content/logical-fallacy/saved_models"))

## How to use the pretrained models

Pretrained Models can be downloaded from this [link](https://drive.google.com/drive/folders/13icpZY_HNemv9Da14fYEyw8EfoxEvKQZ?usp=sharing)


The model follows Huggingface standard format, for how to use models， you can refer the code in the file `codes_for_models/experiments_round2/logicedu.py` , and use the appropriate flags

Here is an example on how to load the models:

```python
import transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model =  AutoModelForSequenceClassification.from_pretrained('path_to_saved_model', num_labels=3)
tokenizer = AutoTokenizer.from_pretrained('path_to_tokenizer', do_lower_case=True)


Saved-model folder contents:
['README.md']

In [9]:

print("train_df exists:", "train_df" in globals())
print("dev_df exists:", "dev_df" in globals())
print("test_df exists:", "test_df" in globals())

train_df exists: False
dev_df exists: False
test_df exists: False

In [10]:

import pandas as pd
import os

data_path = "/content/logical-fallacy/data"

train_df = pd.read_csv(os.path.join(data_path, "edu_train.csv"))
dev_df = pd.read_csv(os.path.join(data_path, "edu_dev.csv"))
test_df = pd.read_csv(os.path.join(data_path, "edu_test.csv"))

required_columns = [
    "source_article",
    "updated_label",
    "masked_articles"
]

train_df = train_df[required_columns].dropna(
    subset=["source_article", "updated_label"]
).copy()

dev_df = dev_df[required_columns].dropna(
    subset=["source_article", "updated_label"]
).copy()

test_df = test_df[required_columns].dropna(
    subset=["source_article", "updated_label"]
).copy()

print("Training:", train_df.shape)
print("Validation:", dev_df.shape)
print("Testing:", test_df.shape)
print("Fallacy categories:", train_df["updated_label"].nunique())

Training: (1849, 3)
Validation: (300, 3)
Testing: (300, 3)
Fallacy categories: 13

In [11]:

script_path = (
    "/content/logical-fallacy/"
    "codes_for_models/experiments_round2/logicedu.py"
)

with open(script_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

print("Script length:", len(lines), "lines")

print("\nTraining configuration and arguments:")
for i, line in enumerate(lines):
    if any(term in line.lower() for term in [
        "add_argument", "def train(", "def main(",
        "from_pretrained", "savepath", "train_strat",
        "do_not_train", "argparse"
    ]):
        print(f"{i+1}: {line.rstrip()}")

Script length: 519 lines

Training configuration and arguments:
14: import argparse
53:                  train_strat=1, test_strat=1, multilabel=False):
60:         self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, do_lower_case=True)
78:                        undersample_ratio=undersample_rate, train_strat=train_strat, test_strat=test_strat)
131:                   undersample_ratio=0.02, train_strat=1, test_strat=1):
134:                                                  undersampling_rate=undersample_ratio, strat=train_strat)
300: def train(model, dataset, optimizer, logger, save_path, device, epochs=5, ratio=0.04, positive_weight=12, debug=False):
437:     parser = argparse.ArgumentParser()
438:     parser.add_argument("-t", "--tokenizer", help="tokenizer path")
439:     parser.add_argument("-m", "--model", help="model path")
440:     parser.add_argument("-w", "--weight", help="Weight of entailment loss")
441:     parser.add_argument("-s", "--savepath", help="Path to save logicedu model")
442:     parser.add_argument("-f", "--finetune", help="Set this flag if you want to finetune the model on MNLI", default='F')
443:     parser.add_argument("-sf", "--savepath2", help="Path to save mnli model", default="mnli")
444:     parser.add_argument("-mp", "--map", help="Map labels to this category")
445:     parser.add_argument("-ts", "--train_strat", help="Strategy number for training")
446:     parser.add_argument("-ds", "--dev_strat", help="Strategy number for development and testing")
447:     parser.add_argument("-rs", "--replace_strat", help="Function used to replace masked words", default='char')
448:     parser.add_argument("-rc", "--replace_count", help="Number of times to replace masked words", default=1)
449:     parser.add_argument("-np", "--multinli_path", help="Path for multinli directory", default="")
450:     parser.add_argument("-do", "--downsample", help="Downsample Training Set", default='F')
451:     parser.add_argument("-c", "--classwise_savepath", help="Path to store classwise results")
452:     parser.add_argument("-sr", "--result_path", help="Path to store results on dev set")
453:     parser.add_argument("-nt", "--do_not_train", help="Set this to T if you do not wish to train the model",
459:     model = AutoModelForSequenceClassification.from_pretrained(args.model, num_labels=3)
478:         train(model, mnli_ds, optimizer, logger, args.savepath2, ratio=1, epochs=10, positive_weight=1)
480:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath2)
490:                              fallacy=True, train_strat=int(args.train_strat), test_strat=int(args.dev_strat))
496:     if args.do_not_train == 'F':
499:         train(model, fallacy_ds, optimizer, logger, args.savepath, device, ratio=1, epochs=10,
502:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath, num_labels=3)
509:     if args.classwise_savepath is not None:
514:         df.to_csv(args.classwise_savepath)

In [12]:

import os

model_path = "/content/electra-logic-structaware"
os.makedirs(model_path, exist_ok=True)

print("Model folder created:", model_path)

Model folder created: /content/electra-logic-structaware

In [13]:

import os
import shutil

for filename in ["config.json", "pytorch_model.bin"]:
    source = "/content/" + filename
    destination = os.path.join(model_path, filename)

    if os.path.exists(source):
        shutil.move(source, destination)
        print("Moved:", filename)
    elif os.path.exists(destination):
        print("Already present:", filename)
    else:
        print("MISSING:", filename)

print("\nFiles in model folder:")
print(os.listdir(model_path))

Already present: config.json
Already present: pytorch_model.bin

Files in model folder:
['config.json', 'pytorch_model.bin']

In [14]:

import json

config_file = os.path.join(model_path, "config.json")

with open(config_file, "r", encoding="utf-8") as f:
    config = json.load(f)

for key in ["model_type", "architectures", "num_labels",
            "id2label", "label2id"]:
    print(f"{key}:", config.get(key, "Not specified"))

model_type: electra
architectures: ['ElectraForSequenceClassification']
num_labels: Not specified
id2label: {'0': 'LABEL_0', '1': 'LABEL_1', '2': 'LABEL_2'}
label2id: {'LABEL_0': 0, 'LABEL_1': 1, 'LABEL_2': 2}

In [15]:

import os

repo = "/content/logical-fallacy"

keywords = [
    "tokenizer_config.json",
    "special_tokens_map.json",
    "vocab.txt",
    "tokenizer.json"
]

print("Tokenizer files found:\n")

for root, dirs, files in os.walk(repo):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "__pycache__"]
    ]

    for filename in files:
        if filename in keywords:
            print(os.path.join(root, filename))

Tokenizer files found:

In [16]:

import os

print("Checkpoint files:")
for filename in os.listdir("/content/electra-logic-structaware"):
    print(filename)

Checkpoint files:
config.json
pytorch_model.bin

In [17]:

script_path = (
    "/content/logical-fallacy/"
    "codes_for_models/experiments_round2/logicedu.py"
)

with open(script_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for start, end in [(40, 75), (450, 505)]:
    print(f"\n--- Lines {start}-{end} ---")
    for i in range(start - 1, min(end, len(lines))):
        print(f"{i+1}: {lines[i].rstrip()}")

--- Lines 40-75 ---
40:                     labels_dict[lbl] = 0
41:                 labels_dict[lbl] += 1
42:     return list(labels_dict.keys()), labels_dict
43:
44:
45: def replace_random_sample(i):
46:     return sample(word_bank, 1)[0]
47:
48:
49: class MNLIDataset:
50:
51:     def __init__(self, tokenizer_path, train_df, val_df, label_col_name, map='base', test_df=None, fallacy=False,
52:                  undersample_train=False, undersample_val=False, undersample_test=False, undersample_rate=0.04,
53:                  train_strat=1, test_strat=1, multilabel=False):
54:         # strat is used in convert_to_mnli function
55:         self.label_dict = {'entailment': 0, 'contradiction': 1, 'neutral': 2}
56:         torch.manual_seed(0)
57:         self.train_df = train_df
58:         self.val_df = val_df
59:         self.test_df = test_df
60:         self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, do_lower_case=True)
61:         special_tokens_dict = {
62:             'additional_special_tokens': ["[A]", "[B]", "[C]", "[D]", "[E]", "[F]", "[G]", "[H]", "[I]"]}
63:         self.tokenizer.add_special_tokens(special_tokens_dict)
64:         self.train_data = None
65:         self.val_data = None
66:         self.label_col_name = label_col_name
67:         self.map = map
68:         self.mappings = pd.read_csv("../../data/mappings.csv")
69:         self.multilabel = multilabel
70:         if fallacy:
71:             self.unique_labels, self.counts_dict = get_unique_labels(pd.concat([train_df, val_df, test_df]),
72:                                                                      self.label_col_name,
73:                                                                      multilabel)
74:             self.total_count = 0
75:             for count in self.counts_dict.values():

--- Lines 450-505 ---
450:     parser.add_argument("-do", "--downsample", help="Downsample Training Set", default='F')
451:     parser.add_argument("-c", "--classwise_savepath", help="Path to store classwise results")
452:     parser.add_argument("-sr", "--result_path", help="Path to store results on dev set")
453:     parser.add_argument("-nt", "--do_not_train", help="Set this to T if you do not wish to train the model",
454:                         default='F')
455:     args = parser.parse_args()
456:     # word_bank = pickle.load('../../data/word_bank.pkl')
457:     logger.info(args)
458:     logger.info("initializing model")
459:     model = AutoModelForSequenceClassification.from_pretrained(args.model, num_labels=3)
460:     model.to(device)
461:
462:     if args.finetune == 'T':
463:         logger.info("initializing mnli dataset")
464:         mnli_train = pd.read_csv(args.multinli_path + "/multinli_1.0_train.txt", sep='\t',
465:                                  skiprows=[24809, 33960, 75910, 100113, 150637, 158833, 173103, 178251, 221950, 286844,
466:                                            314109])[['gold_label', 'sentence1', 'sentence2']]
467:         mnli_train = mnli_train.dropna()
468:         mnli_dev_matched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_matched.txt", sep='\t')[
469:             ['gold_label', 'sentence1', 'sentence2']]
470:         mnli_dev_mismatched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_mismatched.txt", sep='\t')[
471:             ['gold_label', 'sentence1', 'sentence2']]
472:         mnli_dev = pd.concat([mnli_dev_matched, mnli_dev_mismatched], ignore_index=True, sort=False)
473:         mnli_dev = mnli_dev.dropna()
474:         mnli_dev = mnli_dev[mnli_dev.gold_label != '-']
475:         mnli_ds = MNLIDataset(args.tokenizer, mnli_train, mnli_dev, 'gold_label', fallacy=False)
476:         logger.info("finetune on mnli")
477:         optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
478:         train(model, mnli_ds, optimizer, logger, args.savepath2, ratio=1, epochs=10, positive_weight=1)
479:         logger.info("reinit model")
480:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath2)
481:         model.to(device)
482:     optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
483:     logger.info("creating dataset")
484:     fallacy_train = pd.read_csv('../../data/edu_train.csv')
485:     if args.downsample == 'T':
486:         fallacy_train = fallacy_train[:747]
487:     fallacy_dev = pd.read_csv('../../data/edu_dev.csv')
488:     fallacy_test = pd.read_csv('../../data/edu_test.csv')
489:     fallacy_ds = MNLIDataset(args.tokenizer, fallacy_train, fallacy_dev, 'updated_label', args.map, fallacy_test,
490:                              fallacy=True, train_strat=int(args.train_strat), test_strat=int(args.dev_strat))
491:     model.resize_token_embeddings(len(fallacy_ds.tokenizer))
492:     fallacy_ds.train_df.to_csv('processed_train_df.csv')
493:     fallacy_ds.val_df.to_csv('processed_val_df.csv')
494:     # print(fallacy_ds.tokenizer.tokenize("[A] causes [B]"))
495:     # print("checking length", len(fallacy_ds.tokenizer), model.config.vocab_size)
496:     if args.do_not_train == 'F':
497:         optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
498:         logger.info("starting training")
499:         train(model, fallacy_ds, optimizer, logger, args.savepath, device, ratio=1, epochs=10,
500:               positive_weight=int(args.weight))
501:
502:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath, num_labels=3)
503:         model.to(device)
504:     logger.info("starting testing")
505:     _, _, test_loader = fallacy_ds.get_data_loaders()

In [18]:

import json

config_path = "/content/electra-logic-structaware/config.json"

with open(config_path, "r", encoding="utf-8") as f:
    config = json.load(f)

print("Model type:", config.get("model_type"))
print("Model architecture:", config.get("architectures"))
print("Vocabulary size:", config.get("vocab_size"))
print("Hidden size:", config.get("hidden_size"))
print("Number of attention heads:", config.get("num_attention_heads"))
print("Number of layers:", config.get("num_hidden_layers"))
print("Special token IDs:")
for key in ["pad_token_id", "bos_token_id", "eos_token_id"]:
    print(key, ":", config.get(key))

Model type: electra
Model architecture: ['ElectraForSequenceClassification']
Vocabulary size: 30531
Hidden size: 768
Number of attention heads: 12
Number of layers: 12
Special token IDs:
pad_token_id : 0
bos_token_id : None
eos_token_id : None

In [19]:

!pip install -q transformers

In [20]:

from transformers import AutoTokenizer

# Candidate base tokenizer for ELECTRA
tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator",
    do_lower_case=True
)

print("Original tokenizer vocabulary:", len(tokenizer))

# Match the special tokens used by the original research code
special_tokens = {
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
}

tokenizer.add_special_tokens(special_tokens)

print("Vocabulary after adding special tokens:", len(tokenizer))
print("Expected checkpoint vocabulary: 30531")

print("\nTokenization test:")
print(tokenizer.tokenize("This argument may contain a fallacy."))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Original tokenizer vocabulary: 30522
Vocabulary after adding special tokens: 30531
Expected checkpoint vocabulary: 30531

Tokenization test:
['this', 'argument', 'may', 'contain', 'a', 'fall', '##acy', '.']

In [21]:

import torch
from transformers import AutoModelForSequenceClassification

model_path = "/content/electra-logic-structaware"

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

# Move model to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("Model loaded successfully!")
print("Device:", device)
print("Model vocabulary size:", model.config.vocab_size)
print("Tokenizer vocabulary size:", len(tokenizer))
print("Number of output labels:", model.config.num_labels)

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory. This is an internal miniz error. If you are seeing this error, there is a high likelihood that your checkpoint file is corrupted. This can happen if the checkpoint was not saved properly, was transferred incorrectly, or the file was modified after saving.

In [22]:

import os

model_path = "/content/electra-logic-structaware"
weights_path = os.path.join(model_path, "pytorch_model.bin")

print("File exists:", os.path.exists(weights_path))

if os.path.exists(weights_path):
    print("File size:", round(os.path.getsize(weights_path) / (1024 * 1024), 2), "MB")

    with open(weights_path, "rb") as f:
        print("First 20 bytes:", f.read(20))

File exists: True
File size: 8.0 MB
First 20 bytes: b'PK\x03\x04\x00\x00\x08\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

In [23]:

import os

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

if os.path.exists(weights_path):
    os.remove(weights_path)
    print("Incomplete checkpoint removed.")
else:
    print("No existing checkpoint found.")

Incomplete checkpoint removed.

In [24]:

import os

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

size_mb = os.path.getsize(weights_path) / (1024 * 1024)

print(f"Checkpoint size: {size_mb:.1f} MB")
print("Checkpoint looks complete:", size_mb > 400)

FileNotFoundError: [Errno 2] No such file or directory: '/content/electra-logic-structaware/pytorch_model.bin'

In [25]:

import os

print("Checking the expected folder...")

model_path = "/content/electra-logic-structaware"
print("Folder exists:", os.path.isdir(model_path))

if os.path.isdir(model_path):
    print("Files in model folder:")
    print(os.listdir(model_path))

print("\nSearching /content for pytorch_model.bin...")

for root, dirs, files in os.walk("/content"):
    dirs[:] = [d for d in dirs if d not in [".git", "__pycache__"]]

    if "pytorch_model.bin" in files:
        path = os.path.join(root, "pytorch_model.bin")
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"Found: {path} ({size_mb:.1f} MB)")

Checking the expected folder...
Folder exists: True
Files in model folder:
['config.json', 'pytorch_model (1).bin']

Searching /content for pytorch_model.bin...
Found: /content/pytorch_model.bin (409.8 MB)

In [26]:

import os
import shutil

model_path = "/content/electra-logic-structaware"
source = "/content/pytorch_model.bin"
destination = os.path.join(model_path, "pytorch_model.bin")

if os.path.exists(source):
    shutil.move(source, destination)
    print("Model file moved successfully.")
elif os.path.exists(destination):
    print("Model file is already in the correct location.")
else:
    print("Model file not found. Please check the upload.")

print("\nFiles in model folder:")
for filename in os.listdir(model_path):
    path = os.path.join(model_path, filename)
    print(filename, "-", round(os.path.getsize(path) / (1024 * 1024), 1), "MB")

Model file moved successfully.

Files in model folder:
config.json - 0.0 MB
pytorch_model (1).bin - 417.8 MB
pytorch_model.bin - 409.8 MB

In [27]:

import torch
from transformers import AutoModelForSequenceClassification

model_path = "/content/electra-logic-structaware"

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("Model loaded successfully!")
print("Device:", device)
print("Model vocabulary size:", model.config.vocab_size)
print("Number of output labels:", model.config.num_labels)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 3: invalid start byte

In [28]:

import os

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

print("File exists:", os.path.exists(weights_path))

if os.path.exists(weights_path):
    print("File size (MB):",
          round(os.path.getsize(weights_path) / (1024 * 1024), 2))

    with open(weights_path, "rb") as f:
        header = f.read(16)

    print("First 16 bytes:", header)
    print("Hexadecimal:", header.hex())

File exists: True
File size (MB): 409.76
First 16 bytes: b'cGR=\x8b\x1co=C\xc7\xee\xbc[\x12O<'
Hexadecimal: 6347523d8b1c6f3d43c7eebc5b124f3c

In [29]:

import torch
from transformers import AutoModelForSequenceClassification

model_path = "/content/electra-logic-structaware"

print("PyTorch version:", torch.__version__)

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3,
    weights_only=False
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("Model loaded successfully!")
print("Device:", device)
print("Labels:", model.config.num_labels)

PyTorch version: 2.11.0+cu130

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 3: invalid start byte

In [30]:

import os
import gzip

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

print("File exists:", os.path.exists(weights_path))

if os.path.exists(weights_path):
    size = os.path.getsize(weights_path)
    print("File size:", round(size / (1024 * 1024), 2), "MB")

    with open(weights_path, "rb") as f:
        header = f.read(32)

    print("First 32 bytes:", header)
    print("Hex:", header.hex())

    if header.startswith(b"PK"):
        print("Detected format: ZIP-based PyTorch checkpoint")
    elif header.startswith(b"\x1f\x8b"):
        print("Detected format: GZIP-compressed file")
    else:
        print("Format not identified from header")

File exists: True
File size: 409.76 MB
First 32 bytes: b'cGR=\x8b\x1co=C\xc7\xee\xbc[\x12O<\xb5{\xd2<\x17}\xbf\xbb\xc0f\x7f\xbc\x10\xc0\x02\xbd'
Hex: 6347523d8b1c6f3d43c7eebc5b124f3cb57bd23c177dbfbbc0667fbc10c002bd
Format not identified from header

In [31]:

import os
import hashlib

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

print("File size:", round(os.path.getsize(weights_path) / (1024 * 1024), 2), "MB")

sha256 = hashlib.sha256()

with open(weights_path, "rb") as f:
    for chunk in iter(lambda: f.read(8 * 1024 * 1024), b""):
        sha256.update(chunk)

print("SHA-256:", sha256.hexdigest())

print("\nFirst 16 bytes in hexadecimal:")
with open(weights_path, "rb") as f:
    print(f.read(16).hex())

File size: 409.76 MB
SHA-256: 69f7ec716bd6e1915c6b575c422b22c14163b83ed0d9035afe1135e9750e975d

First 16 bytes in hexadecimal:
6347523d8b1c6f3d43c7eebc5b124f3c

In [90]:
import os

path = "/content/pytorch_model_original.bin"

print("File exists:", os.path.exists(path))

if os.path.exists(path):
    print("File size:", round(os.path.getsize(path) / (1024 * 1024), 2), "MB")

File exists: True
File size: 417.76 MB

In [91]:
import hashlib, os

path = "/content/pytorch_model_original.bin"

sha = hashlib.sha256()
with open(path, "rb") as f:
    for chunk in iter(lambda: f.read(8 * 1024 * 1024), b""):
        sha.update(chunk)

with open(path, "rb") as f:
    first_bytes = f.read(16).hex()

print("Size:", round(os.path.getsize(path) / (1024 * 1024), 2), "MB")
print("SHA-256:", sha.hexdigest())
print("First 16 bytes:", first_bytes)

Size: 417.76 MB
SHA-256: 7903a585dee9dd2ccecf99f6b7dbbeb3967dcef80ab13a564a24413a4aae30ca
First 16 bytes: 504b0304000008080000000000000000

In [92]:
import os
import shutil
from transformers import AutoModelForSequenceClassification

source = "/content/pytorch_model_original.bin"
folder = "/content/electra-logic-structaware"
destination = os.path.join(folder, "pytorch_model.bin")

shutil.copyfile(source, destination)
print("Checkpoint copied successfully.")

model = AutoModelForSequenceClassification.from_pretrained(
    folder,
    num_labels=3
)

print("SUCCESS: Model loaded!")
print("Model type:", type(model).__name__)
print("Number of labels:", model.config.num_labels)

Checkpoint copied successfully.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

SUCCESS: Model loaded!
Model type: ElectraForSequenceClassification
Number of labels: 3

In [93]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator"
)

special_tokens = [f"[{letter}]" for letter in "ABCDEFGHI"]
tokenizer.add_special_tokens(
    {"additional_special_tokens": special_tokens}
)

print("Tokenizer loaded successfully")
print("Vocabulary size:", len(tokenizer))
print("Special tokens:", special_tokens)
print("Model vocabulary size:", model.config.vocab_size)
print("Embedding vocabulary size:", model.get_input_embeddings().weight.shape[0])

Tokenizer loaded successfully
Vocabulary size: 30531
Special tokens: ['[A]', '[B]', '[C]', '[D]', '[E]', '[F]', '[G]', '[H]', '[I]']
Model vocabulary size: 30531
Embedding vocabulary size: 30531

In [94]:
path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for start, end in [(40, 100), (100, 180), (180, 260)]:
    print(f"\n{'='*20} Lines {start}-{end} {'='*20}")
    for i in range(start - 1, min(end, len(lines))):
        print(f"{i+1}: {lines[i]}", end="")

==================== Lines 40-100 ====================
40:                     labels_dict[lbl] = 0
41:                 labels_dict[lbl] += 1
42:     return list(labels_dict.keys()), labels_dict
43:
44:
45: def replace_random_sample(i):
46:     return sample(word_bank, 1)[0]
47:
48:
49: class MNLIDataset:
50:
51:     def __init__(self, tokenizer_path, train_df, val_df, label_col_name, map='base', test_df=None, fallacy=False,
52:                  undersample_train=False, undersample_val=False, undersample_test=False, undersample_rate=0.04,
53:                  train_strat=1, test_strat=1, multilabel=False):
54:         # strat is used in convert_to_mnli function
55:         self.label_dict = {'entailment': 0, 'contradiction': 1, 'neutral': 2}
56:         torch.manual_seed(0)
57:         self.train_df = train_df
58:         self.val_df = val_df
59:         self.test_df = test_df
60:         self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, do_lower_case=True)
61:         special_tokens_dict = {
62:             'additional_special_tokens': ["[A]", "[B]", "[C]", "[D]", "[E]", "[F]", "[G]", "[H]", "[I]"]}
63:         self.tokenizer.add_special_tokens(special_tokens_dict)
64:         self.train_data = None
65:         self.val_data = None
66:         self.label_col_name = label_col_name
67:         self.map = map
68:         self.mappings = pd.read_csv("../../data/mappings.csv")
69:         self.multilabel = multilabel
70:         if fallacy:
71:             self.unique_labels, self.counts_dict = get_unique_labels(pd.concat([train_df, val_df, test_df]),
72:                                                                      self.label_col_name,
73:                                                                      multilabel)
74:             self.total_count = 0
75:             for count in self.counts_dict.values():
76:                 self.total_count += count
77:         self.init_data(fallacy, undersample_train, undersample_val, undersample_test,
78:                        undersample_ratio=undersample_rate, train_strat=train_strat, test_strat=test_strat)
79:
80:     def convert_to_mnli(self, df, undersample=False, undersampling_rate=0.02, strat=1):
81:         """
82:         strat=1 -> only original article
83:         strat=2 -> only masked article
84:         strat=3 -> both
85:         """
86:         data = []
87:         for i, row in df.iterrows():
88:             for label in self.unique_labels:
89:                 entry = [row['source_article']]
90:                 if self.map == 'base':
91:                     entry.append("This is an example of %s logical fallacy" % label)
92:                 elif self.map == 'simplify':
93:                     simplified_label = \
94:                         list(self.mappings[self.mappings['Original Name'] == label]['Understandable Name'])[0]
95:                     entry.append("This is an example of %s" % simplified_label)
96:                 elif self.map == 'description':
97:                     description = list(self.mappings[self.mappings['Original Name'] == label]['Description'])[0]
98:                     entry.append("This is an example of %s" % description)
99:                 elif self.map == 'logical-form':
100:                     form = list(self.mappings[self.mappings['Original Name'] == label]['Logical Form'])[0]

==================== Lines 100-180 ====================
100:                     form = list(self.mappings[self.mappings['Original Name'] == label]['Logical Form'])[0]
101:                     entry.append("This article matches the following logical form: %s" % form)
102:                 elif self.map == 'masked-logical-form':
103:                     # print(self.mappings[self.mappings['Original Name'] == label]['Masked Logical Form'])
104:                     form = replace_masked_tokens(list(self.mappings[self.mappings['Original Name'] == label]
105:                                                       ['Masked Logical Form'])[0])
106:                     entry.append("This article matches the following logical form: %s" % form)
107:                 if (self.multilabel is False and label == row[self.label_col_name]) or (
108:                         self.multilabel is True and label in row[self.label_col_name]):
109:                     entry.append("entailment")
110:                 else:
111:                     p = random.random()
112:                     if undersample and p > undersampling_rate:
113:                         continue
114:                     entry.append("contradiction")
115:                 weight = (self.total_count / self.counts_dict[label]) / 10
116:                 if entry[-1] == "entailment":
117:                     weight *= 12
118:                 entry.append(weight)
119:                 # print(entry)
120:                 entry.append(label)
121:                 if strat % 2:
122:                     data.append(entry)
123:                 if strat > 1:
124:                     entry1 = [replace_masked_tokens(row['masked_articles']), entry[1], entry[2], entry[3]]
125:                     if entry1[0] != entry[0] or strat == 3:
126:                         data.append(entry1)
127:
128:         return pd.DataFrame(data, columns=['sentence1', 'sentence2', 'gold_label', 'weight','logical_fallacy'])
129:
130:     def init_data(self, fallacy, undersample_train=False, undersample_val=False, undersample_test=False,
131:                   undersample_ratio=0.02, train_strat=1, test_strat=1):
132:         if fallacy:
133:             self.train_df = self.convert_to_mnli(self.train_df, undersample=undersample_train,
134:                                                  undersampling_rate=undersample_ratio, strat=train_strat)
135:             self.val_df = self.convert_to_mnli(self.val_df, undersample=undersample_val,
136:                                                undersampling_rate=undersample_ratio, strat=test_strat)
137:             self.test_df = self.convert_to_mnli(self.test_df, undersample=undersample_test,
138:                                                 undersampling_rate=undersample_ratio, strat=test_strat)
139:         # print(self.counts_dict, self.total_count)
140:         # self.train_df.to_csv('results/temp.csv')
141:         self.train_data = self.load_data(self.train_df)
142:         self.val_data = self.load_data(self.val_df)
143:         self.test_data = self.load_data(self.test_df)
144:
145:     def load_data(self, df):
146:         if df is None:
147:             return None
148:
149:         MAX_LEN = 512
150:         token_ids = []
151:         mask_ids = []
152:         seg_ids = []
153:         y = []
154:         weights = []
155:
156:         df = df.dropna()
157:
158:         premise_list = df['sentence1'].to_list()
159:         hypothesis_list = df['sentence2'].to_list()
160:         label_list = df['gold_label'].to_list()
161:         weight_list = df['weight'].to_list()
162:
163:         for (premise, hypothesis, label, weight) in zip(premise_list, hypothesis_list, label_list, weight_list):
164:
165:             premise_id = self.tokenizer.encode(premise, add_special_tokens=False)
166:             hypothesis_id = self.tokenizer.encode(hypothesis, add_special_tokens=False)
167:             pair_token_ids = [self.tokenizer.cls_token_id] + premise_id + [
168:                 self.tokenizer.sep_token_id] + hypothesis_id + [self.tokenizer.sep_token_id]
169:             # pair_token_ids = premise_id + hypothesis_id
170:             # print("max token id=", max(pair_token_ids))
171:             premise_len = len(premise_id)
172:             hypothesis_len = len(hypothesis_id)
173:
174:             segment_ids = torch.tensor(
175:                 [0] * (premise_len + 2) + [1] * (hypothesis_len + 1))  # sentence 0 and sentence 1
176:             attention_mask_ids = torch.tensor([1] * (premise_len + hypothesis_len + 3))  # mask padded values
177:             if len(pair_token_ids) > MAX_LEN or len(segment_ids) > MAX_LEN or len(attention_mask_ids) > MAX_LEN:
178:                 continue
179:             token_ids.append(torch.tensor(pair_token_ids))
180:             seg_ids.append(segment_ids)

==================== Lines 180-260 ====================
180:             seg_ids.append(segment_ids)
181:             mask_ids.append(attention_mask_ids)
182:             y.append(self.label_dict[label])
183:             weights.append(weight)
184:
185:         token_ids = pad_sequence(token_ids, batch_first=True)
186:         mask_ids = pad_sequence(mask_ids, batch_first=True)
187:         seg_ids = pad_sequence(seg_ids, batch_first=True)
188:         y = torch.tensor(y)
189:         # print(token_ids.shape)
190:         # print(torch.tensor(weights).shape)
191:         dataset = TensorDataset(token_ids, mask_ids, seg_ids, y, torch.tensor(weights))
192:         # print(len(dataset))
193:         return dataset
194:
195:     def get_undersampled(self, ratio=0.04, batch_size=32, shuffle=True):
196:         train_df_entail = self.train_df[self.train_df.gold_label == 'entailment']
197:         train_df_contradict = self.train_df[self.train_df.gold_label == 'contradiction']
198:         train_df_contradict = train_df_contradict.sample(n=int(len(train_df_contradict) * ratio))
199:         df = pd.concat([train_df_contradict, train_df_entail])
200:         df = self.load_data(df)
201:         return DataLoader(
202:             df,
203:             shuffle=shuffle,
204:             batch_size=batch_size
205:         )
206:
207:     def get_data_loaders(self, batch_size=32, shuffle=True):
208:         train_loader = DataLoader(
209:             self.train_data,
210:             shuffle=shuffle,
211:             batch_size=batch_size
212:         )
213:
214:         val_loader = DataLoader(
215:             self.val_data,
216:             shuffle=shuffle,
217:             batch_size=batch_size
218:         )
219:         if self.test_data:
220:             test_loader = DataLoader(
221:                 self.test_data,
222:                 shuffle=False,
223:                 batch_size=len(self.unique_labels)
224:             )
225:         else:
226:             test_loader = None
227:
228:         return train_loader, val_loader, test_loader
229:
230:
231: def get_logger(level='DEBUG'):
232:     logger = logging.getLogger()
233:     logger.handlers = []
234:     file_log_handler = logging.FileHandler('logfile.log')
235:     logger.addHandler(file_log_handler)
236:     stderr_log_handler = logging.StreamHandler()
237:     logger.addHandler(stderr_log_handler)
238:     logger.setLevel(level)
239:     return logger
240:
241:
242: def multi_acc(y_pred, y_test, flip=True):
243:     preds = torch.log_softmax(y_pred, dim=1).argmax(dim=1)
244:     acc = (preds == y_test).sum().float() / float(y_test.size(0))
245:     if flip:
246:         y_pred = 1 - preds.cpu()
247:         y_test = 1 - y_test.cpu()
248:     else:
249:         y_pred = preds.cpu()
250:         y_test = y_test.cpu()
251:     TP = 0
252:     FP = 0
253:     TN = 0
254:     FN = 0
255:     for i in range(len(y_pred)):
256:         if y_test[i] == y_pred[i] == 1:
257:             TP += 1
258:         if y_pred[i] == 1 and y_test[i] != y_pred[i]:
259:             FP += 1
260:         if y_test[i] == y_pred[i] == 0:

In [95]:
print("Training labels:")
print(sorted(train_df["updated_label"].unique()))

print("\nNumber of unique labels:",
      train_df["updated_label"].nunique())

print("\nSample training row:")
print(train_df[["source_article", "updated_label", "masked_articles"]].iloc[0].to_dict())

Training labels:
['ad hominem', 'ad populum', 'appeal to emotion', 'circular reasoning', 'equivocation', 'fallacy of credibility', 'fallacy of extension', 'fallacy of logic', 'fallacy of relevance', 'false causality', 'false dilemma', 'faulty generalization', 'intentional']

Number of unique labels: 13

Sample training row:
{'source_article': 'company\'s slogan "Expect More. Pay Less."', 'updated_label': 'appeal to emotion', 'masked_articles': 'company \'s slogan " Expect More . Pay Less . " '}

In [96]:
import pandas as pd

mapping_path = "/content/logical-fallacy/data/mappings.csv"
mappings_df = pd.read_csv(mapping_path)

print("Mapping columns:")
print(mappings_df.columns.tolist())

print("\nMapping file preview:")
display(mappings_df.head(15))

Mapping columns:
['Original Name', 'Understandable Name', 'Description', 'Logical Form', 'Source for Logical Form ', 'Masked Logical Form']

Mapping file preview:

,Original Name,Understandable Name,Description,Logical Form,Source for Logical Form,Masked Logical Form
0,faulty generalization,faulty generalization,an informal fallacy wherein a conclusion is dr...,Sample S is taken from population P. Sample S ...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is taken from <MSK2>. <MSK1> is a very ...
1,false causality,false causality,statement that jumps to a conclusion implying ...,"A occurred, then B occurred.\nTherefore, A cau...",https://en.wikipedia.org/wiki/Post_hoc_ergo_pr...,"<MSK1> occurred, then <MSK2> occurred.\nTheref..."
2,circular reasoning,circular reasoning,when the end of an argument comes back to the ...,X is true because of Y.\n\nY is true because o...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is true because of <MSK2>.\n\n<MSK2> is...
3,ad populum,appeal to popularity,a fallacious argument which is based on affirm...,"A lot of people believe X.Therefore, X must be...",https://www.logicallyfallacious.com/logicalfal...,"A lot of people believe <MSK1>.Therefore, <MSK..."
4,ad hominem,personal attack,instead of addressing someone's argument or p...,Person 1 is claiming Y.\n\nPerson 1 is a moron...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is claiming <MSK2>.\n\n<MSK1> is a moro...
5,fallacy of logic,logical error,an error in the logical structure of an argument.,"If A is true, then B is true. B is true. There...",https://en.wikipedia.org/wiki/Formal_fallacy,"If <MSK1> is true, then <MSK2> is true.<MSK2> ..."
6,appeal to emotion,appeal to emotion,manipulation of the recipient's emotions in or...,Claim X is made without evidence. In place of ...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is made without evidence. In place of e...
7,false dilemma,excluding viable alternatives,presenting only two options or sides when ther...,Either X or Y is true.,https://www.logicallyfallacious.com/logicalfal...,Either <MSK1> or <MSK2> is true.
8,equivocation,use of ambiguous language,when a key term or phrase in an argument is us...,Term X is used to mean Y in the premise.\nTerm...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is used to mean <MSK2> in the premise.\...
9,fallacy of extension,exaggerating,attacking an exaggerated or caricatured versio...,Person 1 makes claim Y. Person 2 restates pers...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> makes claim <MSK2>. <MSK3> restates <MS...
10,fallacy of relevance,irrelevant argument,introducing premises or conclusions that have ...,"It is claimed that X implies Y, whereas X is u...",Self,"It is claimed that <MSK1> implies <MSK2>, wher..."
11,fallacy of credibility,attacking the character of the speaker,attempts to disprove an argument by attacking ...,Person 1 makes claim Y. Person 2 claims Person...,Self,<MSK1> makes <MSK2>. <MSK3> claims <MSK1> is n...
12,miscellaneous,miscellaneous,miscellaneous,miscellaneous,NaN,miscellaneous
13,intentional,intentionally wrong argument,some intentional (sometimes subconscious) acti...,Person 1 knows claim X is incorrect. They stil...,NaN,<MSK1> knows <MSK2> is incorrect. They still c...

In [97]:
print("Model label configuration:")
print(model.config.id2label)

print("\nLabel to ID mapping:")
print(model.config.label2id)

print("\nNumber of output classes:")
print(model.config.num_labels)

Model label configuration:
{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}

Label to ID mapping:
{'LABEL_0': 0, 'LABEL_1': 1, 'LABEL_2': 2}

Number of output classes:
3

In [98]:
import torch

premise = "Everyone is buying this product, so it must be the best."
hypothesis = "This is an example of ad populum logical fallacy"

inputs = tokenizer(
    premise,
    hypothesis,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
inputs = {k: v.to(device) for k, v in inputs.items()}

model.eval()
with torch.no_grad():
    outputs = model(**inputs)
    probabilities = torch.softmax(outputs.logits, dim=-1)[0]

labels = ["Entailment", "Contradiction", "Neutral"]

print("Device:", device)
for label, score in zip(labels, probabilities.tolist()):
    print(f"{label}: {score:.4f}")

Device: cuda
Entailment: 0.0356
Contradiction: 0.9639
Neutral: 0.0006

In [99]:
import torch
import pandas as pd

argument = "Everyone is buying this product, so it must be the best."

categories = sorted(train_df["updated_label"].unique())
results = []

model.eval()

for category in categories:
    hypothesis = f"This is an example of {category} logical fallacy"

    inputs = tokenizer(
        argument,
        hypothesis,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        logits = model(**inputs).logits
        probs = torch.softmax(logits, dim=-1)[0].cpu().tolist()

    results.append({
        "Fallacy": category,
        "Entailment": round(probs[0], 4),
        "Contradiction": round(probs[1], 4),
        "Neutral": round(probs[2], 4)
    })

results_df = pd.DataFrame(results)
display(results_df.sort_values("Entailment", ascending=False))

                   Fallacy  Entailment  Contradiction  Neutral
12             intentional      0.0405         0.9583   0.0013
3       circular reasoning      0.0374         0.9617   0.0009
11   faulty generalization      0.0369         0.9626   0.0005
1               ad populum      0.0356         0.9639   0.0006
5   fallacy of credibility      0.0343         0.9650   0.0007
6     fallacy of extension      0.0343         0.9651   0.0006
7         fallacy of logic      0.0341         0.9651   0.0008
8     fallacy of relevance      0.0330         0.9664   0.0006
9          false causality      0.0324         0.9670   0.0006
0               ad hominem      0.0301         0.9692   0.0007
10           false dilemma      0.0296         0.9693   0.0011
4             equivocation      0.0282         0.9710   0.0009
2        appeal to emotion      0.0229         0.9764   0.0008

In [100]:
import json

config_path = "/content/electra-logic-structaware/config.json"

with open(config_path, "r") as f:
    config = json.load(f)

print("Model type:", config.get("model_type"))
print("Architecture:", config.get("architectures"))
print("Vocabulary size:", config.get("vocab_size"))
print("Special token IDs:")
print("PAD:", config.get("pad_token_id"))
print("CLS:", config.get("cls_token_id"))
print("SEP:", config.get("sep_token_id"))

print("\nTokenizer source currently used:")
print("google/electra-base-discriminator")

Model type: electra
Architecture: ['ElectraForSequenceClassification']
Vocabulary size: 30531
Special token IDs:
PAD: 0
CLS: None
SEP: None

Tokenizer source currently used:
google/electra-base-discriminator

In [101]:
print("CLS token:", tokenizer.cls_token)
print("CLS token ID:", tokenizer.cls_token_id)

print("SEP token:", tokenizer.sep_token)
print("SEP token ID:", tokenizer.sep_token_id)

print("PAD token:", tokenizer.pad_token)
print("PAD token ID:", tokenizer.pad_token_id)

print("\nSpecial fallacy tokens:")
for token in ["[A]", "[B]", "[C]", "[D]", "[E]", "[F]", "[G]", "[H]", "[I]"]:
    print(token, "->", tokenizer.convert_tokens_to_ids(token))

CLS token: [CLS]
CLS token ID: 101
SEP token: [SEP]
SEP token ID: 102
PAD token: [PAD]
PAD token ID: 0

Special fallacy tokens:
[A] -> 30522
[B] -> 30523
[C] -> 30524
[D] -> 30525
[E] -> 30526
[F] -> 30527
[G] -> 30528
[H] -> 30529
[I] -> 30530

In [102]:
path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for i in range(450, min(520, len(lines))):
    print(f"{i+1}: {lines[i]}", end="")

451:     parser.add_argument("-c", "--classwise_savepath", help="Path to store classwise results")
452:     parser.add_argument("-sr", "--result_path", help="Path to store results on dev set")
453:     parser.add_argument("-nt", "--do_not_train", help="Set this to T if you do not wish to train the model",
454:                         default='F')
455:     args = parser.parse_args()
456:     # word_bank = pickle.load('../../data/word_bank.pkl')
457:     logger.info(args)
458:     logger.info("initializing model")
459:     model = AutoModelForSequenceClassification.from_pretrained(args.model, num_labels=3)
460:     model.to(device)
461:
462:     if args.finetune == 'T':
463:         logger.info("initializing mnli dataset")
464:         mnli_train = pd.read_csv(args.multinli_path + "/multinli_1.0_train.txt", sep='\t',
465:                                  skiprows=[24809, 33960, 75910, 100113, 150637, 158833, 173103, 178251, 221950, 286844,
466:                                            314109])[['gold_label', 'sentence1', 'sentence2']]
467:         mnli_train = mnli_train.dropna()
468:         mnli_dev_matched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_matched.txt", sep='\t')[
469:             ['gold_label', 'sentence1', 'sentence2']]
470:         mnli_dev_mismatched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_mismatched.txt", sep='\t')[
471:             ['gold_label', 'sentence1', 'sentence2']]
472:         mnli_dev = pd.concat([mnli_dev_matched, mnli_dev_mismatched], ignore_index=True, sort=False)
473:         mnli_dev = mnli_dev.dropna()
474:         mnli_dev = mnli_dev[mnli_dev.gold_label != '-']
475:         mnli_ds = MNLIDataset(args.tokenizer, mnli_train, mnli_dev, 'gold_label', fallacy=False)
476:         logger.info("finetune on mnli")
477:         optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
478:         train(model, mnli_ds, optimizer, logger, args.savepath2, ratio=1, epochs=10, positive_weight=1)
479:         logger.info("reinit model")
480:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath2)
481:         model.to(device)
482:     optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
483:     logger.info("creating dataset")
484:     fallacy_train = pd.read_csv('../../data/edu_train.csv')
485:     if args.downsample == 'T':
486:         fallacy_train = fallacy_train[:747]
487:     fallacy_dev = pd.read_csv('../../data/edu_dev.csv')
488:     fallacy_test = pd.read_csv('../../data/edu_test.csv')
489:     fallacy_ds = MNLIDataset(args.tokenizer, fallacy_train, fallacy_dev, 'updated_label', args.map, fallacy_test,
490:                              fallacy=True, train_strat=int(args.train_strat), test_strat=int(args.dev_strat))
491:     model.resize_token_embeddings(len(fallacy_ds.tokenizer))
492:     fallacy_ds.train_df.to_csv('processed_train_df.csv')
493:     fallacy_ds.val_df.to_csv('processed_val_df.csv')
494:     # print(fallacy_ds.tokenizer.tokenize("[A] causes [B]"))
495:     # print("checking length", len(fallacy_ds.tokenizer), model.config.vocab_size)
496:     if args.do_not_train == 'F':
497:         optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
498:         logger.info("starting training")
499:         train(model, fallacy_ds, optimizer, logger, args.savepath, device, ratio=1, epochs=10,
500:               positive_weight=int(args.weight))
501:
502:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath, num_labels=3)
503:         model.to(device)
504:     logger.info("starting testing")
505:     _, _, test_loader = fallacy_ds.get_data_loaders()
506:     scores = eval1(model, test_loader, logger, device)
507:     logger.info("micro f1: %f macro f1:%f precision: %f recall: %f exact match %f", scores[4], scores[5], scores[1],
508:                 scores[2], scores[3])
509:     if args.classwise_savepath is not None:
510:         classwise_scores = eval_classwise(model, test_loader, logger, fallacy_ds.unique_labels, device)
511:         df = pd.DataFrame.from_records(classwise_scores, columns=['Fallacy Name', 'Precision', 'Recall', 'F1',
512:                                                                   'Number of Positive Labels for this Class in Test Set'
513:                                                                   ])
514:         df.to_csv(args.classwise_savepath)
515:     if args.result_path is not None:
516:         logger.info("Generating results on Dev Set")
517:         df = eval_and_store(fallacy_ds, model, logger, device, args.map)
518:         df = convert_to_multilabel(df)
519:         df.to_csv(args.result_path)

In [103]:
path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Original evaluation and prediction logic
for start, end in [(260, 360), (360, 450)]:
    print(f"\n{'='*15} Lines {start}-{end} {'='*15}")
    for i in range(start - 1, min(end, len(lines))):
        print(f"{i+1}: {lines[i]}", end="")

=============== Lines 260-360 ===============
260:         if y_test[i] == y_pred[i] == 0:
261:             TN += 1
262:         if y_pred[i] == 0 and y_test[i] != y_pred[i]:
263:             FN += 1
264:     if TP == 0:
265:         return acc, 0, 0
266:     precision = TP / (TP + FP)
267:     recall = TP / (TP + FN)
268:     return acc, precision, recall
269:
270:
271: import time
272:
273:
274: def get_metrics(logits, labels, threshold=0.5, sig=True, tensors=True):
275:     if sig:
276:         sig = nn.Sigmoid()
277:         preds = sig(logits)
278:         preds = (preds > threshold)
279:     else:
280:         preds = logits
281:     # print(preds.cpu().int(),labels.cpu().int())
282:     if tensors:
283:         y_true = labels.cpu().int()
284:         y_pred = preds.cpu().int()
285:     else:
286:         y_true = np.array(labels)
287:         y_pred = np.array(preds)
288:     temp = 0
289:     for i in range(y_true.shape[0]):
290:         temp += sum(np.logical_and(y_true[i], y_pred[i])) / sum(np.logical_or(y_true[i], y_pred[i]))
291:     accuracy = temp / y_true.shape[0]
292:     precision = sklearn.metrics.precision_score(y_true=y_true, y_pred=y_pred, average='samples', zero_division=0)
293:     recall = sklearn.metrics.recall_score(y_true=y_true, y_pred=y_pred, average='samples', zero_division=0)
294:     exact_match = sklearn.metrics.accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)
295:     micro_f1_score = sklearn.metrics.f1_score(y_true, y_pred, average='micro', zero_division=0)
296:     macro_f1_score = sklearn.metrics.f1_score(y_true, y_pred, average='macro', zero_division=0)
297:     return accuracy, precision, recall, exact_match, micro_f1_score, macro_f1_score
298:
299:
300: def train(model, dataset, optimizer, logger, save_path, device, epochs=5, ratio=0.04, positive_weight=12, debug=False):
301:     train_loader, val_loader, _ = dataset.get_data_loaders()
302:     min_val_loss = float('inf')
303:     loss_fn = nn.CrossEntropyLoss(reduction='none')
304:     loss_fn.to(device)
305:     for epoch in range(epochs):
306:         start = time.time()
307:         model.train()
308:         total_train_loss = 0
309:         total_train_acc = 0
310:         total_train_prec = 0
311:         total_train_rec = 0
312:         if ratio < 1:
313:             train_loader = dataset.get_undersampled(ratio)
314:         for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(train_loader):
315:             # print(weights.shape)
316:             if batch_idx % 10 == 0:
317:                 logger.debug('%d %d', epoch, batch_idx)
318:             optimizer.zero_grad()
319:             pair_token_ids = pair_token_ids.to(device)
320:             mask_ids = mask_ids.to(device)
321:             seg_ids = seg_ids.to(device)
322:             labels = y.to(device)
323:             weights = weights.to(device)
324:             if debug:
325:                 print(pair_token_ids.shape, seg_ids.shape, mask_ids.shape)
326:                 break
327:             _, prediction = model(pair_token_ids,
328:                                   token_type_ids=seg_ids,
329:                                   attention_mask=mask_ids,
330:                                   labels=labels).values()
331:             # print(weights.shape)
332:             loss = loss_fn(prediction, labels)
333:             # print(loss.shape)
334:             len1 = loss.shape[0]
335:             loss = torch.dot(loss, weights) / len1
336:             # print('forward prop done')
337:             acc, prec, rec = multi_acc(prediction, labels)
338:             # print(acc,prec,rec)
339:             loss.backward()
340:             optimizer.step()
341:
342:             total_train_loss += loss.item()
343:             total_train_acc += acc.float()
344:             total_train_prec += prec
345:             total_train_rec += rec
346:         if debug:
347:             break
348:         train_acc = total_train_acc / len(train_loader)
349:         train_loss = total_train_loss / len(train_loader)
350:         train_prec = total_train_prec / len(train_loader)
351:         train_rec = total_train_rec / len(train_loader)
352:         model.eval()
353:         total_val_acc = 0
354:         total_val_loss = 0
355:         total_val_prec = 0
356:         total_val_rec = 0
357:
358:         with torch.no_grad():
359:             for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(val_loader):
360:                 pair_token_ids = pair_token_ids.to(device)

=============== Lines 360-450 ===============
360:                 pair_token_ids = pair_token_ids.to(device)
361:                 mask_ids = mask_ids.to(device)
362:                 seg_ids = seg_ids.to(device)
363:                 labels = y.to(device)
364:                 weights = weights.to(device)
365:                 _, prediction = model(pair_token_ids,
366:                                       token_type_ids=seg_ids,
367:                                       attention_mask=mask_ids,
368:                                       labels=labels).values()
369:                 loss = loss_fn(prediction, labels)
370:                 len1 = loss.shape[0]
371:                 loss = torch.dot(loss, weights) / len1
372:                 acc, prec, rec = multi_acc(prediction, labels)
373:
374:                 total_val_loss += loss.item()
375:                 total_val_acc += acc.float()
376:                 total_val_prec += prec
377:                 total_val_rec += rec
378:
379:         val_acc = total_val_acc / len(val_loader)
380:         val_loss = total_val_loss / len(val_loader)
381:         val_rec = total_val_rec / len(val_loader)
382:         val_prec = total_val_prec / len(val_loader)
383:         flag = True
384:         if val_loss < min_val_loss:
385:             min_val_loss = val_loss
386:             logger.info("saving model")
387:             model.save_pretrained(save_path)
388:         else:
389:             flag = False
390:         end = time.time()
391:         hours, rem = divmod(end - start, 3600)
392:         minutes, seconds = divmod(rem, 60)
393:
394:         logger.info(
395:             f'Epoch {epoch + 1}: train_loss: {train_loss:.4f} train_acc: {train_acc:.4f} train_prec: {train_prec:.4f} '
396:             f'train_rec: {train_rec:.4f}| val_loss: {val_loss:.4f} val_acc: {val_acc:.4f} val_prec: {val_prec:.4f} '
397:             f'val_rec: {val_rec:.4f}'
398:         )
399:         logger.info("{:0>2}:{:0>2}:{:05.2f}".format(int(hours), int(minutes), seconds))
400:         if not flag:
401:             break
402:
403:
404: def eval1(model, test_loader, logger, device):
405:     with torch.no_grad():
406:         all_preds = []
407:         all_labels = []
408:         for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(test_loader):
409:             logger.debug("%d", batch_idx)
410:             pair_token_ids = pair_token_ids.to(device)
411:             mask_ids = mask_ids.to(device)
412:             seg_ids = seg_ids.to(device)
413:             labels = y.to(device)
414:             if model == "random":
415:                 prediction = torch.rand([15, 3])
416:             else:
417:                 _, prediction = model(pair_token_ids,
418:                                       token_type_ids=seg_ids,
419:                                       attention_mask=mask_ids,
420:                                       labels=labels).values()
421:             all_preds.append(torch.log_softmax(prediction, dim=1).argmax(dim=1))
422:             all_labels.append(labels)
423:         all_preds = 1 - torch.stack(all_preds)
424:         all_labels = 1 - torch.stack(all_labels)
425:         all_preds[all_preds < 0] = 0
426:         all_labels[all_labels < 0] = 0
427:         return get_metrics(all_preds, all_labels, sig=False)
428:
429:
430: if __name__ == "__main__":
431:     if torch.cuda.is_available():
432:         device = "cuda"
433:     else:
434:         device = "cpu"
435:     logger = get_logger()
436:     logger.info("device = %s", device)
437:     parser = argparse.ArgumentParser()
438:     parser.add_argument("-t", "--tokenizer", help="tokenizer path")
439:     parser.add_argument("-m", "--model", help="model path")
440:     parser.add_argument("-w", "--weight", help="Weight of entailment loss")
441:     parser.add_argument("-s", "--savepath", help="Path to save logicedu model")
442:     parser.add_argument("-f", "--finetune", help="Set this flag if you want to finetune the model on MNLI", default='F')
443:     parser.add_argument("-sf", "--savepath2", help="Path to save mnli model", default="mnli")
444:     parser.add_argument("-mp", "--map", help="Map labels to this category")
445:     parser.add_argument("-ts", "--train_strat", help="Strategy number for training")
446:     parser.add_argument("-ds", "--dev_strat", help="Strategy number for development and testing")
447:     parser.add_argument("-rs", "--replace_strat", help="Function used to replace masked words", default='char')
448:     parser.add_argument("-rc", "--replace_count", help="Number of times to replace masked words", default=1)
449:     parser.add_argument("-np", "--multinli_path", help="Path for multinli directory", default="")
450:     parser.add_argument("-do", "--downsample", help="Downsample Training Set", default='F')

In [104]:
path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for i in range(0, min(45, len(lines))):
    print(f"{i+1}: {lines[i]}", end="")

print("\n--- Remaining command-line options ---")
for i in range(430, min(455, len(lines))):
    print(f"{i+1}: {lines[i]}", end="")

1: import pickle
2: import cv2
3: import torch
4: from torch.utils.data import TensorDataset, DataLoader
5: from torch.nn.utils.rnn import pad_sequence
6: from transformers import AutoTokenizer, AdamW, AutoModelForSequenceClassification
7: import pandas as pd
8: import random
9: from torch import nn
10: import sklearn
11: import numpy as np
12: import sklearn.metrics
13: import logging
14: import argparse
15: from random import sample
16: from library import eval_classwise, eval_and_store, convert_to_multilabel, get_corefs, replace_masked_tokens, \
17:     replace_char
18: from weighted_cross_entropy import CrossEntropyLoss
19:
20: torch.manual_seed(0)
21:
22:
23: def get_unique_labels(df, label_col_name, multilabel=False):
24:     labels_dict = {}
25:     if multilabel:
26:         for labels in df[label_col_name]:
27:             for label in labels:
28:                 if label not in labels_dict.keys():
29:                     labels_dict[label] = 0
30:                 labels_dict[label] += 1
31:     else:
32:         candidate_labels = df[label_col_name].unique()
33:         for label in candidate_labels:
34:             labels = label.split(';')
35:             if len(labels) > 1:
36:                 print(labels)
37:             labels = [x.strip() for x in labels]
38:             for lbl in labels:
39:                 if lbl not in labels_dict.keys():
40:                     labels_dict[lbl] = 0
41:                 labels_dict[lbl] += 1
42:     return list(labels_dict.keys()), labels_dict
43:
44:
45: def replace_random_sample(i):

--- Remaining command-line options ---
431:     if torch.cuda.is_available():
432:         device = "cuda"
433:     else:
434:         device = "cpu"
435:     logger = get_logger()
436:     logger.info("device = %s", device)
437:     parser = argparse.ArgumentParser()
438:     parser.add_argument("-t", "--tokenizer", help="tokenizer path")
439:     parser.add_argument("-m", "--model", help="model path")
440:     parser.add_argument("-w", "--weight", help="Weight of entailment loss")
441:     parser.add_argument("-s", "--savepath", help="Path to save logicedu model")
442:     parser.add_argument("-f", "--finetune", help="Set this flag if you want to finetune the model on MNLI", default='F')
443:     parser.add_argument("-sf", "--savepath2", help="Path to save mnli model", default="mnli")
444:     parser.add_argument("-mp", "--map", help="Map labels to this category")
445:     parser.add_argument("-ts", "--train_strat", help="Strategy number for training")
446:     parser.add_argument("-ds", "--dev_strat", help="Strategy number for development and testing")
447:     parser.add_argument("-rs", "--replace_strat", help="Function used to replace masked words", default='char')
448:     parser.add_argument("-rc", "--replace_count", help="Number of times to replace masked words", default=1)
449:     parser.add_argument("-np", "--multinli_path", help="Path for multinli directory", default="")
450:     parser.add_argument("-do", "--downsample", help="Downsample Training Set", default='F')
451:     parser.add_argument("-c", "--classwise_savepath", help="Path to store classwise results")
452:     parser.add_argument("-sr", "--result_path", help="Path to store results on dev set")
453:     parser.add_argument("-nt", "--do_not_train", help="Set this to T if you do not wish to train the model",
454:                         default='F')
455:     args = parser.parse_args()

In [105]:

path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Display the main function and its argument defaults
for i in range(454, min(520, len(lines))):
    print(f"{i+1}: {lines[i]}", end="")

455:     args = parser.parse_args()
456:     # word_bank = pickle.load('../../data/word_bank.pkl')
457:     logger.info(args)
458:     logger.info("initializing model")
459:     model = AutoModelForSequenceClassification.from_pretrained(args.model, num_labels=3)
460:     model.to(device)
461:
462:     if args.finetune == 'T':
463:         logger.info("initializing mnli dataset")
464:         mnli_train = pd.read_csv(args.multinli_path + "/multinli_1.0_train.txt", sep='\t',
465:                                  skiprows=[24809, 33960, 75910, 100113, 150637, 158833, 173103, 178251, 221950, 286844,
466:                                            314109])[['gold_label', 'sentence1', 'sentence2']]
467:         mnli_train = mnli_train.dropna()
468:         mnli_dev_matched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_matched.txt", sep='\t')[
469:             ['gold_label', 'sentence1', 'sentence2']]
470:         mnli_dev_mismatched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_mismatched.txt", sep='\t')[
471:             ['gold_label', 'sentence1', 'sentence2']]
472:         mnli_dev = pd.concat([mnli_dev_matched, mnli_dev_mismatched], ignore_index=True, sort=False)
473:         mnli_dev = mnli_dev.dropna()
474:         mnli_dev = mnli_dev[mnli_dev.gold_label != '-']
475:         mnli_ds = MNLIDataset(args.tokenizer, mnli_train, mnli_dev, 'gold_label', fallacy=False)
476:         logger.info("finetune on mnli")
477:         optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
478:         train(model, mnli_ds, optimizer, logger, args.savepath2, ratio=1, epochs=10, positive_weight=1)
479:         logger.info("reinit model")
480:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath2)
481:         model.to(device)
482:     optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
483:     logger.info("creating dataset")
484:     fallacy_train = pd.read_csv('../../data/edu_train.csv')
485:     if args.downsample == 'T':
486:         fallacy_train = fallacy_train[:747]
487:     fallacy_dev = pd.read_csv('../../data/edu_dev.csv')
488:     fallacy_test = pd.read_csv('../../data/edu_test.csv')
489:     fallacy_ds = MNLIDataset(args.tokenizer, fallacy_train, fallacy_dev, 'updated_label', args.map, fallacy_test,
490:                              fallacy=True, train_strat=int(args.train_strat), test_strat=int(args.dev_strat))
491:     model.resize_token_embeddings(len(fallacy_ds.tokenizer))
492:     fallacy_ds.train_df.to_csv('processed_train_df.csv')
493:     fallacy_ds.val_df.to_csv('processed_val_df.csv')
494:     # print(fallacy_ds.tokenizer.tokenize("[A] causes [B]"))
495:     # print("checking length", len(fallacy_ds.tokenizer), model.config.vocab_size)
496:     if args.do_not_train == 'F':
497:         optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
498:         logger.info("starting training")
499:         train(model, fallacy_ds, optimizer, logger, args.savepath, device, ratio=1, epochs=10,
500:               positive_weight=int(args.weight))
501:
502:         model = AutoModelForSequenceClassification.from_pretrained(args.savepath, num_labels=3)
503:         model.to(device)
504:     logger.info("starting testing")
505:     _, _, test_loader = fallacy_ds.get_data_loaders()
506:     scores = eval1(model, test_loader, logger, device)
507:     logger.info("micro f1: %f macro f1:%f precision: %f recall: %f exact match %f", scores[4], scores[5], scores[1],
508:                 scores[2], scores[3])
509:     if args.classwise_savepath is not None:
510:         classwise_scores = eval_classwise(model, test_loader, logger, fallacy_ds.unique_labels, device)
511:         df = pd.DataFrame.from_records(classwise_scores, columns=['Fallacy Name', 'Precision', 'Recall', 'F1',
512:                                                                   'Number of Positive Labels for this Class in Test Set'
513:                                                                   ])
514:         df.to_csv(args.classwise_savepath)
515:     if args.result_path is not None:
516:         logger.info("Generating results on Dev Set")
517:         df = eval_and_store(fallacy_ds, model, logger, device, args.map)
518:         df = convert_to_multilabel(df)
519:         df.to_csv(args.result_path)

In [106]:

path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Display the dataset construction and label-mapping logic
for start, end in [(45, 180), (180, 260)]:
    print(f"\n{'='*20} Lines {start+1}-{end} {'='*20}")
    for i in range(start, min(end, len(lines))):
        print(f"{i+1}: {lines[i]}", end="")

==================== Lines 46-180 ====================
46:     return sample(word_bank, 1)[0]
47:
48:
49: class MNLIDataset:
50:
51:     def __init__(self, tokenizer_path, train_df, val_df, label_col_name, map='base', test_df=None, fallacy=False,
52:                  undersample_train=False, undersample_val=False, undersample_test=False, undersample_rate=0.04,
53:                  train_strat=1, test_strat=1, multilabel=False):
54:         # strat is used in convert_to_mnli function
55:         self.label_dict = {'entailment': 0, 'contradiction': 1, 'neutral': 2}
56:         torch.manual_seed(0)
57:         self.train_df = train_df
58:         self.val_df = val_df
59:         self.test_df = test_df
60:         self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, do_lower_case=True)
61:         special_tokens_dict = {
62:             'additional_special_tokens': ["[A]", "[B]", "[C]", "[D]", "[E]", "[F]", "[G]", "[H]", "[I]"]}
63:         self.tokenizer.add_special_tokens(special_tokens_dict)
64:         self.train_data = None
65:         self.val_data = None
66:         self.label_col_name = label_col_name
67:         self.map = map
68:         self.mappings = pd.read_csv("../../data/mappings.csv")
69:         self.multilabel = multilabel
70:         if fallacy:
71:             self.unique_labels, self.counts_dict = get_unique_labels(pd.concat([train_df, val_df, test_df]),
72:                                                                      self.label_col_name,
73:                                                                      multilabel)
74:             self.total_count = 0
75:             for count in self.counts_dict.values():
76:                 self.total_count += count
77:         self.init_data(fallacy, undersample_train, undersample_val, undersample_test,
78:                        undersample_ratio=undersample_rate, train_strat=train_strat, test_strat=test_strat)
79:
80:     def convert_to_mnli(self, df, undersample=False, undersampling_rate=0.02, strat=1):
81:         """
82:         strat=1 -> only original article
83:         strat=2 -> only masked article
84:         strat=3 -> both
85:         """
86:         data = []
87:         for i, row in df.iterrows():
88:             for label in self.unique_labels:
89:                 entry = [row['source_article']]
90:                 if self.map == 'base':
91:                     entry.append("This is an example of %s logical fallacy" % label)
92:                 elif self.map == 'simplify':
93:                     simplified_label = \
94:                         list(self.mappings[self.mappings['Original Name'] == label]['Understandable Name'])[0]
95:                     entry.append("This is an example of %s" % simplified_label)
96:                 elif self.map == 'description':
97:                     description = list(self.mappings[self.mappings['Original Name'] == label]['Description'])[0]
98:                     entry.append("This is an example of %s" % description)
99:                 elif self.map == 'logical-form':
100:                     form = list(self.mappings[self.mappings['Original Name'] == label]['Logical Form'])[0]
101:                     entry.append("This article matches the following logical form: %s" % form)
102:                 elif self.map == 'masked-logical-form':
103:                     # print(self.mappings[self.mappings['Original Name'] == label]['Masked Logical Form'])
104:                     form = replace_masked_tokens(list(self.mappings[self.mappings['Original Name'] == label]
105:                                                       ['Masked Logical Form'])[0])
106:                     entry.append("This article matches the following logical form: %s" % form)
107:                 if (self.multilabel is False and label == row[self.label_col_name]) or (
108:                         self.multilabel is True and label in row[self.label_col_name]):
109:                     entry.append("entailment")
110:                 else:
111:                     p = random.random()
112:                     if undersample and p > undersampling_rate:
113:                         continue
114:                     entry.append("contradiction")
115:                 weight = (self.total_count / self.counts_dict[label]) / 10
116:                 if entry[-1] == "entailment":
117:                     weight *= 12
118:                 entry.append(weight)
119:                 # print(entry)
120:                 entry.append(label)
121:                 if strat % 2:
122:                     data.append(entry)
123:                 if strat > 1:
124:                     entry1 = [replace_masked_tokens(row['masked_articles']), entry[1], entry[2], entry[3]]
125:                     if entry1[0] != entry[0] or strat == 3:
126:                         data.append(entry1)
127:
128:         return pd.DataFrame(data, columns=['sentence1', 'sentence2', 'gold_label', 'weight','logical_fallacy'])
129:
130:     def init_data(self, fallacy, undersample_train=False, undersample_val=False, undersample_test=False,
131:                   undersample_ratio=0.02, train_strat=1, test_strat=1):
132:         if fallacy:
133:             self.train_df = self.convert_to_mnli(self.train_df, undersample=undersample_train,
134:                                                  undersampling_rate=undersample_ratio, strat=train_strat)
135:             self.val_df = self.convert_to_mnli(self.val_df, undersample=undersample_val,
136:                                                undersampling_rate=undersample_ratio, strat=test_strat)
137:             self.test_df = self.convert_to_mnli(self.test_df, undersample=undersample_test,
138:                                                 undersampling_rate=undersample_ratio, strat=test_strat)
139:         # print(self.counts_dict, self.total_count)
140:         # self.train_df.to_csv('results/temp.csv')
141:         self.train_data = self.load_data(self.train_df)
142:         self.val_data = self.load_data(self.val_df)
143:         self.test_data = self.load_data(self.test_df)
144:
145:     def load_data(self, df):
146:         if df is None:
147:             return None
148:
149:         MAX_LEN = 512
150:         token_ids = []
151:         mask_ids = []
152:         seg_ids = []
153:         y = []
154:         weights = []
155:
156:         df = df.dropna()
157:
158:         premise_list = df['sentence1'].to_list()
159:         hypothesis_list = df['sentence2'].to_list()
160:         label_list = df['gold_label'].to_list()
161:         weight_list = df['weight'].to_list()
162:
163:         for (premise, hypothesis, label, weight) in zip(premise_list, hypothesis_list, label_list, weight_list):
164:
165:             premise_id = self.tokenizer.encode(premise, add_special_tokens=False)
166:             hypothesis_id = self.tokenizer.encode(hypothesis, add_special_tokens=False)
167:             pair_token_ids = [self.tokenizer.cls_token_id] + premise_id + [
168:                 self.tokenizer.sep_token_id] + hypothesis_id + [self.tokenizer.sep_token_id]
169:             # pair_token_ids = premise_id + hypothesis_id
170:             # print("max token id=", max(pair_token_ids))
171:             premise_len = len(premise_id)
172:             hypothesis_len = len(hypothesis_id)
173:
174:             segment_ids = torch.tensor(
175:                 [0] * (premise_len + 2) + [1] * (hypothesis_len + 1))  # sentence 0 and sentence 1
176:             attention_mask_ids = torch.tensor([1] * (premise_len + hypothesis_len + 3))  # mask padded values
177:             if len(pair_token_ids) > MAX_LEN or len(segment_ids) > MAX_LEN or len(attention_mask_ids) > MAX_LEN:
178:                 continue
179:             token_ids.append(torch.tensor(pair_token_ids))
180:             seg_ids.append(segment_ids)

==================== Lines 181-260 ====================
181:             mask_ids.append(attention_mask_ids)
182:             y.append(self.label_dict[label])
183:             weights.append(weight)
184:
185:         token_ids = pad_sequence(token_ids, batch_first=True)
186:         mask_ids = pad_sequence(mask_ids, batch_first=True)
187:         seg_ids = pad_sequence(seg_ids, batch_first=True)
188:         y = torch.tensor(y)
189:         # print(token_ids.shape)
190:         # print(torch.tensor(weights).shape)
191:         dataset = TensorDataset(token_ids, mask_ids, seg_ids, y, torch.tensor(weights))
192:         # print(len(dataset))
193:         return dataset
194:
195:     def get_undersampled(self, ratio=0.04, batch_size=32, shuffle=True):
196:         train_df_entail = self.train_df[self.train_df.gold_label == 'entailment']
197:         train_df_contradict = self.train_df[self.train_df.gold_label == 'contradiction']
198:         train_df_contradict = train_df_contradict.sample(n=int(len(train_df_contradict) * ratio))
199:         df = pd.concat([train_df_contradict, train_df_entail])
200:         df = self.load_data(df)
201:         return DataLoader(
202:             df,
203:             shuffle=shuffle,
204:             batch_size=batch_size
205:         )
206:
207:     def get_data_loaders(self, batch_size=32, shuffle=True):
208:         train_loader = DataLoader(
209:             self.train_data,
210:             shuffle=shuffle,
211:             batch_size=batch_size
212:         )
213:
214:         val_loader = DataLoader(
215:             self.val_data,
216:             shuffle=shuffle,
217:             batch_size=batch_size
218:         )
219:         if self.test_data:
220:             test_loader = DataLoader(
221:                 self.test_data,
222:                 shuffle=False,
223:                 batch_size=len(self.unique_labels)
224:             )
225:         else:
226:             test_loader = None
227:
228:         return train_loader, val_loader, test_loader
229:
230:
231: def get_logger(level='DEBUG'):
232:     logger = logging.getLogger()
233:     logger.handlers = []
234:     file_log_handler = logging.FileHandler('logfile.log')
235:     logger.addHandler(file_log_handler)
236:     stderr_log_handler = logging.StreamHandler()
237:     logger.addHandler(stderr_log_handler)
238:     logger.setLevel(level)
239:     return logger
240:
241:
242: def multi_acc(y_pred, y_test, flip=True):
243:     preds = torch.log_softmax(y_pred, dim=1).argmax(dim=1)
244:     acc = (preds == y_test).sum().float() / float(y_test.size(0))
245:     if flip:
246:         y_pred = 1 - preds.cpu()
247:         y_test = 1 - y_test.cpu()
248:     else:
249:         y_pred = preds.cpu()
250:         y_test = y_test.cpu()
251:     TP = 0
252:     FP = 0
253:     TN = 0
254:     FN = 0
255:     for i in range(len(y_pred)):
256:         if y_test[i] == y_pred[i] == 1:
257:             TP += 1
258:         if y_pred[i] == 1 and y_test[i] != y_pred[i]:
259:             FP += 1
260:         if y_test[i] == y_pred[i] == 0:

In [107]:

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "/content/electra-logic-structaware"
tokenizer_path = "google/electra-base-discriminator"

tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

print("Model:", model.config.model_type)
print("Output classes:", model.config.num_labels)
print("Tokenizer vocabulary:", len(tokenizer))
print("Model embedding vocabulary:", model.get_input_embeddings().num_embeddings)
print("Special tokens:", {
    token: tokenizer.convert_tokens_to_ids(token)
    for token in ["[A]", "[B]", "[C]", "[D]", "[E]",
                  "[F]", "[G]", "[H]", "[I]"]
})
print("Checkpoint and tokenizer loaded successfully.")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Model: electra
Output classes: 3
Tokenizer vocabulary: 30531
Model embedding vocabulary: 30531
Special tokens: {'[A]': 30522, '[B]': 30523, '[C]': 30524, '[D]': 30525, '[E]': 30526, '[F]': 30527, '[G]': 30528, '[H]': 30529, '[I]': 30530}
Checkpoint and tokenizer loaded successfully.

In [108]:

import os
import transformers
import torch

repo = "/content/logical-fallacy"
code_dir = os.path.join(
    repo, "codes_for_models", "experiments_round2"
)

print("Transformers version:", transformers.__version__)
print("PyTorch version:", torch.__version__)
print("\nRequired files:")

for filename in [
    "logicedu.py",
    "library.py",
    "weighted_cross_entropy.py"
]:
    matches = []
    for root, dirs, files in os.walk(repo):
        if filename in files:
            matches.append(os.path.join(root, filename))

    print(f"\n{filename}:")
    for path in matches:
        print(" ", path)

print("\nData files:")
for filename in [
    "edu_train.csv",
    "edu_dev.csv",
    "edu_test.csv",
    "mappings.csv"
]:
    path = os.path.join(repo, "data", filename)
    print(filename, "->", os.path.exists(path))

Transformers version: 5.20.2
PyTorch version: 2.11.0+cu130

Required files:

logicedu.py:
  /content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py

library.py:
  /content/logical-fallacy/codes_for_models/experiments_round2/library.py

weighted_cross_entropy.py:
  /content/logical-fallacy/codes_for_models/experiments_round2/weighted_cross_entropy.py

Data files:
edu_train.csv -> True
edu_dev.csv -> True
edu_test.csv -> True
mappings.csv -> True

In [109]:

import os
import sys
import traceback

repo = "/content/logical-fallacy"
code_dir = os.path.join(
    repo, "codes_for_models", "experiments_round2"
)

os.chdir(code_dir)
if code_dir not in sys.path:
    sys.path.insert(0, code_dir)

try:
    import logicedu
    print("SUCCESS: Original research script imported.")
    print("Script location:", logicedu.__file__)
except Exception:
    print("IMPORT FAILED:")
    traceback.print_exc()

IMPORT FAILED:

Traceback (most recent call last):
  File "/tmp/ipykernel_2317/1833965776.py", line 15, in <cell line: 0>
    import logicedu
  File "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py", line 6, in <module>
    from transformers import AutoTokenizer, AdamW, AutoModelForSequenceClassification
ImportError: cannot import name 'AdamW' from 'transformers' (/usr/local/lib/python3.13/dist-packages/transformers/__init__.py)

In [110]:

import os

path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(path, "r", encoding="utf-8") as f:
    code = f.read()

old_import = "from transformers import AutoTokenizer, AdamW, AutoModelForSequenceClassification"
new_import = """from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.optim import AdamW"""

if old_import not in code:
    print("Expected import line not found. No changes made.")
else:
    code = code.replace(old_import, new_import, 1)

    with open(path, "w", encoding="utf-8") as f:
        f.write(code)

    print("Compatibility fix applied.")
    print("AdamW now imports from torch.optim.")

Compatibility fix applied.
AdamW now imports from torch.optim.

In [111]:

import os
import sys
import traceback

repo = "/content/logical-fallacy"
code_dir = os.path.join(repo, "codes_for_models", "experiments_round2")

os.chdir(code_dir)
if code_dir not in sys.path:
    sys.path.insert(0, code_dir)

try:
    import logicedu
    print("SUCCESS: Original research script imported.")
except Exception:
    print("IMPORT FAILED:")
    traceback.print_exc()

SUCCESS: Original research script imported.

In [112]:

import os
import pandas as pd
from logicedu import MNLIDataset

repo = "/content/logical-fallacy"
data_dir = os.path.join(repo, "data")

train_df = pd.read_csv(os.path.join(data_dir, "edu_train.csv"))
dev_df = pd.read_csv(os.path.join(data_dir, "edu_dev.csv"))
test_df = pd.read_csv(os.path.join(data_dir, "edu_test.csv"))

# Run from the repository root so the original relative mapping path works.
os.chdir(repo)

# Build the original NLI dataset.
fallacy_ds = MNLIDataset(
    tokenizer_path="google/electra-base-discriminator",
    train_df=train_df,
    val_df=dev_df,
    label_col_name="updated_label",
    map="base",
    test_df=test_df,
    fallacy=True,
    train_strat=1,
    test_strat=1
)

print("Fallacy categories:", len(fallacy_ds.unique_labels))
print("Categories:", fallacy_ds.unique_labels)
print("\nGenerated training examples:")
print(fallacy_ds.train_df.head(5).to_string(index=False))
print("\nGenerated training rows:", len(fallacy_ds.train_df))
print("Training tensors:", len(fallacy_ds.train_data))
print("Validation tensors:", len(fallacy_ds.val_data))
print("Test tensors:", len(fallacy_ds.test_data))

FileNotFoundError: [Errno 2] No such file or directory: '../../data/mappings.csv'

In [113]:

import os

repo = "/content/logical-fallacy"
code_dir = os.path.join(
    repo, "codes_for_models", "experiments_round2"
)

os.chdir(code_dir)

print("Current directory:", os.getcwd())

for path in [
    "../../data/mappings.csv",
    "../../data/edu_train.csv",
    "../../data/edu_dev.csv",
    "../../data/edu_test.csv",
]:
    print(path, "->", os.path.exists(path))

Current directory: /content/logical-fallacy/codes_for_models/experiments_round2
../../data/mappings.csv -> True
../../data/edu_train.csv -> True
../../data/edu_dev.csv -> True
../../data/edu_test.csv -> True

In [114]:

import pandas as pd
from logicedu import MNLIDataset

train_df = pd.read_csv("../../data/edu_train.csv")
dev_df = pd.read_csv("../../data/edu_dev.csv")
test_df = pd.read_csv("../../data/edu_test.csv")

fallacy_ds = MNLIDataset(
    tokenizer_path="google/electra-base-discriminator",
    train_df=train_df,
    val_df=dev_df,
    label_col_name="updated_label",
    map="base",
    test_df=test_df,
    fallacy=True,
    train_strat=1,
    test_strat=1
)

print("Fallacy categories:", len(fallacy_ds.unique_labels))
print("Categories:", fallacy_ds.unique_labels)
print("\nGenerated training examples:")
print(fallacy_ds.train_df.head(5).to_string(index=False))
print("\nGenerated training rows:", len(fallacy_ds.train_df))
print("Training tensors:", len(fallacy_ds.train_data))
print("Validation tensors:", len(fallacy_ds.val_data))
print("Test tensors:", len(fallacy_ds.test_data))

Fallacy categories: 13
Categories: ['appeal to emotion', 'false causality', 'ad populum', 'circular reasoning', 'fallacy of relevance', 'faulty generalization', 'ad hominem', 'fallacy of extension', 'equivocation', 'fallacy of logic', 'fallacy of credibility', 'intentional', 'false dilemma']

Generated training examples:
                                sentence1                                                  sentence2    gold_label  weight      logical_fallacy
company's slogan "Expect More. Pay Less."    This is an example of appeal to emotion logical fallacy    entailment    15.6    appeal to emotion
company's slogan "Expect More. Pay Less."      This is an example of false causality logical fallacy contradiction     1.3      false causality
company's slogan "Expect More. Pay Less."           This is an example of ad populum logical fallacy contradiction     1.3           ad populum
company's slogan "Expect More. Pay Less."   This is an example of circular reasoning logical fallacy contradiction     1.3   circular reasoning
company's slogan "Expect More. Pay Less." This is an example of fallacy of relevance logical fallacy contradiction     1.3 fallacy of relevance

Generated training rows: 24037
Training tensors: 24037
Validation tensors: 3900
Test tensors: 3900

In [115]:

import inspect
import logicedu

print("Training function signature:")
print(inspect.signature(logicedu.train))

print("\nTraining function source:")
print(inspect.getsource(logicedu.train))

Training function signature:
(model, dataset, optimizer, logger, save_path, device, epochs=5, ratio=0.04, positive_weight=12, debug=False)

Training function source:
def train(model, dataset, optimizer, logger, save_path, device, epochs=5, ratio=0.04, positive_weight=12, debug=False):
    train_loader, val_loader, _ = dataset.get_data_loaders()
    min_val_loss = float('inf')
    loss_fn = nn.CrossEntropyLoss(reduction='none')
    loss_fn.to(device)
    for epoch in range(epochs):
        start = time.time()
        model.train()
        total_train_loss = 0
        total_train_acc = 0
        total_train_prec = 0
        total_train_rec = 0
        if ratio < 1:
            train_loader = dataset.get_undersampled(ratio)
        for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(train_loader):
            # print(weights.shape)
            if batch_idx % 10 == 0:
                logger.debug('%d %d', epoch, batch_idx)
            optimizer.zero_grad()
            pair_token_ids = pair_token_ids.to(device)
            mask_ids = mask_ids.to(device)
            seg_ids = seg_ids.to(device)
            labels = y.to(device)
            weights = weights.to(device)
            if debug:
                print(pair_token_ids.shape, seg_ids.shape, mask_ids.shape)
                break
            _, prediction = model(pair_token_ids,
                                  token_type_ids=seg_ids,
                                  attention_mask=mask_ids,
                                  labels=labels).values()
            # print(weights.shape)
            loss = loss_fn(prediction, labels)
            # print(loss.shape)
            len1 = loss.shape[0]
            loss = torch.dot(loss, weights) / len1
            # print('forward prop done')
            acc, prec, rec = multi_acc(prediction, labels)
            # print(acc,prec,rec)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()
            total_train_acc += acc.float()
            total_train_prec += prec
            total_train_rec += rec
        if debug:
            break
        train_acc = total_train_acc / len(train_loader)
        train_loss = total_train_loss / len(train_loader)
        train_prec = total_train_prec / len(train_loader)
        train_rec = total_train_rec / len(train_loader)
        model.eval()
        total_val_acc = 0
        total_val_loss = 0
        total_val_prec = 0
        total_val_rec = 0

        with torch.no_grad():
            for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(val_loader):
                pair_token_ids = pair_token_ids.to(device)
                mask_ids = mask_ids.to(device)
                seg_ids = seg_ids.to(device)
                labels = y.to(device)
                weights = weights.to(device)
                _, prediction = model(pair_token_ids,
                                      token_type_ids=seg_ids,
                                      attention_mask=mask_ids,
                                      labels=labels).values()
                loss = loss_fn(prediction, labels)
                len1 = loss.shape[0]
                loss = torch.dot(loss, weights) / len1
                acc, prec, rec = multi_acc(prediction, labels)

                total_val_loss += loss.item()
                total_val_acc += acc.float()
                total_val_prec += prec
                total_val_rec += rec

        val_acc = total_val_acc / len(val_loader)
        val_loss = total_val_loss / len(val_loader)
        val_rec = total_val_rec / len(val_loader)
        val_prec = total_val_prec / len(val_loader)
        flag = True
        if val_loss < min_val_loss:
            min_val_loss = val_loss
            logger.info("saving model")
            model.save_pretrained(save_path)
        else:
            flag = False
        end = time.time()
        hours, rem = divmod(end - start, 3600)
        minutes, seconds = divmod(rem, 60)

        logger.info(
            f'Epoch {epoch + 1}: train_loss: {train_loss:.4f} train_acc: {train_acc:.4f} train_prec: {train_prec:.4f} '
            f'train_rec: {train_rec:.4f}| val_loss: {val_loss:.4f} val_acc: {val_acc:.4f} val_prec: {val_prec:.4f} '
            f'val_rec: {val_rec:.4f}'
        )
        logger.info("{:0>2}:{:0>2}:{:05.2f}".format(int(hours), int(minutes), seconds))
        if not flag:
            break

In [116]:

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "/content/electra-logic-structaware"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Use the same tokenizer setup as the original research code.
tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator",
    do_lower_case=True
)
tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)
model.resize_token_embeddings(len(tokenizer))
model.to(device)
model.eval()

# Use one actual preprocessed example.
pair_token_ids, mask_ids, seg_ids, labels, weights = next(
    iter(fallacy_ds.get_data_loaders(batch_size=2)[0])
)

with torch.no_grad():
    outputs = model(
        input_ids=pair_token_ids.to(device),
        token_type_ids=seg_ids.to(device),
        attention_mask=mask_ids.to(device),
        labels=labels.to(device)
    )

print("Device:", device)
print("Input shape:", tuple(pair_token_ids.shape))
print("Logits shape:", tuple(outputs.logits.shape))
print("Loss:", round(outputs.loss.item(), 4))
print("Forward pass successful.")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Device: cuda
Input shape: (2, 251)
Logits shape: (2, 3)
Loss: 0.5766
Forward pass successful.

In [117]:

import os
import shutil
import torch

output_dir = "/content/fallacylens_trained_model"
os.makedirs(output_dir, exist_ok=True)

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU memory (GB):",
          round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))

total, used, free = shutil.disk_usage("/content")
print("Free disk space (GB):", round(free / 1e9, 2))
print("Model output directory:", output_dir)

GPU available: True
GPU: Tesla T4
GPU memory (GB): 15.64
Free disk space (GB): 73.85
Model output directory: /content/fallacylens_trained_model

In [118]:

import os
import torch
from torch.optim import AdamW
import logicedu

# Confirm the previous setup is still available.
assert "fallacy_ds" in globals(), "Please rerun the dataset preprocessing cell."
assert "model" in globals(), "Please rerun the model loading cell."

output_dir = "/content/fallacylens_trained_model"
os.makedirs(output_dir, exist_ok=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Original research optimizer settings.
optimizer = AdamW(model.parameters(), lr=2e-5)

# Save the training log in the original experiment directory.
logger = logicedu.get_logger()
logger.info("Starting FallacyLens baseline training")
logger.info("Device: %s", device)
logger.info("Training examples: %d", len(fallacy_ds.train_data))
logger.info("Validation examples: %d", len(fallacy_ds.val_data))

# Original training function: maximum 10 epochs.
logicedu.train(
    model=model,
    dataset=fallacy_ds,
    optimizer=optimizer,
    logger=logger,
    save_path=output_dir,
    device=device,
    epochs=10,
    ratio=1,
    positive_weight=12
)

print("\nTraining function finished.")
print("Checkpoint directory:", output_dir)
print("Checkpoint config exists:",
      os.path.exists(os.path.join(output_dir, "config.json")))

Starting FallacyLens baseline training
Device: cuda
Training examples: 24037
Validation examples: 3900
0 0
0 10
0 20
0 30
0 40
0 50
0 60
0 70
0 80
0 90
0 100
0 110
0 120
0 130
0 140
0 150
0 160
0 170
0 180
0 190
0 200
0 210
0 220
0 230
0 240
0 250
0 260
0 270
0 280
0 290
0 300
0 310
0 320
0 330
0 340
0 350
0 360
0 370
0 380
0 390
0 400
0 410
0 420
0 430
0 440
0 450
0 460
0 470
0 480
0 490
0 500
0 510
0 520
0 530
0 540
0 550
0 560
0 570
0 580
0 590
0 600
0 610
0 620
0 630
0 640
0 650
0 660
0 670
0 680
0 690
0 700
0 710
0 720
0 730
0 740
0 750
saving model

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1: train_loss: 0.9828 train_acc: 0.8151 train_prec: 0.2874 train_rec: 0.7356| val_loss: 0.8728 val_acc: 0.8360 val_prec: 0.3028 val_rec: 0.8139
00:16:50.80
1 0
1 10
1 20
1 30
1 40
1 50
1 60
1 70
1 80
1 90
1 100
1 110
1 120
1 130
1 140
1 150
1 160
1 170
1 180
1 190
1 200
1 210
1 220
1 230
1 240
1 250
1 260
1 270
1 280
1 290
1 300
1 310
1 320
1 330
1 340
1 350
1 360
1 370
1 380
1 390
1 400
1 410
1 420
1 430
1 440
1 450
1 460
1 470
1 480
1 490
1 500
1 510
1 520
1 530
1 540
1 550
1 560
1 570
1 580
1 590
1 600
1 610
1 620
1 630
1 640
1 650
1 660
1 670
1 680
1 690
1 700
1 710
1 720
1 730
1 740
1 750
Epoch 2: train_loss: 0.6088 train_acc: 0.9015 train_prec: 0.4391 train_rec: 0.8077| val_loss: 0.9071 val_acc: 0.8977 val_prec: 0.3987 val_rec: 0.7352
00:16:48.70

Training function finished.
Checkpoint directory: /content/fallacylens_trained_model
Checkpoint config exists: True

In [1]:

import os

output_dir = "/content/fallacylens_trained_model"

print("Checkpoint files:")
for file in os.listdir(output_dir):
    print(file)

print("\nModel weights saved:",
      any(f in os.listdir(output_dir)
          for f in ["model.safetensors", "pytorch_model.bin"]))

print("Config saved:",
      os.path.exists(os.path.join(output_dir, "config.json")))

Checkpoint files:

FileNotFoundError: [Errno 2] No such file or directory: '/content/fallacylens_trained_model'

In [3]:

import os

print("Current working directory:", os.getcwd())
print("\nChecking common locations:")

paths = [
    "/content/fallacylens_trained_model",
    "/content/logical-fallacy",
    "/content/electra-logic-structaware",
    "/content/drive/MyDrive"
]

for path in paths:
    print(f"{path}: {'EXISTS' if os.path.exists(path) else 'NOT FOUND'}")

print("\nSearching /content for model checkpoint files:")
for root, dirs, files in os.walk("/content"):
    dirs[:] = [d for d in dirs if d not in [".git", "node_modules"]]
    for file in files:
        if file in ["model.safetensors", "pytorch_model.bin"]:
            print(os.path.join(root, file))

Current working directory: /content

Checking common locations:
/content/fallacylens_trained_model: NOT FOUND
/content/logical-fallacy: NOT FOUND
/content/electra-logic-structaware: NOT FOUND
/content/drive/MyDrive: NOT FOUND

Searching /content for model checkpoint files:

In [5]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:

import os

drive_path = "/content/drive/MyDrive"

print("Google Drive available:", os.path.exists(drive_path))

if os.path.exists(drive_path):
    for root, dirs, files in os.walk(drive_path):
        dirs[:] = [d for d in dirs if d not in [".git", "node_modules"]]
        for file in files:
            if (
                "fallacylens" in file.lower()
                or "electra-logic-structaware" in file.lower()
                or file == "pytorch_model.bin"
                or file == "model.safetensors"
            ):
                print(os.path.join(root, file))

Google Drive available: True
/content/drive/MyDrive/Colab Notebooks/FallacyLens_Model_Training.ipynb
/content/drive/MyDrive/Colab Notebooks/FallacyLens_Colab_Backend.ipynb
/content/drive/MyDrive/Colab Notebooks/FallacyLens_Research_Baseline.ipynb

In [10]:

import os

drive_path = "/content/drive/MyDrive"

for root, dirs, files in os.walk(drive_path):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "node_modules"]
    ]

    for folder in dirs:
        if "fallacy" in folder.lower() or "electra" in folder.lower():
            print("Folder:", os.path.join(root, folder))

    for file in files:
        if file in [
            "config.json",
            "model.safetensors",
            "pytorch_model.bin"
        ]:
            print("Model-related file:", os.path.join(root, file))

In [11]:

import os

notebook_path = (
    "/content/drive/MyDrive/Colab Notebooks/"
    "FallacyLens_Model_Training.ipynb"
)

print("Training notebook exists:", os.path.exists(notebook_path))

if os.path.exists(notebook_path):
    print("Notebook size:",
          round(os.path.getsize(notebook_path) / 1024, 2), "KB")

Training notebook exists: True
Notebook size: 310.67 KB

In [12]:

import json

notebook_path = (
    "/content/drive/MyDrive/Colab Notebooks/"
    "FallacyLens_Model_Training.ipynb"
)

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

for i, cell in enumerate(notebook.get("cells", [])):
    source = "".join(cell.get("source", []))

    if any(word in source.lower() for word in [
        "logicedu.train",
        "fallacylens_trained_model",
        "save_pretrained",
        "saving model",
        "checkpoint"
    ]):
        print(f"\n--- CELL {i} ---")
        print(source[:2500])

        for output in cell.get("outputs", []):
            if "text" in output:
                print("SAVED OUTPUT:")
                print("".join(output["text"])[-1500:])

--- CELL 15 ---

import os

repo = "/content/logical-fallacy"

print("Repository exists:", os.path.exists(repo))

print("\nTraining-related Python files:")
for root, dirs, files in os.walk(repo):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "__pycache__"]
    ]

    for file in files:
        if file.endswith(".py") and any(
            word in file.lower()
            for word in ["train", "logic", "experiment", "main"]
        ):
            print(os.path.relpath(
                os.path.join(root, file), repo
            ))

print("\nSaved-model or checkpoint directories:")
for root, dirs, files in os.walk(repo):
    dirs[:] = [
        d for d in dirs
        if d not in [".git", "__pycache__"]
    ]

    if any(word in root.lower()
           for word in ["saved_models", "checkpoint", "results"]):
        print(os.path.relpath(root, repo))

SAVED OUTPUT:
Repository exists: False

Training-related Python files:

Saved-model or checkpoint directories:


--- CELL 28 ---

import os

print("Checkpoint files:")
for filename in os.listdir("/content/electra-logic-structaware"):
    print(filename)

SAVED OUTPUT:
Checkpoint files:
config.json
pytorch_model.bin


--- CELL 32 ---

from transformers import AutoTokenizer

# Candidate base tokenizer for ELECTRA
tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator",
    do_lower_case=True
)

print("Original tokenizer vocabulary:", len(tokenizer))

# Match the special tokens used by the original research code
special_tokens = {
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
}

tokenizer.add_special_tokens(special_tokens)

print("Vocabulary after adding special tokens:", len(tokenizer))
print("Expected checkpoint vocabulary: 30531")

print("\nTokenization test:")
print(tokenizer.tokenize("This argument may contain a fallacy."))

SAVED OUTPUT:
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

SAVED OUTPUT:
Original tokenizer vocabulary: 30522
Vocabulary after adding special tokens: 30531
Expected checkpoint vocabulary: 30531

Tokenization test:
['this', 'argument', 'may', 'contain', 'a', 'fall', '##acy', '.']


--- CELL 35 ---

import os

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

if os.path.exists(weights_path):
    os.remove(weights_path)
    print("Incomplete checkpoint removed.")
else:
    print("No existing checkpoint found.")

SAVED OUTPUT:
Incomplete checkpoint removed.


--- CELL 36 ---

import os

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

size_mb = os.path.getsize(weights_path) / (1024 * 1024)

print(f"Checkpoint size: {size_mb:.1f} MB")
print("Checkpoint looks complete:", size_mb > 400)


--- CELL 42 ---

import os
import gzip

weights_path = "/content/electra-logic-structaware/pytorch_model.bin"

print("File exists:", os.path.exists(weights_path))

if os.path.exists(weights_path):
    size = os.path.getsize(weights_path)
    print("File size:", round(size / (1024 * 1024), 2), "MB")

    with open(weights_path, "rb") as f:
        header = f.read(32)

    print("First 32 bytes:", header)
    print("Hex:", header.hex())

    if header.startswith(b"PK"):
        print("Detected format: ZIP-based PyTorch checkpoint")
    elif header.startswith(b"\x1f\x8b"):
        print("Detected format: GZIP-compressed file")
    else:
        print("Format not identified from header")

SAVED OUTPUT:
File exists: True
File size: 409.76 MB
First 32 bytes: b'cGR=\x8b\x1co=C\xc7\xee\xbc[\x12O<\xb5{\xd2<\x17}\xbf\xbb\xc0f\x7f\xbc\x10\xc0\x02\xbd'
Hex: 6347523d8b1c6f3d43c7eebc5b124f3cb57bd23c177dbfbbc0667fbc10c002bd
Format not identified from header


--- CELL 46 ---
import os
import shutil
from transformers import AutoModelForSequenceClassification

source = "/content/pytorch_model_original.bin"
folder = "/content/electra-logic-structaware"
destination = os.path.join(folder, "pytorch_model.bin")

shutil.copyfile(source, destination)
print("Checkpoint copied successfully.")

model = AutoModelForSequenceClassification.from_pretrained(
    folder,
    num_labels=3
)

print("SUCCESS: Model loaded!")
print("Model type:", type(model).__name__)
print("Number of labels:", model.config.num_labels)
SAVED OUTPUT:
Checkpoint copied successfully.

SAVED OUTPUT:
SUCCESS: Model loaded!
Model type: ElectraForSequenceClassification
Number of labels: 3


--- CELL 61 ---

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "/content/electra-logic-structaware"
tokenizer_path = "google/electra-base-discriminator"

tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

print("Model:", model.config.model_type)
print("Output classes:", model.config.num_labels)
print("Tokenizer vocabulary:", len(tokenizer))
print("Model embedding vocabulary:", model.get_input_embeddings().num_embeddings)
print("Special tokens:", {
    token: tokenizer.convert_tokens_to_ids(token)
    for token in ["[A]", "[B]", "[C]", "[D]", "[E]",
                  "[F]", "[G]", "[H]", "[I]"]
})
print("Checkpoint and tokenizer loaded successfully.")

SAVED OUTPUT:
Model: electra
Output classes: 3
Tokenizer vocabulary: 30531
Model embedding vocabulary: 30531
Special tokens: {'[A]': 30522, '[B]': 30523, '[C]': 30524, '[D]': 30525, '[E]': 30526, '[F]': 30527, '[G]': 30528, '[H]': 30529, '[I]': 30530}
Checkpoint and tokenizer loaded successfully.


--- CELL 69 ---

import inspect
import logicedu

print("Training function signature:")
print(inspect.signature(logicedu.train))

print("\nTraining function source:")
print(inspect.getsource(logicedu.train))

SAVED OUTPUT:
     token_type_ids=seg_ids,
                                      attention_mask=mask_ids,
                                      labels=labels).values()
                loss = loss_fn(prediction, labels)
                len1 = loss.shape[0]
                loss = torch.dot(loss, weights) / len1
                acc, prec, rec = multi_acc(prediction, labels)

                total_val_loss += loss.item()
                total_val_acc += acc.float()
                total_val_prec += prec
                total_val_rec += rec

        val_acc = total_val_acc / len(val_loader)
        val_loss = total_val_loss / len(val_loader)
        val_rec = total_val_rec / len(val_loader)
        val_prec = total_val_prec / len(val_loader)
        flag = True
        if val_loss < min_val_loss:
            min_val_loss = val_loss
            logger.info("saving model")
            model.save_pretrained(save_path)
        else:
            flag = False
        end = time.time()
        hours, rem = divmod(end - start, 3600)
        minutes, seconds = divmod(rem, 60)

        logger.info(
            f'Epoch {epoch + 1}: train_loss: {train_loss:.4f} train_acc: {train_acc:.4f} train_prec: {train_prec:.4f} '
            f'train_rec: {train_rec:.4f}| val_loss: {val_loss:.4f} val_acc: {val_acc:.4f} val_prec: {val_prec:.4f} '
            f'val_rec: {val_rec:.4f}'
        )
        logger.info("{:0>2}:{:0>2}:{:05.2f}".format(int(hours), int(minutes), seconds))
        if not flag:
            break



--- CELL 71 ---

import os
import shutil
import torch

output_dir = "/content/fallacylens_trained_model"
os.makedirs(output_dir, exist_ok=True)

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU memory (GB):",
          round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))

total, used, free = shutil.disk_usage("/content")
print("Free disk space (GB):", round(free / 1e9, 2))
print("Model output directory:", output_dir)

SAVED OUTPUT:
GPU available: True
GPU: Tesla T4
GPU memory (GB): 15.64
Free disk space (GB): 73.85
Model output directory: /content/fallacylens_trained_model


--- CELL 72 ---

import os
import torch
from torch.optim import AdamW
import logicedu

# Confirm the previous setup is still available.
assert "fallacy_ds" in globals(), "Please rerun the dataset preprocessing cell."
assert "model" in globals(), "Please rerun the model loading cell."

output_dir = "/content/fallacylens_trained_model"
os.makedirs(output_dir, exist_ok=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Original research optimizer settings.
optimizer = AdamW(model.parameters(), lr=2e-5)

# Save the training log in the original experiment directory.
logger = logicedu.get_logger()
logger.info("Starting FallacyLens baseline training")
logger.info("Device: %s", device)
logger.info("Training examples: %d", len(fallacy_ds.train_data))
logger.info("Validation examples: %d", len(fallacy_ds.val_data))

# Original training function: maximum 10 epochs.
logicedu.train(
    model=model,
    dataset=fallacy_ds,
    optimizer=optimizer,
    logger=logger,
    save_path=output_dir,
    device=device,
    epochs=10,
    ratio=1,
    positive_weight=12
)

print("\nTraining function finished.")
print("Checkpoint directory:", output_dir)
print("Checkpoint config exists:",
      os.path.exists(os.path.join(output_dir, "config.json")))

SAVED OUTPUT:
Starting FallacyLens baseline training
Device: cuda
Training examples: 24037
Validation examples: 3900
0 0
0 10
0 20
0 30
0 40
0 50
0 60
0 70
0 80
0 90
0 100
0 110
0 120
0 130
0 140
0 150
0 160
0 170
0 180
0 190
0 200
0 210
0 220
0 230
0 240
0 250
0 260
0 270
0 280
0 290
0 300
0 310
0 320
0 330
0 340
0 350
0 360
0 370
0 380
0 390
0 400
0 410
0 420
0 430
0 440
0 450
0 460
0 470
0 480
0 490
0 500
0 510
0 520
0 530
0 540
0 550
0 560
0 570
0 580
0 590
0 600
0 610
0 620
0 630
0 640
0 650
0 660
0 670
0 680
0 690
0 700
0 710
0 720
0 730
0 740
0 750
saving model

SAVED OUTPUT:
Epoch 1: train_loss: 0.9828 train_acc: 0.8151 train_prec: 0.2874 train_rec: 0.7356| val_loss: 0.8728 val_acc: 0.8360 val_prec: 0.3028 val_rec: 0.8139
00:16:50.80
1 0
1 10
1 20
1 30
1 40
1 50
1 60
1 70
1 80
1 90
1 100
1 110
1 120
1 130
1 140
1 150
1 160
1 170
1 180
1 190
1 200
1 210
1 220
1 230
1 240
1 250
1 260
1 270
1 280
1 290
1 300
1 310
1 320
1 330
1 340
1 350
1 360
1 370
1 380
1 390
1 400
1 410
1 420
1 430
1 440
1 450
1 460
1 470
1 480
1 490
1 500
1 510
1 520
1 530
1 540
1 550
1 560
1 570
1 580
1 590
1 600
1 610
1 620
1 630
1 640
1 650
1 660
1 670
1 680
1 690
1 700
1 710
1 720
1 730
1 740
1 750
Epoch 2: train_loss: 0.6088 train_acc: 0.9015 train_prec: 0.4391 train_rec: 0.8077| val_loss: 0.9071 val_acc: 0.8977 val_prec: 0.3987 val_rec: 0.7352
00:16:48.70

SAVED OUTPUT:

Training function finished.
Checkpoint directory: /content/fallacylens_trained_model
Checkpoint config exists: True


--- CELL 73 ---

import os

output_dir = "/content/fallacylens_trained_model"

print("Checkpoint files:")
for file in os.listdir(output_dir):
    print(file)

print("\nModel weights saved:",
      any(f in os.listdir(output_dir)
          for f in ["model.safetensors", "pytorch_model.bin"]))

print("Config saved:",
      os.path.exists(os.path.join(output_dir, "config.json")))

SAVED OUTPUT:
Checkpoint files:


--- CELL 74 ---

import os

print("Current working directory:", os.getcwd())
print("\nChecking common locations:")

paths = [
    "/content/fallacylens_trained_model",
    "/content/logical-fallacy",
    "/content/electra-logic-structaware",
    "/content/drive/MyDrive"
]

for path in paths:
    print(f"{path}: {'EXISTS' if os.path.exists(path) else 'NOT FOUND'}")

print("\nSearching /content for model checkpoint files:")
for root, dirs, files in os.walk("/content"):
    dirs[:] = [d for d in dirs if d not in [".git", "node_modules"]]
    for file in files:
        if file in ["model.safetensors", "pytorch_model.bin"]:
            print(os.path.join(root, file))

SAVED OUTPUT:
Current working directory: /content

Checking common locations:
/content/fallacylens_trained_model: NOT FOUND
/content/logical-fallacy: NOT FOUND
/content/electra-logic-structaware: NOT FOUND
/content/drive/MyDrive: NOT FOUND

Searching /content for model checkpoint files:

In [13]:

import json

notebook_path = (
    "/content/drive/MyDrive/Colab Notebooks/"
    "FallacyLens_Model_Training.ipynb"
)

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

for i, cell in enumerate(notebook.get("cells", [])):
    source = "".join(cell.get("source", []))

    if "logicedu.train(" in source or "Starting FallacyLens baseline training" in source:
        print(f"\n===== TRAINING CELL {i} =====")
        print(source)

        for output in cell.get("outputs", []):
            if "text" in output:
                print("\n===== SAVED TRAINING OUTPUT =====")
                print("".join(output["text"])[-3000:])

===== TRAINING CELL 72 =====

import os
import torch
from torch.optim import AdamW
import logicedu

# Confirm the previous setup is still available.
assert "fallacy_ds" in globals(), "Please rerun the dataset preprocessing cell."
assert "model" in globals(), "Please rerun the model loading cell."

output_dir = "/content/fallacylens_trained_model"
os.makedirs(output_dir, exist_ok=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Original research optimizer settings.
optimizer = AdamW(model.parameters(), lr=2e-5)

# Save the training log in the original experiment directory.
logger = logicedu.get_logger()
logger.info("Starting FallacyLens baseline training")
logger.info("Device: %s", device)
logger.info("Training examples: %d", len(fallacy_ds.train_data))
logger.info("Validation examples: %d", len(fallacy_ds.val_data))

# Original training function: maximum 10 epochs.
logicedu.train(
    model=model,
    dataset=fallacy_ds,
    optimizer=optimizer,
    logger=logger,
    save_path=output_dir,
    device=device,
    epochs=10,
    ratio=1,
    positive_weight=12
)

print("\nTraining function finished.")
print("Checkpoint directory:", output_dir)
print("Checkpoint config exists:",
      os.path.exists(os.path.join(output_dir, "config.json")))


===== SAVED TRAINING OUTPUT =====
Starting FallacyLens baseline training
Device: cuda
Training examples: 24037
Validation examples: 3900
0 0
0 10
0 20
0 30
0 40
0 50
0 60
0 70
0 80
0 90
0 100
0 110
0 120
0 130
0 140
0 150
0 160
0 170
0 180
0 190
0 200
0 210
0 220
0 230
0 240
0 250
0 260
0 270
0 280
0 290
0 300
0 310
0 320
0 330
0 340
0 350
0 360
0 370
0 380
0 390
0 400
0 410
0 420
0 430
0 440
0 450
0 460
0 470
0 480
0 490
0 500
0 510
0 520
0 530
0 540
0 550
0 560
0 570
0 580
0 590
0 600
0 610
0 620
0 630
0 640
0 650
0 660
0 670
0 680
0 690
0 700
0 710
0 720
0 730
0 740
0 750
saving model


===== SAVED TRAINING OUTPUT =====
Epoch 1: train_loss: 0.9828 train_acc: 0.8151 train_prec: 0.2874 train_rec: 0.7356| val_loss: 0.8728 val_acc: 0.8360 val_prec: 0.3028 val_rec: 0.8139
00:16:50.80
1 0
1 10
1 20
1 30
1 40
1 50
1 60
1 70
1 80
1 90
1 100
1 110
1 120
1 130
1 140
1 150
1 160
1 170
1 180
1 190
1 200
1 210
1 220
1 230
1 240
1 250
1 260
1 270
1 280
1 290
1 300
1 310
1 320
1 330
1 340
1 350
1 360
1 370
1 380
1 390
1 400
1 410
1 420
1 430
1 440
1 450
1 460
1 470
1 480
1 490
1 500
1 510
1 520
1 530
1 540
1 550
1 560
1 570
1 580
1 590
1 600
1 610
1 620
1 630
1 640
1 650
1 660
1 670
1 680
1 690
1 700
1 710
1 720
1 730
1 740
1 750
Epoch 2: train_loss: 0.6088 train_acc: 0.9015 train_prec: 0.4391 train_rec: 0.8077| val_loss: 0.9071 val_acc: 0.8977 val_prec: 0.3987 val_rec: 0.7352
00:16:48.70


===== SAVED TRAINING OUTPUT =====

Training function finished.
Checkpoint directory: /content/fallacylens_trained_model
Checkpoint config exists: True

In [14]:
output_dir = "/content/fallacylens_trained_model"

In [15]:
output_dir = "/content/drive/MyDrive/FallacyLens/trained_model"

In [16]:

from google.colab import drive
import os

drive.mount("/content/drive")

output_dir = "/content/drive/MyDrive/FallacyLens/trained_model"
os.makedirs(output_dir, exist_ok=True)

print("Checkpoint folder ready:", output_dir)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint folder ready: /content/drive/MyDrive/FallacyLens/trained_model

In [17]:

!git clone https://github.com/causalNLP/logical-fallacy.git /content/logical-fallacy

Cloning into '/content/logical-fallacy'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 254 (delta 44), reused 29 (delta 28), pack-reused 181 (from 1)
Receiving objects: 100% (254/254), 10.55 MiB | 17.74 MiB/s, done.
Resolving deltas: 100% (94/94), done.

In [18]:

import os

repo_path = "/content/logical-fallacy"
data_path = os.path.join(repo_path, "data")
code_path = os.path.join(
    repo_path, "codes_for_models", "experiments_round2"
)

print("Repository exists:", os.path.exists(repo_path))
print("Training script exists:",
      os.path.exists(os.path.join(code_path, "logicedu.py")))
print("Training data exists:",
      os.path.exists(os.path.join(data_path, "edu_train.csv")))
print("Validation data exists:",
      os.path.exists(os.path.join(data_path, "edu_dev.csv")))
print("Test data exists:",
      os.path.exists(os.path.join(data_path, "edu_test.csv")))

Repository exists: True
Training script exists: True
Training data exists: True
Validation data exists: True
Test data exists: True

In [27]:

import os

drive_path = "/content/drive/MyDrive"

for root, dirs, files in os.walk(drive_path):
    dirs[:] = [d for d in dirs if d not in [".git", "node_modules"]]

    for folder in dirs:
        if "electra-logic-structaware" in folder.lower():
            print("Model folder found:", os.path.join(root, folder))

    for file in files:
        if file == "pytorch_model.bin" or file == "model.safetensors":
            if "fallacylens" in root.lower() or "electra" in root.lower():
                print("Model weights found:", os.path.join(root, file))

In [28]:

import os

path = "/content/drive/MyDrive"

print("Drive mounted:", os.path.exists(path))
print("Top-level Drive folders:", os.listdir(path)[:30])

Drive mounted: True
Top-level Drive folders: ['Colab Notebooks', 'IXASSESSMENT-III_B_EXAMINATION-MATHEMATICS_1_.pdf', 'PE.pdf', 'Daksh ', 'IX-MATHEMATICS_SECONDTERMINALEXAMINATION.pdf', 'https:  images..txt', '8ee58dbb-c9a2-41bf-b1a1-f3b6f9657875.pdf', 'Naina Covid-19.pdf', 'samjuban covid-19.pdf', 'Mahesh covid-19.pdf', '11.MATHS.pdf', 'Postponement of the ICSE and ISC Year 2021-2022 Semester 1 Examinations (1).pdf', 'Copy of Class 12 Mathematics and Statistics Part 1 Textbook Pdf.pdf', 'IMG_20221004_233127.jpg', 'Videos and photos', 'Marriage ', 'Adobe Scan 27-Feb-2024.pdf', 'EAadhaar_2722400976417120220520153802_1107202316317 .pdf', 'photo', 'SOP Core Format.docx', 'image (1).jpg', 'image.jpg', 'IMG_2700.png', 'IMG_3377.png', 'IMG_8862.png', 'CYBER M2.xls', '41e682d1-ce14-4a9d-ba6b-1a207e77380d.jpeg', 'Expense Sheet The CNC Crew.xlsx', 'IMG_9290.png', 'K007_K008_CaseStudy_EPM.gdoc']

In [29]:

!pip -q install -U transformers

from transformers import AutoConfig

print("Checking the public ELECTRA configuration...")

config = AutoConfig.from_pretrained(
    "google/electra-base-discriminator"
)

print("Model type:", config.model_type)
print("Vocabulary size:", config.vocab_size)

Checking the public ELECTRA configuration...

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

Model type: electra
Vocabulary size: 30522

In [30]:

!pip -q install gdown

import os

models_dir = "/content/author_models"
os.makedirs(models_dir, exist_ok=True)

print("Folder ready:", models_dir)
print("Next: download the authors' pretrained checkpoint.")

Folder ready: /content/author_models
Next: download the authors' pretrained checkpoint.

In [31]:

!gdown --folder "https://drive.google.com/drive/folders/13icpZY_HNemv9Da14fYEyw8EfoxEvKQZ" -O /content/author_models

Retrieving folder contents
Retrieving folder 1nCzNJboVlOGZ8jbC_JLR3fJc2YwmJ30N electra-logic
Processing file 1hhyZRfADD4Nz8Q2oVf-bvDiNmnQ9sdtA config.json
Processing file 1dh-wTzw-pyRlbpX0nKG17cBhndsFfbzt pytorch_model.bin
Retrieving folder 1zeDG2ruHcZjaUZb82hjMzC6gbl9CWJq_ electra-logic-structaware
Processing file 1_ErzN3iBRNvK70CNS0K2v85JKMAMLzyR config.json
Processing file 1V4lDQGKGazPlCkDE8ZOYNYclnFKTzFhu pytorch_model.bin
Retrieving folder 1wPXoZ-MyR5FBsQKcpS1n1oW1f2-1Kqay electra-logicclimate
Processing file 1r_VKrq52QaDgnr9aZ8mqEkmI8x-3lmKe config.json
Processing file 1mlmNNk8l1zGHeHw_KNU3jSA2TC453P79 pytorch_model.bin
Retrieving folder 1mDOLYOQzDBnK75jUdhvfpPBZYr_-GQRc electra-logicclimate-structaware
Processing file 1Gub_Jx4Ipk_GjT-Hpww8WQZxh4CmXkDC config.json
Processing file 18kJ7zQ_0wiuVVPyxwZIP7hD9kh--iJ54 pytorch_model.bin
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1hhyZRfADD4Nz8Q2oVf-bvDiNmnQ9sdtA
To: /content/author_models/electra-logic/config.json
100% 1.06k/1.06k [00:00<00:00, 6.04MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1dh-wTzw-pyRlbpX0nKG17cBhndsFfbzt
From (redirected): https://drive.google.com/uc?id=1dh-wTzw-pyRlbpX0nKG17cBhndsFfbzt&confirm=t&uuid=43e90c0f-f0f4-48e8-a6ab-06be67a21fc9
To: /content/author_models/electra-logic/pytorch_model.bin
100% 438M/438M [00:08<00:00, 52.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_ErzN3iBRNvK70CNS0K2v85JKMAMLzyR
To: /content/author_models/electra-logic-structaware/config.json
100% 1.06k/1.06k [00:00<00:00, 5.71MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1V4lDQGKGazPlCkDE8ZOYNYclnFKTzFhu
From (redirected): https://drive.google.com/uc?id=1V4lDQGKGazPlCkDE8ZOYNYclnFKTzFhu&confirm=t&uuid=73e01fa1-3e43-41a5-b2c2-3bd24eed790c
To: /content/author_models/electra-logic-structaware/pytorch_model.bin
100% 438M/438M [00:09<00:00, 47.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1r_VKrq52QaDgnr9aZ8mqEkmI8x-3lmKe
To: /content/author_models/electra-logicclimate/config.json
100% 1.06k/1.06k [00:00<00:00, 6.26MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1mlmNNk8l1zGHeHw_KNU3jSA2TC453P79
From (redirected): https://drive.google.com/uc?id=1mlmNNk8l1zGHeHw_KNU3jSA2TC453P79&confirm=t&uuid=50e4ed1f-9002-435c-988c-9b48e4284041
To: /content/author_models/electra-logicclimate/pytorch_model.bin
100% 438M/438M [00:09<00:00, 45.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Gub_Jx4Ipk_GjT-Hpww8WQZxh4CmXkDC
To: /content/author_models/electra-logicclimate-structaware/config.json
100% 1.07k/1.07k [00:00<00:00, 6.34MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=18kJ7zQ_0wiuVVPyxwZIP7hD9kh--iJ54
From (redirected): https://drive.google.com/uc?id=18kJ7zQ_0wiuVVPyxwZIP7hD9kh--iJ54&confirm=t&uuid=b80fbb67-2c5e-4395-9737-b96c877dc191
To: /content/author_models/electra-logicclimate-structaware/pytorch_model.bin
100% 438M/438M [00:11<00:00, 38.0MB/s]
Download completed

In [32]:

import os
import shutil

source = "/content/author_models/electra-logic-structaware"
destination = "/content/drive/MyDrive/FallacyLens/pretrained_model"

os.makedirs(destination, exist_ok=True)

for filename in ["config.json", "pytorch_model.bin"]:
    src = os.path.join(source, filename)
    dst = os.path.join(destination, filename)

    if not os.path.exists(src):
        raise FileNotFoundError(f"Missing file: {src}")

    shutil.copy2(src, dst)
    print(f"Copied: {filename}")

print("\nVerification:")
for filename in ["config.json", "pytorch_model.bin"]:
    path = os.path.join(destination, filename)
    print(filename, "-", round(os.path.getsize(path) / (1024**2), 2), "MB")

print("\nPretrained model saved to:", destination)

Copied: config.json
Copied: pytorch_model.bin

Verification:
config.json - 0.0 MB
pytorch_model.bin - 417.76 MB

Pretrained model saved to: /content/drive/MyDrive/FallacyLens/pretrained_model

In [33]:

%cd /content/logical-fallacy

!pip install -q transformers==4.44.2 gdown scikit-learn pandas numpy

/content/logical-fallacy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error

  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> No available output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tokenizers (pyproject.toml) ... error
  ERROR: Failed building wheel for tokenizers
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> tokenizers

In [34]:

%pip install -q --upgrade pip
%pip install -q transformers==4.44.2 tokenizers==0.19.1 --only-binary=:all:

ERROR: Ignored the following yanked versions: 0.20.4
ERROR: Could not find a version that satisfies the requirement tokenizers==0.19.1 (from versions: 0.15.1, 0.15.2, 0.20.2, 0.20.3, 0.20.4rc0, 0.21.0rc0, 0.21.0, 0.21.1rc0, 0.21.1, 0.21.2rc0, 0.21.2, 0.21.4, 0.22.0, 0.22.1rc0, 0.22.1, 0.22.2rc0, 0.22.2, 0.23.0rc0, 0.23.1rc0, 0.23.1, 0.23.2, 0.23.3, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3)
ERROR: No matching distribution found for tokenizers==0.19.1

In [35]:

import sys
import torch
import transformers
import tokenizers

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Tokenizers:", tokenizers.__version__)
print("GPU available:", torch.cuda.is_available())

Python: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
PyTorch: 2.11.0+cu130
Transformers: 5.22.0
Tokenizers: 0.23.3
GPU available: True

In [36]:

import os
from transformers import AutoModelForSequenceClassification

model_path = "/content/drive/MyDrive/FallacyLens/pretrained_model"

print("Config exists:",
      os.path.exists(os.path.join(model_path, "config.json")))
print("Weights exist:",
      os.path.exists(os.path.join(model_path, "pytorch_model.bin")))

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

print("\nModel loaded successfully!")
print("Model type:", type(model).__name__)
print("Number of output labels:", model.config.num_labels)
print("GPU available:", __import__("torch").cuda.is_available())

Config exists: True
Weights exist: True

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Model loaded successfully!
Model type: ElectraForSequenceClassification
Number of output labels: 3
GPU available: True

In [37]:

import os
import pandas as pd
from transformers import AutoTokenizer

repo_path = "/content/logical-fallacy"
code_dir = os.path.join(
    repo_path, "codes_for_models", "experiments_round2"
)
data_dir = os.path.join(repo_path, "data")

os.chdir(code_dir)

tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator"
)
tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

train_df = pd.read_csv("../../data/edu_train.csv")
dev_df = pd.read_csv("../../data/edu_dev.csv")
test_df = pd.read_csv("../../data/edu_test.csv")

print("Tokenizer vocabulary:", len(tokenizer))
print("Training rows:", len(train_df))
print("Validation rows:", len(dev_df))
print("Test rows:", len(test_df))
print("Training labels:", train_df["updated_label"].nunique())
print("Working directory:", os.getcwd())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizer vocabulary: 30531
Training rows: 1849
Validation rows: 300
Test rows: 300
Training labels: 13
Working directory: /content/logical-fallacy/codes_for_models/experiments_round2

In [38]:

import os
import sys

code_dir = "/content/logical-fallacy/codes_for_models/experiments_round2"
os.chdir(code_dir)

# Fix the AdamW import for modern PyTorch/Transformers.
script_path = os.path.join(code_dir, "logicedu.py")

with open(script_path, "r", encoding="utf-8") as f:
    source = f.read()

source = source.replace(
    "from transformers import AutoTokenizer, AdamW, AutoModelForSequenceClassification",
    "from transformers import AutoTokenizer, AutoModelForSequenceClassification\nfrom torch.optim import AdamW"
)

with open(script_path, "w", encoding="utf-8") as f:
    f.write(source)

import logicedu

print("Research training script imported successfully.")
print("Training function available:", callable(logicedu.train))
print("Preprocessing class available:", hasattr(logicedu, "MNLIDataset"))

Research training script imported successfully.
Training function available: True
Preprocessing class available: True

In [39]:

import os
import torch
import pandas as pd
import logicedu
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.optim import AdamW

code_dir = "/content/logical-fallacy/codes_for_models/experiments_round2"
os.chdir(code_dir)

# Load original research dataset splits
train_df = pd.read_csv("../../data/edu_train.csv")
dev_df = pd.read_csv("../../data/edu_dev.csv")
test_df = pd.read_csv("../../data/edu_test.csv")

# Load tokenizer and research-specific special tokens
tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator"
)
tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

# Rebuild original NLI dataset
fallacy_ds = logicedu.MNLIDataset(
    tokenizer_path="google/electra-base-discriminator",
    train_df=train_df,
    val_df=dev_df,
    label_col_name="updated_label",
    map="base",
    test_df=test_df,
    fallacy=True,
    train_strat=1,
    test_strat=1
)

# Load the authors' pretrained checkpoint from Drive
model_path = "/content/drive/MyDrive/FallacyLens/pretrained_model"
model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

# Match model embeddings to the tokenizer vocabulary
model.resize_token_embeddings(len(tokenizer))

print("\nDataset rebuilt successfully.")
print("Training NLI examples:", len(fallacy_ds.train_data))
print("Validation NLI examples:", len(fallacy_ds.val_data))
print("Test NLI examples:", len(fallacy_ds.test_data))
print("Tokenizer vocabulary:", len(tokenizer))
print("Model embedding vocabulary:",
      model.get_input_embeddings().num_embeddings)
print("Output classes:", model.config.num_labels)
print("GPU available:", torch.cuda.is_available())

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Dataset rebuilt successfully.
Training NLI examples: 24037
Validation NLI examples: 3900
Test NLI examples: 3900
Tokenizer vocabulary: 30531
Model embedding vocabulary: 30531
Output classes: 3
GPU available: True

In [41]:

import os
import torch
from torch.optim import AdamW

# Permanent save location in Google Drive
save_path = "/content/drive/MyDrive/FallacyLens/trained_model"
os.makedirs(save_path, exist_ok=True)

# Use GPU when available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

print("Starting FallacyLens training...")
print("Device:", device)
print("Checkpoint folder:", save_path)

logicedu.train(
    model=model,
    dataset=fallacy_ds,
    optimizer=optimizer,
    logger=None,
    save_path=save_path,
    device=device,
    epochs=3,
    ratio=0.04,
    positive_weight=12,
    debug=False
)

print("Training process finished.")
print("Saved folder contents:", os.listdir(save_path))

Starting FallacyLens training...
Device: cuda
Checkpoint folder: /content/drive/MyDrive/FallacyLens/trained_model

AttributeError: 'NoneType' object has no attribute 'debug'

In [42]:

import logging

logger = logging.getLogger("FallacyLens")
logger.setLevel(logging.DEBUG)

# Avoid adding duplicate handlers if you rerun this cell
if not logger.handlers:
    handler = logging.StreamHandler()
    handler.setLevel(logging.DEBUG)
    logger.addHandler(handler)

print("Logger configured successfully.")

Logger configured successfully.

In [43]:

import os
import torch
from torch.optim import AdamW

save_path = "/content/drive/MyDrive/FallacyLens/trained_model"
os.makedirs(save_path, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
optimizer = AdamW(model.parameters(), lr=2e-5)

print("Starting FallacyLens training...")
print("Device:", device)
print("Saving to:", save_path)

logicedu.train(
    model=model,
    dataset=fallacy_ds,
    optimizer=optimizer,
    logger=logger,
    save_path=save_path,
    device=device,
    epochs=3,
    ratio=0.04,
    positive_weight=12,
    debug=False
)

print("Training finished.")
print("Saved files:", os.listdir(save_path))

Starting FallacyLens training...
Device: cuda
Saving to: /content/drive/MyDrive/FallacyLens/trained_model

0 0
DEBUG:FallacyLens:0 0
0 10
DEBUG:FallacyLens:0 10
0 20
DEBUG:FallacyLens:0 20
0 30
DEBUG:FallacyLens:0 30
0 40
DEBUG:FallacyLens:0 40
0 50
DEBUG:FallacyLens:0 50
0 60
DEBUG:FallacyLens:0 60
0 70
DEBUG:FallacyLens:0 70
0 80
DEBUG:FallacyLens:0 80
saving model
INFO:FallacyLens:saving model

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1: train_loss: 2.0256 train_acc: 0.6741 train_prec: 0.6801 train_rec: 0.9840| val_loss: 3.5946 val_acc: 0.0977 val_prec: 0.0787 val_rec: 0.9180
INFO:FallacyLens:Epoch 1: train_loss: 2.0256 train_acc: 0.6741 train_prec: 0.6801 train_rec: 0.9840| val_loss: 3.5946 val_acc: 0.0977 val_prec: 0.0787 val_rec: 0.9180
00:02:46.94
INFO:FallacyLens:00:02:46.94
1 0
DEBUG:FallacyLens:1 0
1 10
DEBUG:FallacyLens:1 10
1 20
DEBUG:FallacyLens:1 20
1 30
DEBUG:FallacyLens:1 30
1 40
DEBUG:FallacyLens:1 40
1 50
DEBUG:FallacyLens:1 50
1 60
DEBUG:FallacyLens:1 60
1 70
DEBUG:FallacyLens:1 70
1 80
DEBUG:FallacyLens:1 80
saving model
INFO:FallacyLens:saving model

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 2: train_loss: 1.3974 train_acc: 0.7053 train_prec: 0.6977 train_rec: 0.9983| val_loss: 2.3860 val_acc: 0.3188 val_prec: 0.1009 val_rec: 0.9406
INFO:FallacyLens:Epoch 2: train_loss: 1.3974 train_acc: 0.7053 train_prec: 0.6977 train_rec: 0.9983| val_loss: 2.3860 val_acc: 0.3188 val_prec: 0.1009 val_rec: 0.9406
00:02:57.62
INFO:FallacyLens:00:02:57.62
2 0
DEBUG:FallacyLens:2 0
2 10
DEBUG:FallacyLens:2 10
2 20
DEBUG:FallacyLens:2 20
2 30
DEBUG:FallacyLens:2 30
2 40
DEBUG:FallacyLens:2 40
2 50
DEBUG:FallacyLens:2 50
2 60
DEBUG:FallacyLens:2 60
2 70
DEBUG:FallacyLens:2 70
2 80
DEBUG:FallacyLens:2 80
saving model
INFO:FallacyLens:saving model

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 3: train_loss: 1.1158 train_acc: 0.7769 train_prec: 0.7563 train_rec: 0.9932| val_loss: 2.1146 val_acc: 0.4443 val_prec: 0.1207 val_rec: 0.9247
INFO:FallacyLens:Epoch 3: train_loss: 1.1158 train_acc: 0.7769 train_prec: 0.7563 train_rec: 0.9932| val_loss: 2.1146 val_acc: 0.4443 val_prec: 0.1207 val_rec: 0.9247
00:02:58.45
INFO:FallacyLens:00:02:58.45

Training finished.
Saved files: ['config.json', 'model.safetensors']

In [44]:

from transformers import AutoModelForSequenceClassification
import os

model_path = "/content/drive/MyDrive/FallacyLens/trained_model"

print("Files:", os.listdir(model_path))

trained_model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

print("Trained model loaded successfully!")
print("Output classes:", trained_model.config.num_labels)

Files: ['config.json', 'model.safetensors']

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Trained model loaded successfully!
Output classes: 3

In [45]:

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

model_path = "/content/drive/MyDrive/FallacyLens/trained_model"

tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator"
)

tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

trained_model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
)

trained_model.resize_token_embeddings(len(tokenizer))
trained_model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
trained_model.to(device)

print("Tokenizer vocabulary:", len(tokenizer))
print("Model embedding vocabulary:",
      trained_model.get_input_embeddings().num_embeddings)
print("Model device:", device)
print("Ready for evaluation!")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Tokenizer vocabulary: 30531
Model embedding vocabulary: 30531
Model device: cuda
Ready for evaluation!

In [46]:

import os
import pandas as pd

repo_path = "/content/logical-fallacy"
test_path = os.path.join(repo_path, "data", "edu_test.csv")

test_df = pd.read_csv(test_path)

print("Test dataset loaded!")
print("Number of test statements:", len(test_df))
print("Columns:", test_df.columns.tolist())
print("\nFallacy categories:", test_df["updated_label"].nunique())
print("\nExamples:")
display(test_df[["source_article", "updated_label"]].head())

Test dataset loaded!
Number of test statements: 300
Columns: ['Unnamed: 0.2', 'Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1', 'Unnamed: 0.1.1.1.1', 'Unnamed: 0.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1.1.1', 'source_article', 'updated_label', 'masked_articles']

Fallacy categories: 13

Examples:

                                      source_article          updated_label
0  People who drive big cars probably hate the en...   fallacy of extension
1      White men can't jump. No, really, they can't!  faulty generalization
2  'Cotton and grain crops were lower this year t...       fallacy of logic
3  "Why are you hitting your computer!?"\n"The la...        false causality
4      All students are good and all clowns are bad.  faulty generalization

In [47]:

import os
import pandas as pd

mapping_path = "/content/logical-fallacy/data/mappings.csv"

mapping_df = pd.read_csv(mapping_path)

print("Mapping columns:", mapping_df.columns.tolist())
display(mapping_df.head(20))

Mapping columns: ['Original Name', 'Understandable Name', 'Description', 'Logical Form', 'Source for Logical Form ', 'Masked Logical Form']

,Original Name,Understandable Name,Description,Logical Form,Source for Logical Form,Masked Logical Form
0,faulty generalization,faulty generalization,an informal fallacy wherein a conclusion is dr...,Sample S is taken from population P. Sample S ...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is taken from <MSK2>. <MSK1> is a very ...
1,false causality,false causality,statement that jumps to a conclusion implying ...,"A occurred, then B occurred.\nTherefore, A cau...",https://en.wikipedia.org/wiki/Post_hoc_ergo_pr...,"<MSK1> occurred, then <MSK2> occurred.\nTheref..."
2,circular reasoning,circular reasoning,when the end of an argument comes back to the ...,X is true because of Y.\n\nY is true because o...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is true because of <MSK2>.\n\n<MSK2> is...
3,ad populum,appeal to popularity,a fallacious argument which is based on affirm...,"A lot of people believe X.Therefore, X must be...",https://www.logicallyfallacious.com/logicalfal...,"A lot of people believe <MSK1>.Therefore, <MSK..."
4,ad hominem,personal attack,instead of addressing someone's argument or p...,Person 1 is claiming Y.\n\nPerson 1 is a moron...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is claiming <MSK2>.\n\n<MSK1> is a moro...
5,fallacy of logic,logical error,an error in the logical structure of an argument.,"If A is true, then B is true. B is true. There...",https://en.wikipedia.org/wiki/Formal_fallacy,"If <MSK1> is true, then <MSK2> is true.<MSK2> ..."
6,appeal to emotion,appeal to emotion,manipulation of the recipient's emotions in or...,Claim X is made without evidence. In place of ...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is made without evidence. In place of e...
7,false dilemma,excluding viable alternatives,presenting only two options or sides when ther...,Either X or Y is true.,https://www.logicallyfallacious.com/logicalfal...,Either <MSK1> or <MSK2> is true.
8,equivocation,use of ambiguous language,when a key term or phrase in an argument is us...,Term X is used to mean Y in the premise.\nTerm...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> is used to mean <MSK2> in the premise.\...
9,fallacy of extension,exaggerating,attacking an exaggerated or caricatured versio...,Person 1 makes claim Y. Person 2 restates pers...,https://www.logicallyfallacious.com/logicalfal...,<MSK1> makes claim <MSK2>. <MSK3> restates <MS...
10,fallacy of relevance,irrelevant argument,introducing premises or conclusions that have ...,"It is claimed that X implies Y, whereas X is u...",Self,"It is claimed that <MSK1> implies <MSK2>, wher..."
11,fallacy of credibility,attacking the character of the speaker,attempts to disprove an argument by attacking ...,Person 1 makes claim Y. Person 2 claims Person...,Self,<MSK1> makes <MSK2>. <MSK3> claims <MSK1> is n...
12,miscellaneous,miscellaneous,miscellaneous,miscellaneous,NaN,miscellaneous
13,intentional,intentionally wrong argument,some intentional (sometimes subconscious) acti...,Person 1 knows claim X is incorrect. They stil...,NaN,<MSK1> knows <MSK2> is incorrect. They still c...

In [48]:

import torch
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report

# Use the categories represented in the training data
fallacy_labels = sorted(train_df["updated_label"].unique())

print("Number of fallacy categories:", len(fallacy_labels))
print("Categories:", fallacy_labels)

# Keep only the needed test columns
evaluation_df = test_df[["source_article", "updated_label"]].dropna().copy()

def predict_fallacy(text, batch_size=13):
    hypotheses = [
        f"This is an example of {label} logical fallacy"
        for label in fallacy_labels
    ]

    inputs = tokenizer(
        [text] * len(hypotheses),
        hypotheses,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt"
    )

    inputs = {key: value.to(device) for key, value in inputs.items()}

    with torch.no_grad():
        logits = trained_model(**inputs).logits
        probabilities = torch.softmax(logits, dim=-1)

    # Research label mapping: entailment=0, contradiction=1, neutral=2
    entailment_scores = probabilities[:, 0]
    best_index = torch.argmax(entailment_scores).item()

    return fallacy_labels[best_index], float(entailment_scores[best_index])

predictions = []
scores = []

for text in evaluation_df["source_article"]:
    prediction, score = predict_fallacy(str(text))
    predictions.append(prediction)
    scores.append(score)

evaluation_df["predicted_label"] = predictions
evaluation_df["entailment_score"] = scores

accuracy = accuracy_score(
    evaluation_df["updated_label"],
    evaluation_df["predicted_label"]
)

print(f"\nTest accuracy: {accuracy:.2%}")
print("\nClassification report:")
print(classification_report(
    evaluation_df["updated_label"],
    evaluation_df["predicted_label"],
    labels=fallacy_labels,
    zero_division=0
))

display(evaluation_df[
    ["source_article", "updated_label", "predicted_label", "entailment_score"]
].head(10))

Number of fallacy categories: 13
Categories: ['ad hominem', 'ad populum', 'appeal to emotion', 'circular reasoning', 'equivocation', 'fallacy of credibility', 'fallacy of extension', 'fallacy of logic', 'fallacy of relevance', 'false causality', 'false dilemma', 'faulty generalization', 'intentional']

Test accuracy: 51.00%

Classification report:
                        precision    recall  f1-score   support

            ad hominem       0.63      0.83      0.72        41
            ad populum       0.83      0.80      0.81        30
     appeal to emotion       0.64      0.30      0.41        23
    circular reasoning       0.53      0.47      0.50        19
          equivocation       0.00      0.00      0.00         5
fallacy of credibility       0.62      0.29      0.40        17
  fallacy of extension       0.00      0.00      0.00        21
      fallacy of logic       0.15      0.29      0.20        14
  fallacy of relevance       0.56      0.21      0.30        24
       false causality       0.58      0.61      0.59        18
         false dilemma       0.60      1.00      0.75        12
 faulty generalization       0.40      0.67      0.50        61
           intentional       0.20      0.07      0.10        15

              accuracy                           0.51       300
             macro avg       0.44      0.43      0.41       300
          weighted avg       0.49      0.51      0.47       300

,source_article,updated_label,predicted_label,entailment_score
0,People who drive big cars probably hate the en...,fallacy of extension,ad hominem,0.998030
1,"White men can't jump. No, really, they can't!",faulty generalization,faulty generalization,0.995158
2,'Cotton and grain crops were lower this year t...,fallacy of logic,faulty generalization,0.990333
3,"""Why are you hitting your computer!?""\n""The la...",false causality,false causality,0.998416
4,All students are good and all clowns are bad.,faulty generalization,faulty generalization,0.996264
5,"""People who don't support the proposed state m...",fallacy of extension,ad hominem,0.996595
6,Charlie: Illegal posting and sharing of songs ...,fallacy of extension,fallacy of relevance,0.991680
7,Paige wants to play a guitar solo on our next ...,faulty generalization,ad hominem,0.998175
8,"My sister-in-law, who is a teacher, said that ...",fallacy of credibility,fallacy of credibility,0.997550
9,something that kills is deadly,circular reasoning,faulty generalization,0.996282

In [49]:

import os

code_dir = "/content/logical-fallacy/codes_for_models/experiments_round2"
script_path = os.path.join(code_dir, "logicedu.py")

with open(script_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for i, line in enumerate(lines):
    if any(term in line.lower() for term in [
        "def eval1", "def evaluate", "def test", "def predict",
        "def convert_to_mnli", "def load_data"
    ]):
        start = max(0, i - 2)
        end = min(len(lines), i + 35)
        print(f"\n--- Lines {start + 1}-{end} ---")
        print("".join(lines[start:end]))

--- Lines 79-115 ---
                       undersample_ratio=undersample_rate, train_strat=train_strat, test_strat=test_strat)

    def convert_to_mnli(self, df, undersample=False, undersampling_rate=0.02, strat=1):
        """
        strat=1 -> only original article
        strat=2 -> only masked article
        strat=3 -> both
        """
        data = []
        for i, row in df.iterrows():
            for label in self.unique_labels:
                entry = [row['source_article']]
                if self.map == 'base':
                    entry.append("This is an example of %s logical fallacy" % label)
                elif self.map == 'simplify':
                    simplified_label = \
                        list(self.mappings[self.mappings['Original Name'] == label]['Understandable Name'])[0]
                    entry.append("This is an example of %s" % simplified_label)
                elif self.map == 'description':
                    description = list(self.mappings[self.mappings['Original Name'] == label]['Description'])[0]
                    entry.append("This is an example of %s" % description)
                elif self.map == 'logical-form':
                    form = list(self.mappings[self.mappings['Original Name'] == label]['Logical Form'])[0]
                    entry.append("This article matches the following logical form: %s" % form)
                elif self.map == 'masked-logical-form':
                    # print(self.mappings[self.mappings['Original Name'] == label]['Masked Logical Form'])
                    form = replace_masked_tokens(list(self.mappings[self.mappings['Original Name'] == label]
                                                      ['Masked Logical Form'])[0])
                    entry.append("This article matches the following logical form: %s" % form)
                if (self.multilabel is False and label == row[self.label_col_name]) or (
                        self.multilabel is True and label in row[self.label_col_name]):
                    entry.append("entailment")
                else:
                    p = random.random()
                    if undersample and p > undersampling_rate:
                        continue
                    entry.append("contradiction")


--- Lines 144-180 ---
        self.test_data = self.load_data(self.test_df)

    def load_data(self, df):
        if df is None:
            return None

        MAX_LEN = 512
        token_ids = []
        mask_ids = []
        seg_ids = []
        y = []
        weights = []

        df = df.dropna()

        premise_list = df['sentence1'].to_list()
        hypothesis_list = df['sentence2'].to_list()
        label_list = df['gold_label'].to_list()
        weight_list = df['weight'].to_list()

        for (premise, hypothesis, label, weight) in zip(premise_list, hypothesis_list, label_list, weight_list):

            premise_id = self.tokenizer.encode(premise, add_special_tokens=False)
            hypothesis_id = self.tokenizer.encode(hypothesis, add_special_tokens=False)
            pair_token_ids = [self.tokenizer.cls_token_id] + premise_id + [
                self.tokenizer.sep_token_id] + hypothesis_id + [self.tokenizer.sep_token_id]
            # pair_token_ids = premise_id + hypothesis_id
            # print("max token id=", max(pair_token_ids))
            premise_len = len(premise_id)
            hypothesis_len = len(hypothesis_id)

            segment_ids = torch.tensor(
                [0] * (premise_len + 2) + [1] * (hypothesis_len + 1))  # sentence 0 and sentence 1
            attention_mask_ids = torch.tensor([1] * (premise_len + hypothesis_len + 3))  # mask padded values
            if len(pair_token_ids) > MAX_LEN or len(segment_ids) > MAX_LEN or len(attention_mask_ids) > MAX_LEN:
                continue
            token_ids.append(torch.tensor(pair_token_ids))


--- Lines 403-439 ---


def eval1(model, test_loader, logger, device):
    with torch.no_grad():
        all_preds = []
        all_labels = []
        for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(test_loader):
            logger.debug("%d", batch_idx)
            pair_token_ids = pair_token_ids.to(device)
            mask_ids = mask_ids.to(device)
            seg_ids = seg_ids.to(device)
            labels = y.to(device)
            if model == "random":
                prediction = torch.rand([15, 3])
            else:
                _, prediction = model(pair_token_ids,
                                      token_type_ids=seg_ids,
                                      attention_mask=mask_ids,
                                      labels=labels).values()
            all_preds.append(torch.log_softmax(prediction, dim=1).argmax(dim=1))
            all_labels.append(labels)
        all_preds = 1 - torch.stack(all_preds)
        all_labels = 1 - torch.stack(all_labels)
        all_preds[all_preds < 0] = 0
        all_labels[all_labels < 0] = 0
        return get_metrics(all_preds, all_labels, sig=False)


if __name__ == "__main__":
    if torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"
    logger = get_logger()
    logger.info("device = %s", device)
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", "--tokenizer", help="tokenizer path")

In [50]:

import os

script_path = (
    "/content/logical-fallacy/"
    "codes_for_models/experiments_round2/logicedu.py"
)

with open(script_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Print the dataset initialization and training configuration
for start, end in [(20, 80), (180, 280), (439, 520)]:
    print(f"\n{'=' * 15} Lines {start + 1}-{min(end, len(lines))} {'=' * 15}")
    print("".join(lines[start:min(end, len(lines))]))

=============== Lines 21-80 ===============
torch.manual_seed(0)


def get_unique_labels(df, label_col_name, multilabel=False):
    labels_dict = {}
    if multilabel:
        for labels in df[label_col_name]:
            for label in labels:
                if label not in labels_dict.keys():
                    labels_dict[label] = 0
                labels_dict[label] += 1
    else:
        candidate_labels = df[label_col_name].unique()
        for label in candidate_labels:
            labels = label.split(';')
            if len(labels) > 1:
                print(labels)
            labels = [x.strip() for x in labels]
            for lbl in labels:
                if lbl not in labels_dict.keys():
                    labels_dict[lbl] = 0
                labels_dict[lbl] += 1
    return list(labels_dict.keys()), labels_dict


def replace_random_sample(i):
    return sample(word_bank, 1)[0]


class MNLIDataset:

    def __init__(self, tokenizer_path, train_df, val_df, label_col_name, map='base', test_df=None, fallacy=False,
                 undersample_train=False, undersample_val=False, undersample_test=False, undersample_rate=0.04,
                 train_strat=1, test_strat=1, multilabel=False):
        # strat is used in convert_to_mnli function
        self.label_dict = {'entailment': 0, 'contradiction': 1, 'neutral': 2}
        torch.manual_seed(0)
        self.train_df = train_df
        self.val_df = val_df
        self.test_df = test_df
        self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, do_lower_case=True)
        special_tokens_dict = {
            'additional_special_tokens': ["[A]", "[B]", "[C]", "[D]", "[E]", "[F]", "[G]", "[H]", "[I]"]}
        self.tokenizer.add_special_tokens(special_tokens_dict)
        self.train_data = None
        self.val_data = None
        self.label_col_name = label_col_name
        self.map = map
        self.mappings = pd.read_csv("../../data/mappings.csv")
        self.multilabel = multilabel
        if fallacy:
            self.unique_labels, self.counts_dict = get_unique_labels(pd.concat([train_df, val_df, test_df]),
                                                                     self.label_col_name,
                                                                     multilabel)
            self.total_count = 0
            for count in self.counts_dict.values():
                self.total_count += count
        self.init_data(fallacy, undersample_train, undersample_val, undersample_test,
                       undersample_ratio=undersample_rate, train_strat=train_strat, test_strat=test_strat)



=============== Lines 181-280 ===============
            seg_ids.append(segment_ids)
            mask_ids.append(attention_mask_ids)
            y.append(self.label_dict[label])
            weights.append(weight)

        token_ids = pad_sequence(token_ids, batch_first=True)
        mask_ids = pad_sequence(mask_ids, batch_first=True)
        seg_ids = pad_sequence(seg_ids, batch_first=True)
        y = torch.tensor(y)
        # print(token_ids.shape)
        # print(torch.tensor(weights).shape)
        dataset = TensorDataset(token_ids, mask_ids, seg_ids, y, torch.tensor(weights))
        # print(len(dataset))
        return dataset

    def get_undersampled(self, ratio=0.04, batch_size=32, shuffle=True):
        train_df_entail = self.train_df[self.train_df.gold_label == 'entailment']
        train_df_contradict = self.train_df[self.train_df.gold_label == 'contradiction']
        train_df_contradict = train_df_contradict.sample(n=int(len(train_df_contradict) * ratio))
        df = pd.concat([train_df_contradict, train_df_entail])
        df = self.load_data(df)
        return DataLoader(
            df,
            shuffle=shuffle,
            batch_size=batch_size
        )

    def get_data_loaders(self, batch_size=32, shuffle=True):
        train_loader = DataLoader(
            self.train_data,
            shuffle=shuffle,
            batch_size=batch_size
        )

        val_loader = DataLoader(
            self.val_data,
            shuffle=shuffle,
            batch_size=batch_size
        )
        if self.test_data:
            test_loader = DataLoader(
                self.test_data,
                shuffle=False,
                batch_size=len(self.unique_labels)
            )
        else:
            test_loader = None

        return train_loader, val_loader, test_loader


def get_logger(level='DEBUG'):
    logger = logging.getLogger()
    logger.handlers = []
    file_log_handler = logging.FileHandler('logfile.log')
    logger.addHandler(file_log_handler)
    stderr_log_handler = logging.StreamHandler()
    logger.addHandler(stderr_log_handler)
    logger.setLevel(level)
    return logger


def multi_acc(y_pred, y_test, flip=True):
    preds = torch.log_softmax(y_pred, dim=1).argmax(dim=1)
    acc = (preds == y_test).sum().float() / float(y_test.size(0))
    if flip:
        y_pred = 1 - preds.cpu()
        y_test = 1 - y_test.cpu()
    else:
        y_pred = preds.cpu()
        y_test = y_test.cpu()
    TP = 0
    FP = 0
    TN = 0
    FN = 0
    for i in range(len(y_pred)):
        if y_test[i] == y_pred[i] == 1:
            TP += 1
        if y_pred[i] == 1 and y_test[i] != y_pred[i]:
            FP += 1
        if y_test[i] == y_pred[i] == 0:
            TN += 1
        if y_pred[i] == 0 and y_test[i] != y_pred[i]:
            FN += 1
    if TP == 0:
        return acc, 0, 0
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    return acc, precision, recall


import time


def get_metrics(logits, labels, threshold=0.5, sig=True, tensors=True):
    if sig:
        sig = nn.Sigmoid()
        preds = sig(logits)
        preds = (preds > threshold)
    else:


=============== Lines 440-520 ===============
    parser.add_argument("-m", "--model", help="model path")
    parser.add_argument("-w", "--weight", help="Weight of entailment loss")
    parser.add_argument("-s", "--savepath", help="Path to save logicedu model")
    parser.add_argument("-f", "--finetune", help="Set this flag if you want to finetune the model on MNLI", default='F')
    parser.add_argument("-sf", "--savepath2", help="Path to save mnli model", default="mnli")
    parser.add_argument("-mp", "--map", help="Map labels to this category")
    parser.add_argument("-ts", "--train_strat", help="Strategy number for training")
    parser.add_argument("-ds", "--dev_strat", help="Strategy number for development and testing")
    parser.add_argument("-rs", "--replace_strat", help="Function used to replace masked words", default='char')
    parser.add_argument("-rc", "--replace_count", help="Number of times to replace masked words", default=1)
    parser.add_argument("-np", "--multinli_path", help="Path for multinli directory", default="")
    parser.add_argument("-do", "--downsample", help="Downsample Training Set", default='F')
    parser.add_argument("-c", "--classwise_savepath", help="Path to store classwise results")
    parser.add_argument("-sr", "--result_path", help="Path to store results on dev set")
    parser.add_argument("-nt", "--do_not_train", help="Set this to T if you do not wish to train the model",
                        default='F')
    args = parser.parse_args()
    # word_bank = pickle.load('../../data/word_bank.pkl')
    logger.info(args)
    logger.info("initializing model")
    model = AutoModelForSequenceClassification.from_pretrained(args.model, num_labels=3)
    model.to(device)

    if args.finetune == 'T':
        logger.info("initializing mnli dataset")
        mnli_train = pd.read_csv(args.multinli_path + "/multinli_1.0_train.txt", sep='\t',
                                 skiprows=[24809, 33960, 75910, 100113, 150637, 158833, 173103, 178251, 221950, 286844,
                                           314109])[['gold_label', 'sentence1', 'sentence2']]
        mnli_train = mnli_train.dropna()
        mnli_dev_matched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_matched.txt", sep='\t')[
            ['gold_label', 'sentence1', 'sentence2']]
        mnli_dev_mismatched = pd.read_csv(args.multinli_path + "/multinli_1.0_dev_mismatched.txt", sep='\t')[
            ['gold_label', 'sentence1', 'sentence2']]
        mnli_dev = pd.concat([mnli_dev_matched, mnli_dev_mismatched], ignore_index=True, sort=False)
        mnli_dev = mnli_dev.dropna()
        mnli_dev = mnli_dev[mnli_dev.gold_label != '-']
        mnli_ds = MNLIDataset(args.tokenizer, mnli_train, mnli_dev, 'gold_label', fallacy=False)
        logger.info("finetune on mnli")
        optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
        train(model, mnli_ds, optimizer, logger, args.savepath2, ratio=1, epochs=10, positive_weight=1)
        logger.info("reinit model")
        model = AutoModelForSequenceClassification.from_pretrained(args.savepath2)
        model.to(device)
    optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
    logger.info("creating dataset")
    fallacy_train = pd.read_csv('../../data/edu_train.csv')
    if args.downsample == 'T':
        fallacy_train = fallacy_train[:747]
    fallacy_dev = pd.read_csv('../../data/edu_dev.csv')
    fallacy_test = pd.read_csv('../../data/edu_test.csv')
    fallacy_ds = MNLIDataset(args.tokenizer, fallacy_train, fallacy_dev, 'updated_label', args.map, fallacy_test,
                             fallacy=True, train_strat=int(args.train_strat), test_strat=int(args.dev_strat))
    model.resize_token_embeddings(len(fallacy_ds.tokenizer))
    fallacy_ds.train_df.to_csv('processed_train_df.csv')
    fallacy_ds.val_df.to_csv('processed_val_df.csv')
    # print(fallacy_ds.tokenizer.tokenize("[A] causes [B]"))
    # print("checking length", len(fallacy_ds.tokenizer), model.config.vocab_size)
    if args.do_not_train == 'F':
        optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
        logger.info("starting training")
        train(model, fallacy_ds, optimizer, logger, args.savepath, device, ratio=1, epochs=10,
              positive_weight=int(args.weight))

        model = AutoModelForSequenceClassification.from_pretrained(args.savepath, num_labels=3)
        model.to(device)
    logger.info("starting testing")
    _, _, test_loader = fallacy_ds.get_data_loaders()
    scores = eval1(model, test_loader, logger, device)
    logger.info("micro f1: %f macro f1:%f precision: %f recall: %f exact match %f", scores[4], scores[5], scores[1],
                scores[2], scores[3])
    if args.classwise_savepath is not None:
        classwise_scores = eval_classwise(model, test_loader, logger, fallacy_ds.unique_labels, device)
        df = pd.DataFrame.from_records(classwise_scores, columns=['Fallacy Name', 'Precision', 'Recall', 'F1',
                                                                  'Number of Positive Labels for this Class in Test Set'
                                                                  ])
        df.to_csv(args.classwise_savepath)
    if args.result_path is not None:
        logger.info("Generating results on Dev Set")
        df = eval_and_store(fallacy_ds, model, logger, device, args.map)
        df = convert_to_multilabel(df)
        df.to_csv(args.result_path)

In [51]:

script_path = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(script_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for start, end in [(150, 185), (280, 405), (400, 440)]:
    print(f"\n{'=' * 12} Lines {start + 1}-{end} {'=' * 12}")
    print("".join(lines[start:end]))

============ Lines 151-185 ============
        token_ids = []
        mask_ids = []
        seg_ids = []
        y = []
        weights = []

        df = df.dropna()

        premise_list = df['sentence1'].to_list()
        hypothesis_list = df['sentence2'].to_list()
        label_list = df['gold_label'].to_list()
        weight_list = df['weight'].to_list()

        for (premise, hypothesis, label, weight) in zip(premise_list, hypothesis_list, label_list, weight_list):

            premise_id = self.tokenizer.encode(premise, add_special_tokens=False)
            hypothesis_id = self.tokenizer.encode(hypothesis, add_special_tokens=False)
            pair_token_ids = [self.tokenizer.cls_token_id] + premise_id + [
                self.tokenizer.sep_token_id] + hypothesis_id + [self.tokenizer.sep_token_id]
            # pair_token_ids = premise_id + hypothesis_id
            # print("max token id=", max(pair_token_ids))
            premise_len = len(premise_id)
            hypothesis_len = len(hypothesis_id)

            segment_ids = torch.tensor(
                [0] * (premise_len + 2) + [1] * (hypothesis_len + 1))  # sentence 0 and sentence 1
            attention_mask_ids = torch.tensor([1] * (premise_len + hypothesis_len + 3))  # mask padded values
            if len(pair_token_ids) > MAX_LEN or len(segment_ids) > MAX_LEN or len(attention_mask_ids) > MAX_LEN:
                continue
            token_ids.append(torch.tensor(pair_token_ids))
            seg_ids.append(segment_ids)
            mask_ids.append(attention_mask_ids)
            y.append(self.label_dict[label])
            weights.append(weight)



============ Lines 281-405 ============
        preds = logits
    # print(preds.cpu().int(),labels.cpu().int())
    if tensors:
        y_true = labels.cpu().int()
        y_pred = preds.cpu().int()
    else:
        y_true = np.array(labels)
        y_pred = np.array(preds)
    temp = 0
    for i in range(y_true.shape[0]):
        temp += sum(np.logical_and(y_true[i], y_pred[i])) / sum(np.logical_or(y_true[i], y_pred[i]))
    accuracy = temp / y_true.shape[0]
    precision = sklearn.metrics.precision_score(y_true=y_true, y_pred=y_pred, average='samples', zero_division=0)
    recall = sklearn.metrics.recall_score(y_true=y_true, y_pred=y_pred, average='samples', zero_division=0)
    exact_match = sklearn.metrics.accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)
    micro_f1_score = sklearn.metrics.f1_score(y_true, y_pred, average='micro', zero_division=0)
    macro_f1_score = sklearn.metrics.f1_score(y_true, y_pred, average='macro', zero_division=0)
    return accuracy, precision, recall, exact_match, micro_f1_score, macro_f1_score


def train(model, dataset, optimizer, logger, save_path, device, epochs=5, ratio=0.04, positive_weight=12, debug=False):
    train_loader, val_loader, _ = dataset.get_data_loaders()
    min_val_loss = float('inf')
    loss_fn = nn.CrossEntropyLoss(reduction='none')
    loss_fn.to(device)
    for epoch in range(epochs):
        start = time.time()
        model.train()
        total_train_loss = 0
        total_train_acc = 0
        total_train_prec = 0
        total_train_rec = 0
        if ratio < 1:
            train_loader = dataset.get_undersampled(ratio)
        for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(train_loader):
            # print(weights.shape)
            if batch_idx % 10 == 0:
                logger.debug('%d %d', epoch, batch_idx)
            optimizer.zero_grad()
            pair_token_ids = pair_token_ids.to(device)
            mask_ids = mask_ids.to(device)
            seg_ids = seg_ids.to(device)
            labels = y.to(device)
            weights = weights.to(device)
            if debug:
                print(pair_token_ids.shape, seg_ids.shape, mask_ids.shape)
                break
            _, prediction = model(pair_token_ids,
                                  token_type_ids=seg_ids,
                                  attention_mask=mask_ids,
                                  labels=labels).values()
            # print(weights.shape)
            loss = loss_fn(prediction, labels)
            # print(loss.shape)
            len1 = loss.shape[0]
            loss = torch.dot(loss, weights) / len1
            # print('forward prop done')
            acc, prec, rec = multi_acc(prediction, labels)
            # print(acc,prec,rec)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()
            total_train_acc += acc.float()
            total_train_prec += prec
            total_train_rec += rec
        if debug:
            break
        train_acc = total_train_acc / len(train_loader)
        train_loss = total_train_loss / len(train_loader)
        train_prec = total_train_prec / len(train_loader)
        train_rec = total_train_rec / len(train_loader)
        model.eval()
        total_val_acc = 0
        total_val_loss = 0
        total_val_prec = 0
        total_val_rec = 0

        with torch.no_grad():
            for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(val_loader):
                pair_token_ids = pair_token_ids.to(device)
                mask_ids = mask_ids.to(device)
                seg_ids = seg_ids.to(device)
                labels = y.to(device)
                weights = weights.to(device)
                _, prediction = model(pair_token_ids,
                                      token_type_ids=seg_ids,
                                      attention_mask=mask_ids,
                                      labels=labels).values()
                loss = loss_fn(prediction, labels)
                len1 = loss.shape[0]
                loss = torch.dot(loss, weights) / len1
                acc, prec, rec = multi_acc(prediction, labels)

                total_val_loss += loss.item()
                total_val_acc += acc.float()
                total_val_prec += prec
                total_val_rec += rec

        val_acc = total_val_acc / len(val_loader)
        val_loss = total_val_loss / len(val_loader)
        val_rec = total_val_rec / len(val_loader)
        val_prec = total_val_prec / len(val_loader)
        flag = True
        if val_loss < min_val_loss:
            min_val_loss = val_loss
            logger.info("saving model")
            model.save_pretrained(save_path)
        else:
            flag = False
        end = time.time()
        hours, rem = divmod(end - start, 3600)
        minutes, seconds = divmod(rem, 60)

        logger.info(
            f'Epoch {epoch + 1}: train_loss: {train_loss:.4f} train_acc: {train_acc:.4f} train_prec: {train_prec:.4f} '
            f'train_rec: {train_rec:.4f}| val_loss: {val_loss:.4f} val_acc: {val_acc:.4f} val_prec: {val_prec:.4f} '
            f'val_rec: {val_rec:.4f}'
        )
        logger.info("{:0>2}:{:0>2}:{:05.2f}".format(int(hours), int(minutes), seconds))
        if not flag:
            break


def eval1(model, test_loader, logger, device):


============ Lines 401-440 ============
        if not flag:
            break


def eval1(model, test_loader, logger, device):
    with torch.no_grad():
        all_preds = []
        all_labels = []
        for batch_idx, (pair_token_ids, mask_ids, seg_ids, y, weights) in enumerate(test_loader):
            logger.debug("%d", batch_idx)
            pair_token_ids = pair_token_ids.to(device)
            mask_ids = mask_ids.to(device)
            seg_ids = seg_ids.to(device)
            labels = y.to(device)
            if model == "random":
                prediction = torch.rand([15, 3])
            else:
                _, prediction = model(pair_token_ids,
                                      token_type_ids=seg_ids,
                                      attention_mask=mask_ids,
                                      labels=labels).values()
            all_preds.append(torch.log_softmax(prediction, dim=1).argmax(dim=1))
            all_labels.append(labels)
        all_preds = 1 - torch.stack(all_preds)
        all_labels = 1 - torch.stack(all_labels)
        all_preds[all_preds < 0] = 0
        all_labels[all_labels < 0] = 0
        return get_metrics(all_preds, all_labels, sig=False)


if __name__ == "__main__":
    if torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"
    logger = get_logger()
    logger.info("device = %s", device)
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", "--tokenizer", help="tokenizer path")
    parser.add_argument("-m", "--model", help="model path")

In [52]:

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "/content/drive/MyDrive/FallacyLens/trained_model"

tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator",
    do_lower_case=True
)

tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

model = AutoModelForSequenceClassification.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

statement = "Everyone likes this product, so it must be the best."
hypothesis = "This is an example of ad populum logical fallacy"

inputs = tokenizer(
    statement,
    hypothesis,
    truncation=True,
    max_length=512,
    return_tensors="pt"
)

inputs = {key: value.to(device) for key, value in inputs.items()}

with torch.no_grad():
    logits = model(**inputs).logits
    probabilities = torch.softmax(logits, dim=-1)[0]

print("Device:", device)
print("Tokenizer vocabulary:", len(tokenizer))
print("Model embedding vocabulary:", model.get_input_embeddings().num_embeddings)
print("Output classes:", model.config.num_labels)
print("NLI probabilities:", {
    "entailment": round(probabilities[0].item(), 4),
    "contradiction": round(probabilities[1].item(), 4),
    "neutral": round(probabilities[2].item(), 4)
})

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Device: cuda
Tokenizer vocabulary: 30531
Model embedding vocabulary: 30531
Output classes: 3
NLI probabilities: {'entailment': 0.9985, 'contradiction': 0.0015, 'neutral': 0.0001}

In [53]:

import torch
import pandas as pd

labels = sorted(train_df["updated_label"].dropna().unique())

statement = "Everyone likes this product, so it must be the best."

results = []

model.eval()

for label in labels:
    hypothesis = f"This is an example of {label} logical fallacy"

    inputs = tokenizer(
        statement,
        hypothesis,
        truncation=True,
        max_length=512,
        return_tensors="pt"
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        logits = model(**inputs).logits
        probs = torch.softmax(logits, dim=-1)[0]

    results.append({
        "Fallacy": label,
        "Entailment": round(probs[0].item(), 4),
        "Contradiction": round(probs[1].item(), 4),
        "Neutral": round(probs[2].item(), 4)
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values("Entailment", ascending=False)

display(results_df.reset_index(drop=True))

                   Fallacy  Entailment  Contradiction  Neutral
0               ad populum      0.9985         0.0015   0.0001
1    faulty generalization      0.9887         0.0113   0.0000
2         fallacy of logic      0.6485         0.3514   0.0001
3     fallacy of extension      0.5570         0.4430   0.0001
4       circular reasoning      0.5215         0.4784   0.0001
5     fallacy of relevance      0.2389         0.7610   0.0002
6               ad hominem      0.1655         0.8344   0.0000
7             equivocation      0.1623         0.8373   0.0004
8              intentional      0.1355         0.8543   0.0102
9   fallacy of credibility      0.1042         0.8950   0.0008
10         false causality      0.0876         0.9123   0.0002
11       appeal to emotion      0.0846         0.9147   0.0007
12           false dilemma      0.0721         0.9268   0.0011

In [54]:

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)
from IPython.display import display

evaluation_df = test_df[
    ["source_article", "updated_label"]
].dropna().copy().reset_index(drop=True)

labels = sorted(train_df["updated_label"].dropna().unique())
predictions = []

model.eval()

for statement in evaluation_df["source_article"]:
    scores = []

    for label in labels:
        hypothesis = (
            f"This is an example of {label} logical fallacy"
        )

        inputs = tokenizer(
            statement,
            hypothesis,
            truncation=True,
            max_length=512,
            return_tensors="pt"
        )
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            logits = model(**inputs).logits[0]
            scores.append(logits[0].item())

    predictions.append(labels[int(np.argmax(scores))])

y_true = evaluation_df["updated_label"].tolist()
y_pred = predictions

print("Test statements:", len(y_true))
print("Accuracy:", round(accuracy_score(y_true, y_pred), 4))
print("Macro F1:", round(
    f1_score(y_true, y_pred, average="macro", zero_division=0), 4
))
print("Weighted F1:", round(
    f1_score(y_true, y_pred, average="weighted", zero_division=0), 4
))

print("\nClassification report:")
print(classification_report(
    y_true, y_pred, labels=labels, zero_division=0
))

print("Confusion matrix:")
display(pd.DataFrame(
    confusion_matrix(y_true, y_pred, labels=labels),
    index=labels,
    columns=labels
))

Test statements: 300
Accuracy: 0.48
Macro F1: 0.3632
Weighted F1: 0.4406

Classification report:
                        precision    recall  f1-score   support

            ad hominem       0.63      0.78      0.70        41
            ad populum       0.83      0.67      0.74        30
     appeal to emotion       0.67      0.35      0.46        23
    circular reasoning       0.36      0.53      0.43        19
          equivocation       0.00      0.00      0.00         5
fallacy of credibility       0.67      0.24      0.35        17
  fallacy of extension       0.00      0.00      0.00        21
      fallacy of logic       0.13      0.14      0.14        14
  fallacy of relevance       0.55      0.25      0.34        24
       false causality       0.57      0.22      0.32        18
         false dilemma       0.56      0.75      0.64        12
 faulty generalization       0.39      0.79      0.52        61
           intentional       0.12      0.07      0.09        15

              accuracy                           0.48       300
             macro avg       0.42      0.37      0.36       300
          weighted avg       0.47      0.48      0.44       300

Confusion matrix:

,ad hominem,ad populum,appeal to emotion,circular reasoning,equivocation,fallacy of credibility,fallacy of extension,fallacy of logic,fallacy of relevance,false causality,false dilemma,faulty generalization,intentional
ad hominem,32,0,1,0,0,0,0,0,1,0,1,5,1
ad populum,0,20,0,1,0,0,0,0,0,0,0,9,0
appeal to emotion,0,0,8,1,0,0,0,2,0,0,1,10,1
circular reasoning,1,0,0,10,0,0,0,4,0,0,0,4,0
equivocation,1,0,0,0,0,1,0,1,0,0,0,0,2
fallacy of credibility,1,0,0,1,0,4,0,1,0,2,0,7,1
fallacy of extension,8,0,0,2,0,0,0,2,4,0,1,4,0
fallacy of logic,0,0,1,3,0,0,0,2,0,0,0,8,0
fallacy of relevance,3,0,1,3,0,0,0,0,6,0,3,8,0
false causality,0,2,0,3,0,0,0,0,0,4,0,9,0
false dilemma,1,0,1,0,0,0,0,0,0,0,9,1,0
faulty generalization,4,2,0,2,0,1,0,0,0,1,1,48,2
intentional,0,0,0,2,0,0,0,3,0,0,0,9,1

In [55]:

import pandas as pd

mapping_path = "/content/logical-fallacy/data/mappings.csv"
mapping_df = pd.read_csv(mapping_path)

print("Available mapping columns:")
print(mapping_df.columns.tolist())

print("\nMappings for the 13 dataset categories:")
labels = sorted(train_df["updated_label"].dropna().unique())

display(
    mapping_df[
        mapping_df["Original Name"].isin(labels)
    ][
        [
            "Original Name",
            "Understandable Name",
            "Description",
            "Logical Form"
        ]
    ].sort_values("Original Name").reset_index(drop=True)
)

Available mapping columns:
['Original Name', 'Understandable Name', 'Description', 'Logical Form', 'Source for Logical Form ', 'Masked Logical Form']

Mappings for the 13 dataset categories:

,Original Name,Understandable Name,Description,Logical Form
0,ad hominem,personal attack,instead of addressing someone's argument or p...,Person 1 is claiming Y.\n\nPerson 1 is a moron...
1,ad populum,appeal to popularity,a fallacious argument which is based on affirm...,"A lot of people believe X.Therefore, X must be..."
2,appeal to emotion,appeal to emotion,manipulation of the recipient's emotions in or...,Claim X is made without evidence. In place of ...
3,circular reasoning,circular reasoning,when the end of an argument comes back to the ...,X is true because of Y.\n\nY is true because o...
4,equivocation,use of ambiguous language,when a key term or phrase in an argument is us...,Term X is used to mean Y in the premise.\nTerm...
5,fallacy of credibility,attacking the character of the speaker,attempts to disprove an argument by attacking ...,Person 1 makes claim Y. Person 2 claims Person...
6,fallacy of extension,exaggerating,attacking an exaggerated or caricatured versio...,Person 1 makes claim Y. Person 2 restates pers...
7,fallacy of logic,logical error,an error in the logical structure of an argument.,"If A is true, then B is true. B is true. There..."
8,fallacy of relevance,irrelevant argument,introducing premises or conclusions that have ...,"It is claimed that X implies Y, whereas X is u..."
9,false causality,false causality,statement that jumps to a conclusion implying ...,"A occurred, then B occurred.\nTherefore, A cau..."
10,false dilemma,excluding viable alternatives,presenting only two options or sides when ther...,Either X or Y is true.
11,faulty generalization,faulty generalization,an informal fallacy wherein a conclusion is dr...,Sample S is taken from population P. Sample S ...
12,intentional,intentionally wrong argument,some intentional (sometimes subconscious) acti...,Person 1 knows claim X is incorrect. They stil...

In [56]:

import torch
import pandas as pd

mapping_path = "/content/logical-fallacy/data/mappings.csv"
mapping_df = pd.read_csv(mapping_path).fillna("")

statement = "Everyone likes this product, so it must be the best."
device = next(model.parameters()).device
model.eval()

def get_entailment_score(statement, hypothesis):
    inputs = tokenizer(
        statement,
        hypothesis,
        truncation=True,
        max_length=512,
        return_tensors="pt"
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        logits = model(**inputs).logits[0]

    return logits[0].item()

results = []

for _, row in mapping_df.iterrows():
    label = row["Original Name"]

    if label not in labels:
        continue

    simple_hypothesis = (
        f"This is an example of {label} logical fallacy"
    )
    description = str(row["Description"]).strip()
    understandable_name = str(row["Understandable Name"]).strip()

    rich_hypothesis = (
        f"This argument demonstrates {understandable_name}: "
        f"{description}"
    )

    results.append({
        "Fallacy": label,
        "Simple score": get_entailment_score(
            statement, simple_hypothesis
        ),
        "Description score": get_entailment_score(
            statement, rich_hypothesis
        )
    })

comparison = pd.DataFrame(results)
display(
    comparison.sort_values(
        "Description score", ascending=False
    ).reset_index(drop=True).round(4)
)

                   Fallacy  Simple score  Description score
0               ad populum        4.8321             4.8696
1    faulty generalization        4.2161             3.0147
2               ad hominem        1.2930             2.1467
3             equivocation        0.7574             2.0656
4       circular reasoning        2.0539             2.0190
5              intentional       -0.1298             1.7383
6   fallacy of credibility        0.3130             1.6321
7          false causality        0.5381             1.6132
8            false dilemma       -0.0096             1.3270
9     fallacy of relevance        1.2119             1.2131
10        fallacy of logic        2.1791             1.1078
11    fallacy of extension        2.1416             0.6719
12       appeal to emotion        0.1935             0.6226

In [57]:

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, f1_score

mapping_df = pd.read_csv(
    "/content/logical-fallacy/data/mappings.csv"
).fillna("")

labels = sorted(train_df["updated_label"].dropna().unique())
mapping_lookup = mapping_df.set_index("Original Name").to_dict("index")

def predict_with_method(statement, method):
    scores = []

    for label in labels:
        info = mapping_lookup.get(label, {})
        name = str(info.get("Understandable Name", label)).strip()
        description = str(info.get("Description", "")).strip()

        if method == "simple":
            hypothesis = f"This is an example of {label} logical fallacy"
        else:
            hypothesis = (
                f"This argument demonstrates {name}: {description}"
            )

        inputs = tokenizer(
            statement, hypothesis,
            truncation=True, max_length=512,
            return_tensors="pt"
        )
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            logits = model(**inputs).logits[0]

        scores.append(logits[0].item())

    return labels[int(np.argmax(scores))]

validation_df = dev_df[
    ["source_article", "updated_label"]
].dropna().reset_index(drop=True)

simple_preds = []
description_preds = []

model.eval()

for i, row in validation_df.iterrows():
    simple_preds.append(
        predict_with_method(row["source_article"], "simple")
    )
    description_preds.append(
        predict_with_method(row["source_article"], "description")
    )

y_true = validation_df["updated_label"].tolist()

comparison_results = pd.DataFrame([
    {
        "Method": "Simple hypothesis",
        "Accuracy": accuracy_score(y_true, simple_preds),
        "Macro F1": f1_score(
            y_true, simple_preds, average="macro", zero_division=0
        )
    },
    {
        "Method": "Description hypothesis",
        "Accuracy": accuracy_score(y_true, description_preds),
        "Macro F1": f1_score(
            y_true, description_preds, average="macro", zero_division=0
        )
    }
])

display(comparison_results.round(4))

                   Method  Accuracy  Macro F1
0       Simple hypothesis    0.5000    0.4342
1  Description hypothesis    0.3267    0.2857

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

MODEL_DIR = "/content/drive/MyDrive/FallacyLens/trained_model"

print("Model folder exists:", os.path.isdir(MODEL_DIR))
if os.path.isdir(MODEL_DIR):
    print("Files:", os.listdir(MODEL_DIR))

Model folder exists: True
Files: ['config.json', 'model.safetensors']

In [3]:
!pip install fastapi uvicorn pyngrok

Requirement already satisfied: fastapi in /usr/local/lib/python3.13/dist-packages (0.141.1)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.13/dist-packages (0.54.0)
Collecting pyngrok
  Downloading pyngrok-9.1.0-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (1.9.0)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (2.14.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi) (0.0.5)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn) (8.5.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: PyYAML>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi) (2.50.1)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from starlette>=0.46.0->fastapi) (4.15.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->starlette>=0.46.0->fastapi) (3.20)
Downloading pyngrok-9.1.0-py3-none-any.whl (27 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-9.1.0

In [4]:
import os

print("Repository exists:", os.path.isdir("/content/logical-fallacy"))
print("Model code exists:", os.path.isfile("/content/logical-fallacy/logicedu.py"))

Repository exists: False
Model code exists: False

In [5]:
!git clone https://github.com/causalNLP/logical-fallacy.git /content/logical-fallacy

Cloning into '/content/logical-fallacy'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 254 (delta 44), reused 29 (delta 28), pack-reused 181 (from 1)
Receiving objects: 100% (254/254), 10.55 MiB | 4.80 MiB/s, done.
Resolving deltas: 100% (94/94), done.

In [6]:
import os

print("Repository exists:", os.path.isdir("/content/logical-fallacy"))
print("Model code exists:", os.path.isfile("/content/logical-fallacy/logicedu.py"))
print("Model files:", os.listdir(
    "/content/drive/MyDrive/FallacyLens/trained_model"
))

Repository exists: True
Model code exists: False
Model files: ['config.json', 'model.safetensors']

In [7]:
import os

REPO_DIR = "/content/logical-fallacy"

print("Repository contents:")
print(os.listdir(REPO_DIR))

print("\nPython files:")
for root, dirs, files in os.walk(REPO_DIR):
    dirs[:] = [d for d in dirs if d not in [".git", "__pycache__"]]
    for file in files:
        if file.endswith(".py"):
            print(os.path.join(root, file))

Repository contents:
['codes_for_analysis', 'codes_for_models', '.gitignore', '.git', 'README.md', 'data', 'saved_models', 'codes_to_get_data']

Python files:
/content/logical-fallacy/codes_for_analysis/evaluation/eval_finetune_results.py
/content/logical-fallacy/codes_for_analysis/evaluation/eval_zeroshot_results.py
/content/logical-fallacy/codes_for_models/experiments_round2/logicclimate_split.py
/content/logical-fallacy/codes_for_models/experiments_round2/logicclimate.py
/content/logical-fallacy/codes_for_models/experiments_round2/create_split.py
/content/logical-fallacy/codes_for_models/experiments_round2/weighted_cross_entropy.py
/content/logical-fallacy/codes_for_models/experiments_round2/remove_duplicates.py
/content/logical-fallacy/codes_for_models/experiments_round2/analyze_datasets.py
/content/logical-fallacy/codes_for_models/experiments_round2/remove_content_words.py
/content/logical-fallacy/codes_for_models/experiments_round2/estimate_percentage.py
/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py
/content/logical-fallacy/codes_for_models/experiments_round2/library.py
/content/logical-fallacy/codes_for_models/experiments_round2/siamese.py
/content/logical-fallacy/codes_for_models/experiments_round2/class_distribution.py
/content/logical-fallacy/codes_for_models/experiments_round2/save_model_offline.py
/content/logical-fallacy/codes_for_models/experiments_round2/experiment.py
/content/logical-fallacy/codes_for_models/experiments_round2/flair_zero_shot.py
/content/logical-fallacy/codes_for_models/experiments_round2/textattack1.py
/content/logical-fallacy/codes_for_models/finetune/main.py
/content/logical-fallacy/codes_for_models/finetune/util.py
/content/logical-fallacy/codes_for_models/finetune/evaluate.py
/content/logical-fallacy/codes_for_models/finetune/test_multi_select.py
/content/logical-fallacy/codes_for_models/zeroshot/model3_ppl.py
/content/logical-fallacy/codes_for_models/zeroshot/model4_matching.py
/content/logical-fallacy/codes_for_models/zeroshot/gen_model1_gpt3.py
/content/logical-fallacy/codes_for_models/zeroshot/model2_gpt3.py
/content/logical-fallacy/codes_for_models/zeroshot/model1_transfer_from_nli.py
/content/logical-fallacy/codes_to_get_data/preprocess_and_merge/data_prep.py
/content/logical-fallacy/codes_to_get_data/preprocess_and_merge/edu_clean_data.py

In [9]:
%cd /content/logical-fallacy/codes_for_models/experiments_round2

import logicedu
import inspect

print("Model classes:")
for name, obj in inspect.getmembers(logicedu, inspect.isclass):
    if "model" in name.lower() or "electra" in name.lower():
        print(name)

print("\nDataset class exists:", hasattr(logicedu, "MNLIDataset"))

/content/logical-fallacy/codes_for_models/experiments_round2

ImportError: cannot import name 'AdamW' from 'transformers' (/usr/local/lib/python3.13/dist-packages/transformers/__init__.py)

In [10]:
import os

FILE_PATH = "/content/logical-fallacy/codes_for_models/experiments_round2/logicedu.py"

with open(FILE_PATH, "r") as f:
    code = f.read()

code = code.replace(
    "from transformers import AutoTokenizer, AdamW, AutoModelForSequenceClassification",
    "from transformers import AutoTokenizer, AutoModelForSequenceClassification\nfrom torch.optim import AdamW"
)

with open(FILE_PATH, "w") as f:
    f.write(code)

print("Import fixed!")

Import fixed!

In [11]:
%cd /content/logical-fallacy/codes_for_models/experiments_round2

import logicedu
import inspect

print("Import successful!")

for name, obj in inspect.getmembers(logicedu, inspect.isclass):
    if "model" in name.lower() or "electra" in name.lower():
        print("Model class:", name)

print("Dataset class exists:", hasattr(logicedu, "MNLIDataset"))

/content/logical-fallacy/codes_for_models/experiments_round2
Import successful!
Model class: AutoModelForSequenceClassification
Dataset class exists: True

In [12]:
import json

MODEL_DIR = "/content/drive/MyDrive/FallacyLens/trained_model"

with open(f"{MODEL_DIR}/config.json", "r") as f:
    config = json.load(f)

print("Model architecture:", config.get("model_type"))
print("Number of labels:", config.get("num_labels"))
print("Hidden size:", config.get("hidden_size"))
print("Vocabulary size:", config.get("vocab_size"))

Model architecture: electra
Number of labels: None
Hidden size: 768
Vocabulary size: 30531

In [13]:
import torch
from transformers import AutoConfig, AutoModelForSequenceClassification

MODEL_DIR = "/content/drive/MyDrive/FallacyLens/trained_model"

# Read the saved configuration
config = AutoConfig.from_pretrained(MODEL_DIR)

print("Model type:", config.model_type)
print("Number of labels:", config.num_labels)
print("Vocabulary size:", config.vocab_size)
print("Architecture:", config.architectures)

# Load the saved checkpoint
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_DIR,
    config=config
)

model.eval()

print("\nModel loaded successfully!")
print("Output labels:", model.config.num_labels)
print("Device:", next(model.parameters()).device)

Model type: electra
Number of labels: 3
Vocabulary size: 30531
Architecture: ['ElectraForSequenceClassification']

Loading weights:   0%|          | 0/201 [00:01<?, ?it/s]

Model loaded successfully!
Output labels: 3
Device: cpu

In [14]:
from transformers import AutoTokenizer
import torch

MODEL_DIR = "/content/drive/MyDrive/FallacyLens/trained_model"

# Load the same tokenizer used during training
tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator",
    do_lower_case=True
)

tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

# Ensure the model uses the expected vocabulary size
print("Tokenizer vocabulary:", len(tokenizer))
print("Model vocabulary:", model.config.vocab_size)

# Test argument
argument = (
    "Everyone believes this product is the best, "
    "so it must be the best product."
)

hypothesis = "This is an example of ad populum logical fallacy"

inputs = tokenizer(
    argument,
    hypothesis,
    return_tensors="pt",
    truncation=True,
    max_length=256
)

model.eval()

with torch.no_grad():
    outputs = model(**inputs)
    probabilities = torch.softmax(outputs.logits, dim=-1)[0]

print("\nTest argument:", argument)
print("Hypothesis:", hypothesis)
print("Entailment score:", round(probabilities[0].item(), 4))
print("Contradiction score:", round(probabilities[1].item(), 4))
print("Neutral score:", round(probabilities[2].item(), 4))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizer vocabulary: 30531
Model vocabulary: 30531

Test argument: Everyone believes this product is the best, so it must be the best product.
Hypothesis: This is an example of ad populum logical fallacy
Entailment score: 0.9985
Contradiction score: 0.0015
Neutral score: 0.0001

In [15]:

import torch

FALLACY_CATEGORIES = [
    "ad hominem",
    "ad populum",
    "appeal to emotion",
    "circular reasoning",
    "equivocation",
    "fallacy of credibility",
    "fallacy of extension",
    "fallacy of logic",
    "fallacy of relevance",
    "false causality",
    "false dilemma",
    "faulty generalization",
    "intentional"
]

def predict_fallacies(argument):
    argument = argument.strip()

    if not argument:
        return []

    results = []

    model.eval()

    with torch.no_grad():
        for category in FALLACY_CATEGORIES:
            hypothesis = (
                f"This is an example of {category} logical fallacy"
            )

            inputs = tokenizer(
                argument,
                hypothesis,
                return_tensors="pt",
                truncation=True,
                max_length=256
            )

            outputs = model(**inputs)
            scores = torch.softmax(outputs.logits, dim=-1)[0]

            results.append({
                "fallacy": category,
                "entailment_score": float(scores[0]),
                "contradiction_score": float(scores[1]),
                "neutral_score": float(scores[2])
            })

    results.sort(
        key=lambda item: item["entailment_score"],
        reverse=True
    )

    return results


# Test all 13 categories
test_argument = (
    "Everyone believes this product is the best, "
    "so it must be the best product."
)

predictions = predict_fallacies(test_argument)

for index, result in enumerate(predictions[:5], start=1):
    print(
        f"{index}. {result['fallacy']}: "
        f"{result['entailment_score']:.4f}"
    )

1. ad populum: 0.9985
2. faulty generalization: 0.9867
3. circular reasoning: 0.7670
4. fallacy of logic: 0.6200
5. fallacy of extension: 0.5499

In [16]:
%pip install fastapi uvicorn pyngrok requests

Requirement already satisfied: fastapi in /usr/local/lib/python3.13/dist-packages (0.141.1)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.13/dist-packages (0.54.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.13/dist-packages (9.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (1.9.0)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (2.14.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi) (0.0.5)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn) (8.5.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: PyYAML>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.10.23)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi) (2.50.1)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from starlette>=0.46.0->fastapi) (4.15.1)

In [17]:

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import threading
import uvicorn

app = FastAPI(title="FallacyLens API")

class ArgumentRequest(BaseModel):
    argument: str

@app.get("/")
def home():
    return {"status": "online", "service": "FallacyLens API"}

@app.post("/predict")
def predict(request: ArgumentRequest):
    argument = request.argument.strip()

    if not argument:
        raise HTTPException(
            status_code=400,
            detail="Please enter an argument."
        )

    try:
        results = predict_fallacies(argument)

        return {
            "argument": argument,
            "predictions": results[:5]
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

server_thread = threading.Thread(
    target=run_server,
    daemon=True
)
server_thread.start()


print("FallacyLens API server started on port 8000.")

FallacyLens API server started on port 8000.

In [18]:

from pyngrok import ngrok
from getpass import getpass

# Enter your token privately; do not share it in chat.
NGROK_TOKEN = getpass("Enter your ngrok auth token: ")
ngrok.set_auth_token(NGROK_TOKEN)

public_url = ngrok.connect(8000, "http").public_url

print("FallacyLens API URL:", public_url)

Enter your ngrok auth token: ··········
FallacyLens API URL: https://stretch-sequence-clammy.ngrok-free.dev

In [1]:
/content/drive/MyDrive/FallacyLens/trained_model

NameError: name 'content' is not defined

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
MODEL_DIR = "/content/drive/MyDrive/FallacyLens/trained_model"

import os

print(os.path.exists(MODEL_DIR))
print(os.listdir(MODEL_DIR))

True
['config.json', 'model.safetensors']

In [4]:
from transformers import AutoConfig, AutoModelForSequenceClassification

config = AutoConfig.from_pretrained(MODEL_DIR)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_DIR,
    config=config
)

print("FallacyLens model loaded successfully!")

Loading weights:   0%|          | 0/201 [00:01<?, ?it/s]

FallacyLens model loaded successfully!

In [5]:
from transformers import AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained(
    "google/electra-base-discriminator",
    do_lower_case=True
)

tokenizer.add_special_tokens({
    "additional_special_tokens": [
        "[A]", "[B]", "[C]", "[D]", "[E]",
        "[F]", "[G]", "[H]", "[I]"
    ]
})

print("Tokenizer loaded successfully!")
print("Model device:", next(model.parameters()).device)
print("Number of labels:", model.config.num_labels)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizer loaded successfully!
Model device: cpu
Number of labels: 3

In [6]:
print("predict_fallacies" in globals())

False

In [7]:

import torch
import torch.nn.functional as F

FALLACY_CATEGORIES = [
    "ad hominem",
    "ad populum",
    "appeal to emotion",
    "circular reasoning",
    "equivocation",
    "fallacy of credibility",
    "fallacy of extension",
    "fallacy of logic",
    "fallacy of relevance",
    "false causality",
    "false dilemma",
    "faulty generalization",
    "intentional"
]

def predict_fallacies(argument, top_k=5):
    # Validate the input
    if not isinstance(argument, str) or not argument.strip():
        raise ValueError("Please enter a non-empty argument.")

    if not isinstance(top_k, int) or not 1 <= top_k <= len(FALLACY_CATEGORIES):
        raise ValueError("top_k must be between 1 and 13.")

    model.eval()
    device = next(model.parameters()).device

    # Compare the argument with each fallacy hypothesis
    hypotheses = [
        f"This is an example of {category} logical fallacy."
        for category in FALLACY_CATEGORIES
    ]

    encoded = tokenizer(
        [argument] * len(hypotheses),
        hypotheses,
        padding=True,
        truncation=True,
        max_length=256,
        return_tensors="pt"
    )

    encoded = {key: value.to(device) for key, value in encoded.items()}

    with torch.no_grad():
        outputs = model(**encoded)
        probabilities = F.softmax(outputs.logits, dim=-1)

    # The project's model uses NLI labels:
    # entailment = 0, contradiction = 1, neutral = 2
    entailment_scores = probabilities[:, 0]

    ranked_indices = torch.argsort(
        entailment_scores, descending=True
    )[:top_k]

    results = []
    for index in ranked_indices.tolist():
        results.append({
            "fallacy": FALLACY_CATEGORIES[index],
            "score": round(entailment_scores[index].item(), 4)
        })

    return results

print("predict_fallacies() defined successfully!")

predict_fallacies() defined successfully!

In [8]:

import torch
import torch.nn.functional as F

FALLACY_CATEGORIES = [
    "ad hominem",
    "ad populum",
    "appeal to emotion",
    "circular reasoning",
    "equivocation",
    "fallacy of credibility",
    "fallacy of extension",
    "fallacy of logic",
    "fallacy of relevance",
    "false causality",
    "false dilemma",
    "faulty generalization",
    "intentional"
]

def predict_fallacies(argument, top_k=5):
    # Validate the input
    if not isinstance(argument, str) or not argument.strip():
        raise ValueError("Please enter a non-empty argument.")

    if not isinstance(top_k, int) or not 1 <= top_k <= len(FALLACY_CATEGORIES):
        raise ValueError("top_k must be between 1 and 13.")

    model.eval()
    device = next(model.parameters()).device

    # Compare the argument with each fallacy hypothesis
    hypotheses = [
        f"This is an example of {category} logical fallacy."
        for category in FALLACY_CATEGORIES
    ]

    encoded = tokenizer(
        [argument] * len(hypotheses),
        hypotheses,
        padding=True,
        truncation=True,
        max_length=256,
        return_tensors="pt"
    )

    encoded = {key: value.to(device) for key, value in encoded.items()}

    with torch.no_grad():
        outputs = model(**encoded)
        probabilities = F.softmax(outputs.logits, dim=-1)

    # The project's model uses NLI labels:
    # entailment = 0, contradiction = 1, neutral = 2
    entailment_scores = probabilities[:, 0]

    ranked_indices = torch.argsort(
        entailment_scores, descending=True
    )[:top_k]

    results = []
    for index in ranked_indices.tolist():
        results.append({
            "fallacy": FALLACY_CATEGORIES[index],
            "score": round(entailment_scores[index].item(), 4)
        })

    return results

print("predict_fallacies() defined successfully!")

predict_fallacies() defined successfully!

In [9]:

test_argument = (
    "Everyone believes this product is the best, "
    "so it must be the best product."
)

results = predict_fallacies(test_argument)

print("Input:", test_argument)
print("\nTop predictions:")

for i, result in enumerate(results, start=1):
    print(
        f"{i}. {result['fallacy']} "
        f"- entailment score: {result['score']}"
    )

Input: Everyone believes this product is the best, so it must be the best product.

Top predictions:
1. ad populum - entailment score: 0.9985
2. faulty generalization - entailment score: 0.9882
3. circular reasoning - entailment score: 0.7511
4. fallacy of logic - entailment score: 0.6189
5. fallacy of extension - entailment score: 0.5478

In [10]:
!pip install fastapi uvicorn pyngrok nest-asyncio

Requirement already satisfied: fastapi in /usr/local/lib/python3.13/dist-packages (0.141.1)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.13/dist-packages (0.54.0)
Collecting pyngrok
  Downloading pyngrok-9.1.0-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (1.6.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (1.9.0)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (2.14.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from fastapi) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi) (0.0.5)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn) (8.5.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: PyYAML>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi) (2.50.1)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from starlette>=0.46.0->fastapi) (4.15.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->starlette>=0.46.0->fastapi) (3.20)
Downloading pyngrok-9.1.0-py3-none-any.whl (27 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-9.1.0

In [11]:

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import nest_asyncio
import uvicorn
from pyngrok import ngrok

app = FastAPI(title="FallacyLens API")

class PredictionRequest(BaseModel):
    argument: str
    top_k: int = 5

@app.get("/")
def home():
    return {"message": "FallacyLens API is running"}

@app.post("/predict")
def predict(request: PredictionRequest):
    try:
        results = predict_fallacies(
            request.argument,
            top_k=request.top_k
        )
        return {
            "argument": request.argument,
            "predictions": results
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

print("FastAPI app created successfully!")

FastAPI app created successfully!

In [22]:

from pyngrok import ngrok

ngrok.set_auth_token("3LJRyQmKkF285BMWiBTFo7kk14e_6NEfSrJY4AdvJoUoPM3k8")

# Close old tunnels if any are still active
ngrok.kill()

public_url = ngrok.connect(8000).public_url
print("Your public API URL:", public_url)
print("Prediction endpoint:", public_url + "/predict")

PyngrokNgrokError: An error occurred when saving the auth token: b'Authtoken already set in configuration file: /root/.config/ngrok/ngrok.yml\n'

In [23]:
from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8000).public_url

print("Your public API URL:", public_url)
print("Your prediction endpoint:", public_url + "/predict")

Your public API URL: https://stretch-sequence-clammy.ngrok-free.dev
Your prediction endpoint: https://stretch-sequence-clammy.ngrok-free.dev/predict

In [24]:
import requests

try:
    response = requests.get("http://127.0.0.1:8000/", timeout=3)
    print("Server status:", response.status_code)
    print(response.text)
except Exception as e:
    print("FastAPI is not reachable:", e)

FastAPI is not reachable: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b1da3f1c830>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [25]:
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import nest_asyncio
import uvicorn

app = FastAPI(title="FallacyLens API")

class PredictionRequest(BaseModel):
    argument: str
    top_k: int = 5

@app.get("/")
def home():
    return {"message": "FallacyLens API is running"}

@app.post("/predict")
def predict(request: PredictionRequest):
    try:
        results = predict_fallacies(
            request.argument,
            top_k=request.top_k
        )
        return {
            "argument": request.argument,
            "predictions": results
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

print("FastAPI app created successfully!")

FastAPI app created successfully!

In [26]:
nest_asyncio.apply()

config = uvicorn.Config(
    app,
    host="0.0.0.0",
    port=8000,
    log_level="info"
)

server = uvicorn.Server(config)
await server.serve()

INFO:     Started server process [784]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [784]

import requests

response = requests.get("http://127.0.0.1:8000/", timeout=5)
print(response.status_code)
print(response.json())

In [28]:
import requests

response = requests.get("http://127.0.0.1:8000/", timeout=5)
print(response.status_code)
print(response.json())

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b1da3fcc190>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [29]:
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="FallacyLens API")

class PredictionRequest(BaseModel):
    argument: str
    top_k: int = 5

@app.get("/")
def home():
    return {"message": "FallacyLens API is running"}

@app.post("/predict")
def predict(request: PredictionRequest):
    try:
        results = predict_fallacies(
            request.argument,
            top_k=request.top_k
        )
        return {
            "argument": request.argument,
            "predictions": results
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

print("FallacyLens API is ready.")

FallacyLens API is ready.

In [33]:
import nest_asyncio
import uvicorn

nest_asyncio.apply()

config = uvicorn.Config(
    app,
    host="0.0.0.0",
    port=8000,
    log_level="info"
)

server = uvicorn.Server(config)
await server.serve()

INFO:     Started server process [784]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [784]

In [34]:
import requests

r = requests.get("http://127.0.0.1:8000/", timeout=10)
print("Status:", r.status_code)
print("Response:", r.text)

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b1da3fd6450>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [35]:
import threading
import time
import requests
import uvicorn

def run_api():
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )

api_thread = threading.Thread(target=run_api, daemon=True)
api_thread.start()

time.sleep(3)

try:
    r = requests.get("http://127.0.0.1:8000/", timeout=10)
    print("Status:", r.status_code)
    print("Response:", r.text)
except Exception as e:
    print("ERROR:", e)

INFO:     Started server process [784]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

INFO:     127.0.0.1:51570 - "GET / HTTP/1.1" 200 OK
Status: 200
Response: {"message":"FallacyLens API is running"}

In [36]:
from pyngrok import ngrok

public_url = ngrok.connect(8000).public_url

print("Public URL:", public_url)
print("API URL:", public_url + "/predict")
print("Documentation:", public_url + "/docs")

Public URL: https://stretch-sequence-clammy.ngrok-free.dev
API URL: https://stretch-sequence-clammy.ngrok-free.dev/predict
Documentation: https://stretch-sequence-clammy.ngrok-free.dev/docs